objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/QTCPOtoSDStatus__c.field-meta.xml
<CustomField>
    <fullName>QTCPOtoSDStatus__c</fullName>
    <description>This field is used to keep a track of shipping status of an Order PO to the Specialty Distributor</description>
    <label>QTC PO to SD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PurchaseOrderService.cls
public inherited sharing class PurchaseOrderService
{

	static final Integer ERRORCODE_TWOHUNDRED = 200;
	static final String QTCPOUPDATEFAILEDWITHBELOWRESPONSE = 'QTC PO Update Failed With Below Response : ';

	public void sendQTCPONoticeToSD(Set<Id> orderIds)
	{

		Map<Id, String> orderIdNServiceInputBody = new PurchaseOrderServiceHelper().getCalloutInputRequestBody(orderIds);

		if (orderIdNServiceInputBody.isEmpty())
		{
			return;
		}

		HttpRequest request = new HttpRequest();
		List<Order__c> orderUpdateInfo = new List<Order__c>();

		for (Id orderId : orderIds)
		{
			if (String.isBlank(orderIdNServiceInputBody.get(orderId)))
			{
				continue;
			}

			try
			{
				request = new HttpRequest();
				request.setMethod(CalloutConstants.POST);
				request.setEndpoint('callout:PurchaseOrderConnection');
				request.setHeader('Content-Type', 'application/json;');
				request.setHeader('client_id', '{!$Credential.UserName}');
				request.setHeader('client_secret', '{!$Credential.Password}');
				request.setBody(orderIdNServiceInputBody.get(orderId));
				request.setTimeout(Integer.valueOf(Label.RequestTimeout));
				Application.logEntry.info('Request is INT-03 ' + request.getBody());

				handleCalloutResponse(new Http().send(request), orderId, orderUpdateInfo);
			}
			catch (Exception excp)
			{
				Application.logEntry.error(excp);
				updateOrdersToFailed(orderIds);
			}
		}
		updateQTCPOToSAPStatus(orderUpdateInfo);
	}

	void updateQTCPOToSAPStatus(List<Order__c> ordersToUpdateQTCPOToSDStatus)
	{
		if (ordersToUpdateQTCPOToSDStatus.isEmpty()) return ;

		fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] {Order__c.SObjectType});
		uow.registerDirty(ordersToUpdateQTCPOToSDStatus);
		uow.commitWork();
	}

	void updateOrdersToFailed(Set<Id> orderIds)
	{
		List<Order__c> ordersToUpdateFailureStatus = new List<Order__c>();
		for (Id orderId : orderIds)
		{
			ordersToUpdateFailureStatus.add(new Order__c(Id = orderId, QTCPOtoSDStatus__c = CalloutConstants.FAILURE));
		}

		fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] {Order__c.SObjectType});
		uow.registerDirty(ordersToUpdateFailureStatus);
		uow.commitWork();
	}

	void handleCalloutResponse(HttpResponse response, Id OrderId, List<Order__c> orderUpdateInfo)
	{
		Application.logEntry.info('Response is INT-03 ' + response.getBody());
		SDNotificationServiceOutput output = (SDNotificationServiceOutput) JSON.deserialize(String.escapeSingleQuotes(response.getBody()), SDNotificationServiceOutput.Class);
		output.orderId = OrderId;
		Boolean transactionSucceeded = determineWhetherServiceFailedOrSucceeded(response.getStatusCode(), output);

		orderUpdateInfo.add(new Order__c(Id = OrderId,
				QTCPOtoSDStatus__c = transactionSucceeded ?
						CalloutConstants.SUCCESS : CalloutConstants.FAILURE));
		if (!transactionSucceeded)
		{
			Application.logEntry.error(QTCPOUPDATEFAILEDWITHBELOWRESPONSE + JSON.serializePretty(output));
		}
	}

	Boolean determineWhetherServiceFailedOrSucceeded(Integer statusCode, SDNotificationServiceOutput output)
	{
		return ERRORCODE_TWOHUNDRED == statusCode && output != null && CalloutConstants.SUCCESS.equalsIgnoreCase(output.status);
	}
}