objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/OrderPlacementRescheduleController.cls
public with sharing class OrderPlacementRescheduleController
{
	private OrderPlacementRescheduleController() //Empty Constructor
	{
	}

	public inherited sharing class DataForComponentLoad
	{
		@AuraEnabled
		public Boolean satisfiedAllValidations { get; set; }
		@AuraEnabled
		public Order__c order { get; set; }
		@AuraEnabled
		public String errorMessageOnValidationsFail { get; set; }

		public DataForComponentLoad(Boolean satisfiedAllValidations,
				Order__c order,
				String errorMessageOnValidationsFail)
		{
			this.satisfiedAllValidations = satisfiedAllValidations;
			this.order = order;
			this.errorMessageOnValidationsFail = errorMessageOnValidationsFail;
		}

	}

	@AuraEnabled
	public static DataForComponentLoad checkForValidationsNPassReqData(String orderId)
	{
		try
		{
			List<Order__c> orders = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType))
													  .selectOrdersByOrderId(new Set<Id> {orderId});
			return isOrderStatusSubmittedOrVerified(orders[0]) ? checkForFurtherValidationsNPassData(orders[0]) :
																 getOnLoadData(orders[0],
																 getError(orders[0].OrderStatus__c));
		}
		catch (Exception excp)
		{
			throw logExceptionNGetAuraHandledException(excp);
		}
	}

	static String getError(String orderStatus)
	{
		return StaticConstants.REQUESTTYPENEW.equalsIgnoreCase(orderStatus) ? Label.OrderCantBeRescheduledWhenOrderIsNew : Label.OrderCantBeRescheduledViaSystemAsOrderIsInProgress;
	}

	static Boolean isOrderStatusSubmittedOrVerified(Order__c order)
	{
		return StaticConstants.orderSubmitted.equalsIgnoreCase(order.OrderStatus__c) ||
				StaticConstants.orderVerified.equalsIgnoreCase(order.OrderStatus__c);
	}

	static DataForComponentLoad getOnLoadData(Order__c order, String errorMessage)
	{
		return new DataForComponentLoad(string.isBlank(errorMessage), order, errorMessage);
	}

	static DataForComponentLoad checkForFurtherValidationsNPassData(Order__c order)
	{
		List<BusinessHours> businessHours = ((BusinessHoursSelector) Application.Selector.newInstance(BusinessHours.SObjectType))
				.selectBusinessHoursByName(Label.BusinessHoursNameForOrderSubmissionRescheduling);
		BusinessHoursCalculatorImp bhCalculatorImp = new BusinessHoursCalculatorImp(businessHours[0].Id);
		Integer noOfDays = Integer.valueOf(bhCalculatorImp.getDifferenceBetweenTimeSpans(Date.today(), order.ApheresisPickUpDate__c) / BusinessHoursCalculator.oneDayToMilliSeconds);
		return getOnLoadData(order, noOfDays >= 0 && noOfDays <= 1 ? Label.OrderCantBeRescheduledViaSystemAsOrderIsInProgress : '');
	}

	@AuraEnabled
	public static String sendSlotBookingRequest(Object confirmSlotAndOrderUpdateInfo)
	{
		try
		{
			SlotAndOrderUpdateInfo slotAndOrderUpdateInfo = (SlotAndOrderUpdateInfo) JSON.deserialize(JSON.serialize(confirmSlotAndOrderUpdateInfo),
					SlotAndOrderUpdateInfo.class);

			slotAndOrderUpdateInfo.order = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType))
                							.selectOrdersByOrderId(new Set<Id>{slotAndOrderUpdateInfo.orderId})[0];
			return new ConfirmApheresisSlotService().confirmApheresisSlot(slotAndOrderUpdateInfo);
		}
		catch (Exception excp)
		{
			throw logExceptionNGetAuraHandledException(excp);
		}
	}
	static AuraHandledException logExceptionNGetAuraHandledException(Exception excp)
	{
		Application.logEntry.error(excp);
		AuraHandledException auraHandledException = new AuraHandledException(excp.getMessage());
		auraHandledException.setMessage(excp.getStackTraceString());
		return auraHandledException;
	}
}