objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ASNToAnaplanStatus__c.field-meta.xml
<CustomField>
    <fullName>ASNToAnaplanStatus__c</fullName>
    <description>Apheresis Shipment Notice to Anaplan Status</description>
    <label>ASN to Anaplan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/CryoCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>CryoCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Cell Pickup Date and Time related to the order.</description>
    <label>Cryo Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/CryoSiteType__c.field-meta.xml
<CustomField>
    <fullName>CryoSiteType__c</fullName>
    <description>This field holds value of Cryo Site records type field value</description>
    <formula>TEXT(CryoSite__r.Type)</formula>
    <label>Cryo Site Type</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/FreshCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FreshCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Fresh Cell Pickup Date and Time related to the order.</description>
    <label>Fresh Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AnaplanNotificationService.cls
public with sharing class AnaplanNotificationService
{
	private static final String COMMERCIAL = 'Commercial';
	private static final String FAILURESTATUS = 'Failure';
	private static final String LOCAL = 'Local';
	private static final String NA = 'NA';
	private static final String PUT = 'PUT';
	private static final String RARITAN = 'Raritan';
	private static final String SHIPMENT = 'Shipment';
	private static final String THIRDPARTY = '3rd party';
	private static final String US = 'US';

	public void sendApheresisShipmentNoticeToAnaplan(Set<Id> orderIds)
	{
		HttpRequest req = new HttpRequest();
		req.setMethod(PUT);
		req.setEndpoint('callout:ShipmentAndMilestoneManufacturing');
		req.setHeader('Content-Type', 'application/json;');
		req.setHeader('client_id', '{!$Credential.UserName}');
		req.setHeader('client_secret', '{!$Credential.Password}');
		req.setTimeout(Integer.valueOf(Label.RequestTimeout));
		List<Order__c> listOrders = (List<Order__c>) Application.Selector.selectById(orderIds);
		if (listOrders.isEmpty()) return ;

		HttpResponse resp = new HttpResponse();
		Http httpProtocol = new Http();

		for (Order__c order : listOrders)
		{
			AphShipNoticeRequestWrapper requestWrapper = new AphShipNoticeRequestWrapper(order);
			String jsonStr = JSON.serialize(requestWrapper);
			req.setBody(jsonStr);
			if (req == null) return ;
			try
			{
				resp = httpProtocol.send(req);
				AphShipNoticeResponseWrapper output = (AphShipNoticeResponseWrapper) JSON.deserialize(resp.getBody(), AphShipNoticeResponseWrapper.class);
				order.ASNToAnaplanStatus__c = FAILURESTATUS;
				if (checkCalloutStatus(resp.getStatusCode(), output))
				{
					order.ASNToAnaplanStatus__c = CalloutConstants.SUCCESS;
				}
				else
				{
					Application.logEntry.error(string.format('{0} : {1}', new List<String> {output.code, output.message}));
				}
				System.debug('INT 13 Request ' + req.getBody());
				System.debug('INT 13 Response' + resp.getBody());
			}
			catch (Exception e)
			{
				Application.logEntry.error(e);
			}
			System.debug('INT 13 Request: ' + req.getBody());
			System.debug('INT 13 Response:' + resp.getBody());
		}

		if (!listOrders.isEmpty())
		{
			fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] {Order__c.SObjectType});
			uow.registerDirty(listOrders);
			uow.commitWork();
		}
	}
	boolean checkCalloutStatus(Integer statusCode, AphShipNoticeResponseWrapper output)
	{
		return CalloutConstants.TWOHUNDRED == statusCode && output != null && CalloutConstants.SUCCESS.equalsIgnoreCase(output.status);
	}

	public class AphShipNoticeRequestWrapper
	{
		String CARTOrderId;
		String status;
		String eventDate;
		String eventType;
		String therapyType;
		String country;
		String region;

		String getEventDate(Order__c order)
		{
			String pickupDate = '' ;
			if (((RARITAN.equalsIgnoreCase(order.CryoSiteType__c)) || (THIRDPARTY.equalsIgnoreCase(order.CryoSiteType__c))) &&
					order.FreshCellPickupDateAndTime__c != null)
			{
				pickupDate = String.valueOf(order.FreshCellPickupDateAndTime__c.date());
			}
			else if (LOCAL.equalsIgnoreCase(order.CryoSiteType__c) && order.CryoCellPickupDateAndTime__c != null)
			{
				pickupDate = String.valueOf(order.CryoCellPickupDateAndTime__c.date());
			}
			return pickupDate;
		}

		public AphShipNoticeRequestWrapper(Order__c Orders)
		{
			this.CARTOrderId = String.valueOf(Orders.CartOrderId__c);
			this.status = String.valueOf(Orders.OrderStatus__c);
			this.eventDate = getEventDate(Orders);
			this.eventType = SHIPMENT;
			this.therapyType = COMMERCIAL;
			this.country = US;
			this.region = NA;
		}
	}

	public class AphShipNoticeResponseWrapper
	{
		public String code { get; set; }
		public String message { get; set; }
		public String status { get; set; }
		public String CARTOrderID { get; set; }

		public AphShipNoticeResponseWrapper()
		{
			// Empty Constructor
		}

		public AphShipNoticeResponseWrapper(JSONParser parser)
		{
			while (parser.nextToken() != System.JSONToken.END_OBJECT)
			{
				if (parser.getCurrentToken() == System.JSONToken.FIELD_NAME)
				{
					String text = parser.getText();
					if (parser.nextToken() != System.JSONToken.VALUE_NULL)
					{
						switch on text
						{
							when 'code'
							{
								code = parser.getText();
							}
							when 'message'
							{
								message = parser.getText();
							}
							when 'CARTOrderId'
							{
								CARTOrderID = parser.getText();
							}
							when 'status'
							{
								status = parser.getText();
							}
						}
					}
				}
			}
		}

		public AphShipNoticeResponseWrapper parse(String json)
		{
			System.JSONParser parser = System.JSON.createParser(json);
			return new AphShipNoticeResponseWrapper(parser);
		}
	}
}