objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/OrderMilestones__c/OrderMilestones__c.object-meta.xml
<CustomObject>
    <label>Order Milestones</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderMilestones__c/fields/MilestoneDatetime__c.field-meta.xml
<CustomField>
    <fullName>MilestoneDatetime__c</fullName>
    <description>Date/time related to the Order Milestone.</description>
    <label>Milestone Datetime</label>
    <type>DateTime</type>
</CustomField>

objects/OrderMilestones__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order related to the milestone.</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Milestones</relationshipLabel>
    <relationshipName>OrderMilestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/ManufacturingMilestonesUpdteSrvceHelper.cls
public inherited sharing class ManufacturingMilestonesUpdteSrvceHelper implements ICalloutServiceHelper {
    
    public Map<Id, String> getCalloutInputRequestBody(Set<Id> orderMilestoneIds)
    {
        Map<Id, String> orderIdNInputBody = new Map<Id, String>();
        
        Map<Id,OrderMilestones__c> orderMilestonesInfo = new Map<Id,OrderMilestones__c>(
            											((OrderMilestonesSelector) Application.Selector
                                                         .newInstance(OrderMilestones__c.SObjectType))
                                                         .selectById(orderMilestoneIds));
        
        OrderMilestones__c orderMilestone = new OrderMilestones__c();
        ManufacturingMilestonesUpdateSrvceInput input = new ManufacturingMilestonesUpdateSrvceInput();
        
        for(Id orderMilestoneId : orderMilestoneIds)
        {
            input  = new ManufacturingMilestonesUpdateSrvceInput();
            orderMilestone = orderMilestonesInfo.get(orderMilestoneId);
            input.CARTOrderId = orderMilestone.Order__r.CartOrderId__c;
            input.status = orderMilestone.Name;
            input.eventDate = orderMilestone.MilestoneDatetime__c == null ? null : string.valueOf(
                              orderMilestone.MilestoneDatetime__c.Date());
            orderIdNInputBody.put(orderMilestone.Order__c,JSON.serialize(input));
        } 
        
        return orderIdNInputBody;
    }
}