objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/AtlasOrderId__c.field-meta.xml
<CustomField>
    <fullName>AtlasOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration, stores the Atlas Order ID value.</description>
    <externalId>true</externalId>
    <label>Atlas Order ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/ConfirmedFPDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedFPDeliveryDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Confirmed FP Delivery Date of the order.</description>
    <label>Confirmed DP Delivery Date from Site</label>
    <type>Date</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/DPOkToShipToSAPStatus__c.field-meta.xml
<CustomField>
    <fullName>DPOkToShipToSAPStatus__c</fullName>
    <description>DP Ok to Ship to SAP Status</description>
    <label>DP Ok to Ship to SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the enrolled patient.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Patient)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/OrdersShipmentServiceTest.cls
@IsTest(SeeAllData=false)
public with sharing class OrdersShipmentServiceTest {

	//GIVEN - A care plan has been created for a patient, and order has been generated.
	@TestSetup static void testDataSetup()
	{
		List<Account> accountToBeInserted = TestDataFactory.getPatientAccountsList();
        insert accountToBeInserted;
        
		Id PatientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.PatientRecordtype).getRecordTypeId();
		for(Account a : accountToBeInserted){
			a.RecordTypeId = PatientRecordTypeId;
		}
		update accountToBeInserted;

		List<Order__c> lstOr = new List<Order__c>();
		lstOr.add(new Order__c(Patient__c = accountToBeInserted[0].Id, AtlasOrderId__c = '574121', CartOrderId__c = 'ORD-0057'));
		insert lstOr;
	}

    @isTest 
    static void itShouldValidateShipmentStatusToSAP(){
        //WHEN DPOkToShipToSAPStatus__c of an Order is updated as 'Retry'
		Test.setMock(HttpCalloutMock.class, new OrdersShipmentServiceMock());
		Test.enableChangeDataCapture();
		Test.startTest();
		OrdersSelector orderSelect = new OrdersSelector();
		List<Order__c> orders = orderSelect.SelectAll();
		List<Order__c> lstOrderToUpdate = new List<Order__c>();
		set<Id> sOrderId = new set<Id>();
        for (Order__c order : orders){
				sOrderId.add(order.id);
				Order__c ord = new Order__c();
				ord.Id = order.Id;
				ord.ConfirmedFPDeliveryDate__c =  Date.today();
				ord.AtlasOrderId__c = '574121';
				ord.CartOrderId__c = 'ORD-0057';
				ord.DPOkToShipToSAPStatus__c = 'Retry';
				lstOrderToUpdate.add(ord);
        }
		update lstOrderToUpdate;
		List<Order__c> listOrders = orderSelect.selectOrdersByOrderId(sOrderId);
        //THEN DPOkToShipToSAPStatus__c  is updated success
		System.assert(!listOrders.isempty());
		System.assertEquals(listOrders[0].DPOkToShipToSAPStatus__c, 'Retry');
		Test.stopTest();
		Test.getEventBus().deliver();
    }

}