objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/CryoCellDropOffDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>CryoCellDropOffDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Cell Drop-off Date and Time related to the order.</description>
    <label>Cryo Cell Drop-Off Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/CryoCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>CryoCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Cell Pickup Date and Time related to the order.</description>
    <label>Cryo Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/FinalDPDateinVineti__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDateinVineti__c</fullName>
    <description>Final DP Date that is coming from Vineti</description>
    <label>Final DP Date Updated in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/FinalDPDropOffDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDropOffDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Final DP Drop-off Date and Time of the related order.</description>
    <label>Final DP Drop-Off Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FinalDPPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FinalDPPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Final DP Pickup Date and Time related to the order.</description>
    <label>Final DP Pickup Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FreshCellDropOffDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FreshCellDropOffDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Fresh Cell Drop Off Date and Time related to the order.</description>
    <label>Fresh Cell Drop Off Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FreshCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FreshCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Fresh Cell Pickup Date and Time related to the order.</description>
    <label>Fresh Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/ManufacturingMilestoneDateTime__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingMilestoneDateTime__c</fullName>
    <description>Manufacturing date/time of the related order milestone.</description>
    <label>Manufacturing Milestone Date Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/ManufacturingStatus__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Manufacturing Status related to the order.</description>
    <label>Manufacturing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>True</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>QC/QA Complete</fullName>
            </value>
            <value>
                <fullName>Manufacturing Started</fullName>
            </value>
            <value>
                <fullName>Manufacturing Complete</fullName>
            </value>
            <value>
                <fullName>QR Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/OrderRescheduledinVineti__c.field-meta.xml
<CustomField>
    <fullName>OrderRescheduledinVineti__c</fullName>
    <description>Order Rescheduled Updated in Vineti System.</description>
    <label>Order Rescheduled in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Shipping status of the order.</description>
    <label>Shipping Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipping Fresh Cells</fullName>
            </value>
            <value>
                <fullName>Fresh Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Cryo-ed Cells</fullName>
            </value>
            <value>
                <fullName>Cryo-ed Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Drug Product</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/VinetiCOI__c.field-meta.xml
<CustomField>
    <fullName>VinetiCOI__c</fullName>
    <description>Field to track courier shipment details in the Vineti portal.</description>
    <externalId>true</externalId>
    <label>Vineti COI #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestones__c/OrderMilestones__c.object-meta.xml
<CustomObject>
    <label>Order Milestones</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderMilestones__c/fields/MilestoneDatetime__c.field-meta.xml
<CustomField>
    <fullName>MilestoneDatetime__c</fullName>
    <description>Date/time related to the Order Milestone.</description>
    <label>Milestone Datetime</label>
    <type>DateTime</type>
</CustomField>

objects/OrderMilestones__c/fields/MilestoneDetail__c.field-meta.xml
<CustomField>
    <fullName>MilestoneDetail__c</fullName>
    <description>Captures Detail of the Order Milestone</description>
    <label>Milestone Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderMilestones__c/fields/MilestoneSource__c.field-meta.xml
<CustomField>
    <fullName>MilestoneSource__c</fullName>
    <description>Captures the End System&apos;s Source on the Order Milestone</description>
    <label>Milestone Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestones__c/fields/MilestoneType__c.field-meta.xml
<CustomField>
    <fullName>MilestoneType__c</fullName>
    <description>Type of Order Milestone.</description>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>COI-COC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderMilestones__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order related to the milestone.</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Milestones</relationshipLabel>
    <relationshipName>OrderMilestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

classes/OrderMilestonesSelector.cls
public with sharing class OrderMilestonesSelector extends sflib_SObjectSelector
{
	string OrderIds = OrderMilestones__c.Order__c.getDescribe().getName();
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				OrderMilestones__c.MilestoneDatetime__c,
				OrderMilestones__c.MilestoneDetail__c,
				OrderMilestones__c.MilestoneType__c,
				OrderMilestones__c.Name,
				OrderMilestones__c.Order__c,
				OrderMilestones__c.MilestoneSource__c
		};
	}

	public SObjectType getSObjectType()
	{
		return OrderMilestones__c.SObjectType;
	}

    public List<OrderMilestones__c> selectById(Set<Id> orderMilestoneIds)
	{
		return (List<OrderMilestones__c>) Database.query(
				newQueryFactory()
            			.selectField('Order__r.CartOrderId__c')
						.setCondition(OrderMilestones__c.Id.getDescribe().getName()+' IN :orderMilestoneIds')
						.toSOQL());
    }

    public List<OrderMilestones__c> selectByOrderIds(Set<Id> orderIds)
    {
       return (List<OrderMilestones__c>) selectByFieldInIdSet(OrderMilestones__c.Order__c,orderIds);
    }

	public List<OrderMilestones__c> selectByOrderIdAndMilestoneNames(Set<Id> setOfOrderIds, List<String> milestoneNames)
	{
		return (List<OrderMilestones__c>) Database.query(
				newQueryFactory()
						.selectField('Order__r.ManufacturingStatus__c')
						.selectField('Order__r.ManufacturingMilestoneDateTime__c')
						.selectField('Order__r.ShippingStatus__c')
						.selectField('Order__r.FinalDPDropOffDateAndTime__c')
						.selectField('Order__r.FinalDPPickupDateAndTime__c')
						.selectField('Order__r.FreshCellDropOffDateAndTime__c')
						.selectField('Order__r.FreshCellPickupDateAndTime__c')
						.selectField('Order__r.CryoCellDropOffDateAndTime__c')
						.selectField('Order__r.CryoCellPickupDateAndTime__c')
						.selectField('Order__r.FinalDPDateinVineti__c')
						.selectField('Order__r.OrderRescheduledinVineti__c')
						.selectField('Order__r.VinetiCOI__c')
						.setCondition('Order__c IN: setOfOrderIds AND Name IN: milestoneNames')
						.toSOQL()
		);
	}

	public List<OrderMilestones__c> selectByOrderIdsAndOldMileStoneIds(Set<Id> orderIds,Set<Id> mileStoneIds)
	{
		return (List<OrderMilestones__c>) Database.query(
				newQueryFactory()
						.setCondition('Order__c IN :orderIds AND Id NOT IN :mileStoneIds')
						.toSOQL()
		);
	}

}