objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientEnrollmentSteps__mdt/PatientEnrollmentSteps__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch steps for patient enrollment dynamically</description>
    <label>Patient Enrollment Steps</label>
    <pluralLabel>Patient Enrollment Steps</pluralLabel>
</CustomObject>

objects/PatientEnrollmentSteps__mdt/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Patient</fullName>
                <default>true</default>
                <label>Patient</label>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientEnrollmentSteps__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Custom field to store order for each step in the progress indicator</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/PatientEnrollmentStepsSelector.cls
public with sharing class PatientEnrollmentStepsSelector extends fflib_SObjectSelector
{
	public static final String ORDER = 'Order';
	public static final String PATIENT = 'Patient';
	String module = PatientEnrollmentSteps__mdt.Module__c.getDescribe().getName();

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				PatientEnrollmentSteps__mdt.DeveloperName,
				PatientEnrollmentSteps__mdt.Id,
				PatientEnrollmentSteps__mdt.MasterLabel,
				PatientEnrollmentSteps__mdt.Module__c,
				PatientEnrollmentSteps__mdt.Order__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return PatientEnrollmentSteps__mdt.sObjectType;
	}

	public List<PatientEnrollmentSteps__mdt> selectPatients()
	{
		return (List<PatientEnrollmentSteps__mdt>) Database.query(
				newQueryFactory()
						.selectField('Module__c')
						.setCondition(module + '=:' +PATIENT)
						.setOrdering('Order__c', fflib_QueryFactory.SortOrder.ASCENDING)
						.toSOQL()
		);
	}

	public List<PatientEnrollmentSteps__mdt> selectSlotSchedulingSteps()
	{
		return (List<PatientEnrollmentSteps__mdt>) Database.query(
				newQueryFactory()
						.selectField('Module__c')
						.setCondition(module + '=:' +ORDER)
						.setOrdering('Order__c', fflib_QueryFactory.SortOrder.ASCENDING)
						.toSOQL()
		);
	}
}