objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo type related to the associated cryo site.</description>
    <label>Cryo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
                <isActive>false</isActive>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Raritan</fullName>
                <isActive>false</isActive>
                <label>Raritan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderMilestones__c/OrderMilestones__c.object-meta.xml
<CustomObject>
    <label>Order Milestones</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderMilestones__c/fields/MilestoneDetail__c.field-meta.xml
<CustomField>
    <fullName>MilestoneDetail__c</fullName>
    <description>Captures Detail of the Order Milestone</description>
    <label>Milestone Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderMilestones__c/fields/MilestoneSource__c.field-meta.xml
<CustomField>
    <fullName>MilestoneSource__c</fullName>
    <description>Captures the End System&apos;s Source on the Order Milestone</description>
    <label>Milestone Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestones__c/fields/MilestoneType__c.field-meta.xml
<CustomField>
    <fullName>MilestoneType__c</fullName>
    <description>Type of Order Milestone.</description>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>COI-COC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderMilestones__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order related to the milestone.</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Milestones</relationshipLabel>
    <relationshipName>OrderMilestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/OrderMilestonesDetails__mdt.object-meta.xml
<CustomObject>
    <label>Order Milestones Details</label>
    <pluralLabel>Order Milestones Details</pluralLabel>
</CustomObject>

objects/OrderMilestonesDetails__mdt/fields/eventName__c.field-meta.xml
<CustomField>
    <fullName>eventName__c</fullName>
    <description>Name of the Order Milestone for which the rule applies</description>
    <label>event Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/SourceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldAPIName__c</fullName>
    <description>API Name of the source field on the Order for the update related to the rule</description>
    <label>Source Field APIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/TargetFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldAPIName__c</fullName>
    <description>API Name of the target field on the Order for the update related to the rule</description>
    <label>TargetFieldAPIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/OrderMilestonesUpdateRules__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to capture business rules for mapping on order manufacturing statuses.</description>
    <label>Order Milestones Update Rules</label>
    <pluralLabel>Order Milestones Update Rules</pluralLabel>
</CustomObject>

objects/OrderMilestonesUpdateRules__mdt/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <description>Cryo type of the Order Milestone for which the rule applies</description>
    <label>CryoType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneName__c.field-meta.xml
<CustomField>
    <fullName>MilestoneName__c</fullName>
    <description>Name of the Order Milestone for which the rule applies</description>
    <label>Milestone Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneSource__c.field-meta.xml
<CustomField>
    <fullName>MilestoneSource__c</fullName>
    <description>This field describes the Milestone Source for the Order Milestone</description>
    <label>Milestone Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneType__c.field-meta.xml
<CustomField>
    <fullName>MilestoneType__c</fullName>
    <description>Type of the Order Milestone for which the rule applies</description>
    <label>Milestone Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/OrderMilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderMilestoneStatus__c</fullName>
    <description>Manufacturing status of the Order Milestone.</description>
    <label>Order Milestone Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/SourceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldAPIName__c</fullName>
    <description>API Name of the source field on the Order for the update related to the rule</description>
    <label>Source Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/TargetFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldAPIName__c</fullName>
    <description>API Name of the target field on the Order for the update related to the rule</description>
    <label>Target Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/TargetStatusAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetStatusAPIName__c</fullName>
    <description>API Name of the target Status fields on the Order for the update related to the rule.</description>
    <label>Target Status API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/OrderMilestonesService.cls
public with sharing class OrderMilestonesService
{
	private static String COINumber = 'COINumber';
	private static String COMMA = ',';
	private static String DIN = 'DIN';
    
	public void callAnaplanToUpdateManuFactutingMilestones(OrderMilestones orderMilestones)
	{
		Set<Id> ordersMileStoneIds = orderMilestones.getRecordIds();

		if (ordersMileStoneIds.isEmpty() || new Utility().getIfExecutionContextInAsync()) return ;

		callAnaplanToUpdateManuFactutingMilestones(ordersMileStoneIds);
	}

	@Future(Callout = true)
	public static void callAnaplanToUpdateManuFactutingMilestones(Set<Id> ordersMileStoneIds)
	{
		if (ordersMileStoneIds == null || ordersMileStoneIds.isEmpty()) return ;

		ManufacturingMilestonesUpdateService manufacturingMilestonesUpdateService = (ManufacturingMilestonesUpdateService) Application.Service
				.newInstance(ManufacturingMilestonesUpdateService.class);
		manufacturingMilestonesUpdateService.callAnaplanToUpdateManufacturingMilestones(ordersMilestoneIds);
	}

	public void checkMilestoneDetailsOnOrders(OrderMilestones milestones){

		List<OrderMilestones__c> ordMilestones = new List<OrderMilestones__c>();
		List<OrderMilestones__c> ordMilestonesListForShipment = new List<OrderMilestones__c>();
		ordMilestones = ((OrderMileStonesSelector) Application.Selector.newInstance(OrderMilestones__c.SObjectType))
				.selectByOrderIdsAndOldMileStoneIds(milestones.getOrderIds(),milestones.getRecordIds());
		Map<String,DateTime> orderMileStoneDateTimeMap = new Map<String,DateTime>();
		orderMileStoneDateTimeMap = milestones.getLatestOrderMileStoneRecordsForOrder(ordMilestones);
		List<OrderMilestones__c> ordMilestonesTobeUpdated = new List<OrderMilestones__c>();
		ordMilestonesTobeUpdated = milestones.getOrderMileStoneRecordsTobeUpdated(orderMileStoneDateTimeMap);

		if (!ordMilestonesTobeUpdated.isEmpty())
		{
			updateMilestoneDetailsOnOrders(ordMilestonesTobeUpdated);
			for (OrderMilestones__c milestone : ordMilestonesTobeUpdated)
			{
				if (milestone.MilestoneDetail__c <> NULL)
				{
					ordMilestonesListForShipment.add(milestone);
				}
			}
			if (!ordMilestonesListForShipment.isEmpty())
			{
				updateOrderShipmentMilestoneDetailsOnOrders(ordMilestonesListForShipment);
			}
		}
	}

	public void updateMilestoneDetailsOnOrders(List<OrderMilestones__c> orderMilestonesList)
	{
		List<OrderMilestonesUpdateRules__mdt> metadataRecordsList = new OrderMilestonesUpdateRulesSelector().selectAll();
		if (metadataRecordsList.isEmpty()) return;
		Map<String, OrderMilestonesUpdateRules__mdt> cryoTypeMetadataRecordsMap = new Map<String, OrderMilestonesUpdateRules__mdt>();
		Map<String, OrderMilestonesUpdateRules__mdt> metadataRecordsMap = new Map<String, OrderMilestonesUpdateRules__mdt>();
		for (OrderMilestonesUpdateRules__mdt record : metadataRecordsList)
		{
			metadataRecordsMap.put(record.MilestoneName__c, record);
			if (record.CryoType__c != NULL)
			{
				String keyValue = record.CryoType__c + COMMA + record.MilestoneName__c;
				cryoTypeMetadataRecordsMap.put(keyValue, record);
			}
		}

		Set<Id> orderIdsSet = ((OrderMilestones) Application.Domain.newInstance(orderMilestonesList)).getOrderIds();
		List<Order__c> relatedOrdersList = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType))
				.selectOrdersByOrderId(orderIdsSet);
		Map<Id, Order__c> relatedOrderIdWithOrderMap = new Map<Id, Order__c>(relatedOrdersList);
		Boolean isRecSatisfying = false;
		Order__c relatedOrderRec;
		OrderMilestonesUpdateRules__mdt orderManufacturingStatusUpdateRuleRecord;
		List<Order__c> orderRecordsToBeUpdated = new List<Order__c>();
		for (OrderMilestones__c orderMilestone : orderMilestonesList)
		{
			relatedOrderRec = new Order__c();
			orderManufacturingStatusUpdateRuleRecord = new OrderMilestonesUpdateRules__mdt();
			isRecSatisfying = (!metadataRecordsMap.isEmpty()
					&& metadataRecordsMap.keySet().contains(orderMilestone.Name))
					&& ((metadataRecordsMap.get(orderMilestone.Name).MilestoneType__c).equals(orderMilestone.MilestoneType__c))
					&& ((metadataRecordsMap.get(orderMilestone.Name).MilestoneSource__c).equals(orderMilestone.MilestoneSource__c))
					&& !relatedOrderIdWithOrderMap.isEmpty()
					&& relatedOrderIdWithOrderMap.containsKey(orderMilestone.Order__c);

			if (isRecSatisfying)
			{
				relatedOrderRec = relatedOrderIdWithOrderMap.get(orderMilestone.Order__c);
				String mapKeyValue = relatedOrderRec.CryoType__c + COMMA + orderMileStone.Name;
				if (cryoTypeMetadataRecordsMap.containsKey(mapKeyValue))
				{
					orderManufacturingStatusUpdateRuleRecord = cryoTypeMetadataRecordsMap.get(mapKeyValue);
				}
				else
				{
					orderManufacturingStatusUpdateRuleRecord = metadataRecordsMap.get(orderMilestone.Name);
				}
				
				if (String.isNotBlank(orderManufacturingStatusUpdateRuleRecord.OrderMilestoneStatus__c))
				{
					relatedOrderRec.put(orderManufacturingStatusUpdateRuleRecord.TargetStatusAPIName__c, orderManufacturingStatusUpdateRuleRecord.OrderMilestoneStatus__c);
				}
				relatedOrderRec.put(orderManufacturingStatusUpdateRuleRecord.TargetFieldAPIName__c,
						orderMilestone.get(orderManufacturingStatusUpdateRuleRecord.SourceFieldAPIName__c));

				orderRecordsToBeUpdated.add(relatedOrderIdWithOrderMap.get(orderMilestone.Order__c));
			}
		}
		if (!orderRecordsToBeUpdated.isEmpty())
		{
			fflib_ISObjectUnitOfWork orderUnitOfWork = Application.UnitOfWork.newInstance();
			orderUnitOfWork.registerDirty(orderRecordsToBeUpdated);
			orderUnitOfWork.commitWork();
		}
	}

	public void updateOrderShipmentMilestoneDetailsOnOrders(List<OrderMilestones__c> milestonesList)
	{
		Set<String> shipmentMilestonesSet = new Set<String>();
		List<OrderMilestonesDetails__mdt> metadataRecordsList = new OrderMilestonesDetailsSelector().selectAll();
		if (metadataRecordsList.isEmpty()) return;
		Map<String, List<OrderMilestonesDetails__mdt>> metadataRecordsMap = new Map<String, List<OrderMilestonesDetails__mdt>>();
		for (OrderMilestonesDetails__mdt record : metadataRecordsList)
		{
			shipmentMilestonesSet.add(record.eventName__c);
			if (!metadataRecordsMap.containsKey(record.eventName__c))
			{
				metadataRecordsMap.put(record.eventName__c, new List<OrderMilestonesDetails__mdt> {record});
			}
			else
			{
				metadataRecordsMap.get(record.eventName__c).add(record);
			}
		}
		List<OrderMilestones__c> finalMileStonesList = new List<OrderMilestones__c>();
		for (OrderMilestones__c ordMileStone : milestonesList)
		{
			if (shipmentMilestonesSet.contains(ordMilestone.Name))
			{
				finalMileStonesList.add(ordMilestone);
			}
		}
		List<Order__c> ordersTobeUpdated = new List<Order__c>();
		if (!finalMileStonesList.isEmpty())
		{
			for (OrderMilestones__c ord : finalMileStonesList)
			{
				Order__c orderRec = new Order__c();
				orderRec.Id = ord.Order__c;
				eventDetails eventWrapper = eventDetails.parse(ord.MilestoneDetail__c);
				for (OrderMilestonesDetails__mdt metadataRec : metadataRecordsMap.get(ord.Name))
				{
					if (!String.isBlank(eventWrapper.DIN)
							&& metadataRec.SourceFieldAPIName__c.equals(DIN))
					{
						orderRec.put(metadataRec.TargetFieldAPIName__c, eventWrapper.DIN);
					}
					if (!String.isBlank(eventWrapper.COINumber)
							&& metadataRec.SourceFieldAPIName__c.equals(COINumber))
					{
						orderRec.put(metadataRec.TargetFieldAPIName__c, eventWrapper.COINumber);
					}
				}
				ordersTobeUpdated.add(orderRec);
			}
		}

		if (!ordersTobeUpdated.isEmpty())
		{
			fflib_ISObjectUnitOfWork orderUnitOfWork = Application.UnitOfWork.newInstance();
			orderUnitOfWork.registerDirty(ordersTobeUpdated);
			orderUnitOfWork.commitWork();
		}
	}
	public class eventDetails
	{
		String DIN { get; set; }
		String COINumber { get; set; }
		public eventDetails(JSONParser parser)
		{
			while (parser.nextToken() != System.JSONToken.END_OBJECT)
			{
				if (parser.getCurrentToken() == System.JSONToken.FIELD_NAME)
				{
					String text = parser.getText();
					if (parser.nextToken() != System.JSONToken.VALUE_NULL)
					{
						switch on text
						{
							when 'DIN'
							{
								DIN = parser.getText();
							}
							when 'COINumber'
							{
								COINumber = parser.getText();
							}
						}
					}
				}
			}
		}
	}
	public static eventDetails parse(String json)
	{
		System.JSONParser parser = System.JSON.createParser(json);
		return new eventDetails(parser);
	}
}