objects/NotificationEngine__mdt/NotificationEngine__mdt.object-meta.xml
<CustomObject>
    <label>Notification Engine</label>
    <pluralLabel>Notification Engine</pluralLabel>
</CustomObject>

objects/NotificationEngine__mdt/fields/FinalStatus__c.field-meta.xml
<CustomField>
    <fullName>FinalStatus__c</fullName>
    <label>Final Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/InitialStatus__c.field-meta.xml
<CustomField>
    <fullName>InitialStatus__c</fullName>
    <label>Initial Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/NotificationBody__c.field-meta.xml
<CustomField>
    <fullName>NotificationBody__c</fullName>
    <label>Notification Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/NotificationSubject__c.field-meta.xml
<CustomField>
    <fullName>NotificationSubject__c</fullName>
    <label>Notifcation Subject</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/ObjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPIName__c</fullName>
    <label>Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/SourceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldAPIName__c</fullName>
    <label>Source Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/NotificationEngineSelector.cls
public with sharing class NotificationEngineSelector extends fflib_SObjectSelector
{

	public static final Boolean ACTIVESTATUS = TRUE;

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				NotificationEngine__mdt.Active__c,
				NotificationEngine__mdt.FinalStatus__c,
				NotificationEngine__mdt.InitialStatus__c,
				NotificationEngine__mdt.NotificationBody__c,
				NotificationEngine__mdt.NotificationSubject__c,
				NotificationEngine__mdt.ObjectAPIName__c,
				NotificationEngine__mdt.SourceFieldAPIName__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return NotificationEngine__mdt.sObjectType;
	}

	public List<NotificationEngine__mdt> selectAll()
	{
		return (List<NotificationEngine__mdt>) Database.query(
				newQueryFactory()
						.toSOQL()
		);
	}

	public List<NotificationEngine__mdt> selectNotificationAlert(String objectAPIName, List<String> sourceFieldAPIName, String initialStatus, String finalStatus)
	{
		String objectAPI = NotificationEngine__mdt.ObjectAPIName__c.getDescribe().getName();
		String sourceFieldAPI = NotificationEngine__mdt.SourceFieldAPIName__c.getDescribe().getName();
		String activeStatus = NotificationEngine__mdt.Active__c.getDescribe().getName();
		String initialManufacturingStatus = NotificationEngine__mdt.InitialStatus__c.getDescribe().getName();
		String finalManufacturingStatus = NotificationEngine__mdt.FinalStatus__c.getDescribe().getName();
		return (List<NotificationEngine__mdt>) Database.query(
				newQueryFactory()
						.setCondition(objectAPI + ' =:objectAPIName AND ' + sourceFieldAPI + ' IN : sourceFieldAPIName AND ' + activeStatus + ' = TRUE  AND ' + initialManufacturingStatus + ' =:initialStatus AND ' + finalManufacturingStatus + ' =:finalStatus')
						.toSOQL()
		);
	}
}