objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientServicesEnrollee__c/fields/CarePlan__c.field-meta.xml
<CustomField>
    <fullName>CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care Plan the patient is enrolled into</description>
    <label>Care Plan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CarePlan</value>
        </filterItems>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CareGap</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Patient Services Enrollees</relationshipLabel>
    <relationshipName>Patient_Services_Enrollees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <description>Patient record of the patient requesting Patient Services</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Services Enrollees</relationshipLabel>
    <relationshipName>Patient_Services_Enrollees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/PatientServicesStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServicesStatus__c</fullName>
    <description>Status of the Patient Services Record</description>
    <defaultValue>&apos;New Patient Services request&apos;</defaultValue>
    <label>Patient Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Patient Services Request</fullName>
                <default>true</default>
                <label>New Patient Services Request</label>
            </value>
            <value>
                <fullName>Request to Enroll Confirmed</fullName>
            </value>
            <value>
                <fullName>Patient Enrollment Form Received</fullName>
            </value>
            <value>
                <fullName>Missing Information in Form</fullName>
            </value>
            <value>
                <fullName>Processing Eligibility</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Enrolled in Service</fullName>
            </value>
            <value>
                <fullName>Opted out of Patient Services</fullName>
            </value>
            <value>
                <fullName>Request for Information Only</fullName>
            </value>
            <value>
                <fullName>Patient Services Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientServicesEnrolleesSelector.cls
public with sharing class PatientServicesEnrolleesSelector extends sflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				PatientServicesEnrollee__c.CarePlan__c,
				PatientServicesEnrollee__c.Name,
				PatientServicesEnrollee__c.Patient__c,
				PatientServicesEnrollee__c.PatientServicesStatus__c
		};
	}

	public SObjectType getSObjectType()
	{
		return PatientServicesEnrollee__c.SObjectType;
	}
    
	public List<PatientServicesEnrollee__c> selectByCarePlanId(Set<Id> carePlanIds)
	{
		return (List<PatientServicesEnrollee__c>) selectByFieldInIdSet(PatientServicesEnrollee__c.CarePlan__c, carePlanIds);
	}

	public List<PatientServicesEnrollee__c> selectById(Set<Id> pseIds)
	{
		return ((List<PatientServicesEnrollee__c>) Database.query(
				newQueryFactory()
						.selectField('Patient__c')
						.setCondition( 'Id IN :pseIds')
						.toSOQL()));
	}

	public List<PatientServicesEnrollee__c> elevatedSelectByAccountId(Set<Id> accountIds){
		ElevateContext elevateContext = new ElevateContext(this);
		return elevateContext.elevatedSelectByAccountId(accountIds);
	}
    
    public Database.QueryLocator getQLOfPSESCreatedEditedInLastNDays(Integer lastNDays)
	{
		return Database.getQueryLocator(
						newQueryFactory()
						.setCondition(String.format('{0} = LAST_N_DAYS:{1}',
						new List<String>{
								Account.LastModifiedDate.getDescribe().getName(),
								String.valueOf(lastNDays)}))
						.toSOQL());
	}

	private without sharing class ElevateContext extends sflib_SObjectSelector
	{
		PatientServicesEnrolleesSelector selector;

		public ElevateContext(PatientServicesEnrolleesSelector selector)
		{
			super(true, false, false, true);
			this.selector = selector;
		}

		public List<Schema.SObjectField> getSObjectFieldList()
		{
			return selector.getSObjectFieldList();
		}

		public Schema.SObjectType getSObjectType()
		{
			return selector.getSObjectType();
		}

		public List<PatientServicesEnrollee__c> elevatedSelectByAccountId(Set<Id> accountIds){
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('Patient__c');
			queryFactory.setCondition('Patient__c IN :accountIds');
			return (List<PatientServicesEnrollee__c>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

	}
	
	public List<PatientServicesEnrollee__c> selectAll()
	{
		return ((List<PatientServicesEnrollee__c>) Database.query(
				newQueryFactory().toSOQL()));
	}
}