objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientServicesEnrollee__c/fields/CarePlan__c.field-meta.xml
<CustomField>
    <fullName>CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care Plan the patient is enrolled into</description>
    <label>Care Plan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CarePlan</value>
        </filterItems>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CareGap</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Patient Services Enrollees</relationshipLabel>
    <relationshipName>Patient_Services_Enrollees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/PatientServicesStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServicesStatus__c</fullName>
    <description>Status of the Patient Services Record</description>
    <defaultValue>&apos;New Patient Services request&apos;</defaultValue>
    <label>Patient Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Patient Services Request</fullName>
                <default>true</default>
                <label>New Patient Services Request</label>
            </value>
            <value>
                <fullName>Request to Enroll Confirmed</fullName>
            </value>
            <value>
                <fullName>Patient Enrollment Form Received</fullName>
            </value>
            <value>
                <fullName>Missing Information in Form</fullName>
            </value>
            <value>
                <fullName>Processing Eligibility</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Enrolled in Service</fullName>
            </value>
            <value>
                <fullName>Opted out of Patient Services</fullName>
            </value>
            <value>
                <fullName>Request for Information Only</fullName>
            </value>
            <value>
                <fullName>Patient Services Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientServicesEnrollees.cls
public with sharing class PatientServicesEnrollees extends sflib_SObjectDomain
{
	static final String INELIGIBLE = 'Ineligible';
	static final String ELIGIBLE = 'Eligible';

	public Type getType()
	{
		return PatientServicesEnrollees.Class;
	}

	public PatientServicesEnrollees(List<PatientServicesEnrollee__c> records)
	{
		super(records, PatientServicesEnrollee__c.SObjectType);
	}

	private PatientServicesEnrolleesService Service
    {
        get
        {
            if (null == Service)
            {
                Service = (PatientServicesEnrolleesService) Application.Service.newInstance(PatientServicesEnrolleesService.class);
            }
            return Service;
        }
        set;
    }

	public override void onAfterInsert()
	{
		createTasksForPatientServiceEnrollees();
		grantAccessToPublicGroups(Records);
	}

	public override void onBeforeUpdate(Map<Id, Sobject> existingRecords)
	{
		onChangedFieldsCreateRelevantTasks();
	}

    public override void onAfterUpdate(Map<Id, Sobject> existingRecords)
    {
		sendPatientServicesEnrolleesLetters();
	    onPatientServicesEligibility(existingRecords);
	    onChangedFieldsCarePlan();
    }

	public void onChangedFieldsCarePlan()
	{
		List<PatientServicesEnrollee__c> cpChangedRecords = (List<PatientServicesEnrollee__c>) getChangedRecords(new Set<Schema.SObjectField>{
															PatientServicesEnrollee__c.CarePlan__c});
		if (cpChangedRecords.isEmpty())
		{
			return;
		}
		grantAccessToPublicGroups(cpChangedRecords);
	}
	
	public void onPatientServicesEligibility(Map<Id, SObject> existingRecords)
	{
		Set<Schema.SObjectField> sObjectField = new Set<Schema.SObjectField> {PatientServicesEnrollee__c.PatientServicesStatus__c};
		List<SObject> changedRecords = getChangedRecords(sObjectField);
		if (changedRecords.isEmpty()) return ;
		fetchNotificationAlertDetails(changedRecords, existingRecords.values(), sObjectField);
	}

	public void fetchNotificationAlertDetails(List<SObject> changedRecords, List<SObject> existingRecords, Set<Schema.SObjectField> sObjectField)
	{
		Service.fetchNotificationAlertDetails((List<PatientServicesEnrollee__c>)
				new sflib_SObjects(changedRecords).getSObjects(),
				(List<PatientServicesEnrollee__c>) new sflib_SObjects(existingRecords).getSObjects(), sObjectField);
	}

	public void onChangedFieldsCreateRelevantTasks()
	{
		List<SObject> changedRecords = getChangedRecords(fieldsToTriggerTaskCreation());
		if (changedRecords.isEmpty()) return;
		new PatientServicesEnrollees(changedRecords).createTasksForPatientServiceEnrollees();
	}

	Set<Schema.SObjectField> fieldsToTriggerTaskCreation()
	{
		return new Set<Schema.SObjectField> {PatientServicesEnrollee__c.PatientServicesStatus__c};
	}

	public void createTasksForPatientServiceEnrollees()
	{
		PatientServicesEnrolleesService service = (PatientServicesEnrolleesService) Application.Service
				.newInstance(PatientServicesEnrolleesService.class);
		service.createTasksForPatientServiceEnrollees(selectPSESWithPatientServiceStatus());
	}

	public PatientServicesEnrollees selectPSESWithPatientServiceStatus()
	{
		List<PatientServicesEnrollee__c> psesWithPSStatus = (List<PatientServicesEnrollee__c>) new sflib_SObjects(Records)
				.filter(new sflib_Criteria()
						.notEqualTo(PatientServicesEnrollee__c.PatientServicesStatus__c, null))
				.getSobjects();
		return new PatientServicesEnrollees(psesWithPSStatus);
	}

	public Class Constructor implements fflib_SObjectDomain.IConstructable2
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new PatientServicesEnrollees(sObjectList);
		}
		public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
		{
			return new PatientServicesEnrollees(sObjectList);
		}
	}

	public void sendPatientServicesEnrolleesLetters()
	{
		List<PatientServicesEnrollee__c> pseChangedRecords = getChangedRecords(new Set<Schema.SObjectField>{
																PatientServicesEnrollee__c.PatientServicesStatus__c});
		
		Set<Id> pseEligibles = getPatientServicesEnrolleesByStatus(pseChangedRecords, ELIGIBLE);
		Set<Id> pseIneligibles = getPatientServicesEnrolleesByStatus(pseChangedRecords, INELIGIBLE);

		Service.sendPatientServicesLetters(new Map<String,Set<Id>>{
			Label.PSETemplateForTheCARTCoordinatorDevName => pseEligibles,
			Label.PSETemplateForThePatientDevName => pseEligibles,
			Label.PSITemplateForTheCARTCoordinatorDevName => pseIneligibles,
			Label.PSITemplateForThePatientDevName => pseIneligibles
		});
	}

	public Set<Id> getPatientServicesEnrolleesByStatus(List<PatientServicesEnrollee__c> pseList, String status)
	{
		Set<Id> pseIds = new Set<Id>();

		for(PatientServicesEnrollee__c pse : pseList)
		{
			if(pse.PatientServicesStatus__c.equalsIgnoreCase(status))
			{
				pseIds.add(PSE.Id);
			}
		}

		return pseIds;
	}

	public Map<Id, PatientServicesEnrollee__c> getPatientServicesByCareplanId()
	{
		Map<Id, PatientServicesEnrollee__c> patientServicesEnrolleeByCarePlanIdMap = new Map<Id, PatientServicesEnrollee__c>();
		for (PatientServicesEnrollee__c record : (List<PatientServicesEnrollee__c>) records)
		{
			if (record.CarePlan__c != null)
			{
				patientServicesEnrolleeByCarePlanIdMap.put(record.CarePlan__c, record);
			}
		}
		return patientServicesEnrolleeByCarePlanIdMap;
	}
	
	public void grantAccessToPublicGroups(List<PatientServicesEnrollee__c> pseList)
	{
		Service.grantAccessToPublicGroups(new PatientServicesEnrollees(pseList));
	}
    
}