objects/OrderMilestonesDetails__mdt/OrderMilestonesDetails__mdt.object-meta.xml
<CustomObject>
    <label>Order Milestones Details</label>
    <pluralLabel>Order Milestones Details</pluralLabel>
</CustomObject>

objects/OrderMilestonesDetails__mdt/fields/eventName__c.field-meta.xml
<CustomField>
    <fullName>eventName__c</fullName>
    <description>Name of the Order Milestone for which the rule applies</description>
    <label>event Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/eventSource__c.field-meta.xml
<CustomField>
    <fullName>eventSource__c</fullName>
    <description>This field describes the Milestone Source for the Order Milestone</description>
    <label>eventSource</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/eventType__c.field-meta.xml
<CustomField>
    <fullName>eventType__c</fullName>
    <description>Type of the Order Milestone for which the rule applies</description>
    <label>Event Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/SourceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldAPIName__c</fullName>
    <description>API Name of the source field on the Order for the update related to the rule</description>
    <label>Source Field APIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/fields/TargetFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldAPIName__c</fullName>
    <description>API Name of the target field on the Order for the update related to the rule</description>
    <label>TargetFieldAPIName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/OrderMilestonesDetailsSelector.cls
public with sharing class OrderMilestonesDetailsSelector extends fflib_SObjectSelector
{
    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				OrderMilestonesDetails__mdt.eventName__c,
				OrderMilestonesDetails__mdt.eventSource__c,
				OrderMilestonesDetails__mdt.eventType__c,
				OrderMilestonesDetails__mdt.SourceFieldAPIName__c,
				OrderMilestonesDetails__mdt.TargetFieldAPIName__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return OrderMilestonesDetails__mdt.sObjectType;
	}

	public List<OrderMilestonesDetails__mdt> selectAll()
	{
		return (List<OrderMilestonesDetails__mdt>) Database.query(
				newQueryFactory()
						.toSOQL()
		);
	}
}