objects/CountryToRegionMapping__mdt/CountryToRegionMapping__mdt.object-meta.xml
<CustomObject>
    <label>Country To Region Mapping</label>
    <pluralLabel>Country To Region Mapping</pluralLabel>
</CustomObject>

objects/CountryToRegionMapping__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Stores the Country for the mapping</description>
    <label>Country</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/CountryToRegionMapping__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Stores the Region corresponding to the Country for the mapping</description>
    <label>Region</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

classes/CountryToRegionMappingSelector.cls
public class CountryToRegionMappingSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				CountryToRegionMapping__mdt.Country__c,
				CountryToRegionMapping__mdt.DeveloperName,
				CountryToRegionMapping__mdt.Region__c,
				CountryToRegionMapping__mdt.MasterLabel
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return CountryToRegionMapping__mdt.sObjectType;
	}

	public List<CountryToRegionMapping__mdt> selectAll(String Country)
	{
		return (List<CountryToRegionMapping__mdt>) Database.query(
				newQueryFactory()
						.setCondition('MasterLabel =:Country')
						.toSOQL()
		);
	}
}