objects/TreatmentJourneySteps__mdt/TreatmentJourneySteps__mdt.object-meta.xml
<CustomObject>
    <label>Treatment Journey Steps</label>
    <pluralLabel>Treatment Journey Steps</pluralLabel>
</CustomObject>

objects/TreatmentJourneySteps__mdt/fields/ApheresisCompleted__c.field-meta.xml
<CustomField>
    <fullName>ApheresisCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the Apheresis Section progress as Completed or Active in Treatment Journey Screen</description>
    <label>Apheresis Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ApheresisPickUpSectionStatus__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpSectionStatus__c</fullName>
    <description>To populate the corresponding Apheresis Section Status based on Order, Care Plan, PO and Slot statuses in Treatment Journey Screen</description>
    <label>Apheresis Pick-Up Section Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/CarePlanStatus__c.field-meta.xml
<CustomField>
    <fullName>CarePlanStatus__c</fullName>
    <description>To store Care Plan Status as per matrix for comparison with the Care Plan Status of the Patient in Treatment Journey Screen</description>
    <label>Care Plan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/DeliveryCompleted__c.field-meta.xml
<CustomField>
    <fullName>DeliveryCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delivery Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>DeliveryStatus__c</fullName>
    <label>Delivery Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/InfusionCompleted__c.field-meta.xml
<CustomField>
    <fullName>InfusionCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Infusion Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/InfusionStatus__c.field-meta.xml
<CustomField>
    <fullName>InfusionStatus__c</fullName>
    <label>Infusion Status</label>
    <length>127</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ManufacturingCompleted__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the Manufacturing Section progress as Completed or Active in Treatment Journey Screen</description>
    <label>Manufacturing Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ManufacturingStatus__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingStatus__c</fullName>
    <description>To store Manufacturing Status as per matrix.</description>
    <label>Manufacturing Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>To store Order Status as per matrix for comparison with the Order Status of the Patient in Treatment Journey Screen</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <description>To store PO Status as per matrix for comparison with the PO Status of the Patients Order in Treatment Journey Screen</description>
    <label>PO Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/SectionName__c.field-meta.xml
<CustomField>
    <fullName>SectionName__c</fullName>
    <description>To store corresponding Section Name in Treatment Journey Screen</description>
    <label>Section Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ShippingCompleted__c.field-meta.xml
<CustomField>
    <fullName>ShippingCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the Shipping Section progress as Completed or Active in Treatment Journey Screen</description>
    <label>Shipping Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <description>To populate the corresponding Shipping Section Status based on Order, Care Plan, PO and Slot statuses in Treatment Journey Screen</description>
    <label>Shipping Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <description>To store Slot Status as per matrix for comparison with the Slot Status of the Patients Order in Treatment Journey Screen</description>
    <label>Slot Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/TreatmentJourneyStepsSelector.cls
public with sharing class TreatmentJourneyStepsSelector extends fflib_SObjectSelector
{
	public static final String APHERESISPICKUP = 'Apheresis Pick-Up';
	public static final String MANUFACTURING ='Manufacturing';
	public static final String SHIPPING = 'Shipping';
	public static final String DELIVERY = 'Delivery';

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				TreatmentJourneySteps__mdt.ApheresisCompleted__c,
				TreatmentJourneySteps__mdt.ApheresisPickUpSectionStatus__c,
				TreatmentJourneySteps__mdt.DeveloperName,
				TreatmentJourneySteps__mdt.DeliveryCompleted__c,
				TreatmentJourneySteps__mdt.DeliveryStatus__c,
				TreatmentJourneySteps__mdt.Id,
				TreatmentJourneySteps__mdt.InfusionCompleted__c,
				TreatmentJourneySteps__mdt.InfusionStatus__c,
				TreatmentJourneySteps__mdt.ManufacturingCompleted__c,
				TreatmentJourneySteps__mdt.ManufacturingStatus__c,
				TreatmentJourneySteps__mdt.MasterLabel,
				TreatmentJourneySteps__mdt.ShippingCompleted__c,
				TreatmentJourneySteps__mdt.ShippingStatus__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return TreatmentJourneySteps__mdt.sObjectType;
	}

	public List<TreatmentJourneySteps__mdt> selectApheresisStepsByStatuses(String carePlanStatus, String orderStatus, String slotStatus, String poStatus)
	{
		String section = TreatmentJourneySteps__mdt.SectionName__c.getDescribe().getName();
		String careplan = TreatmentJourneySteps__mdt.CarePlanStatus__c.getDescribe().getName();
		String order = TreatmentJourneySteps__mdt.OrderStatus__c.getDescribe().getName();
		String slot = TreatmentJourneySteps__mdt.SlotStatus__c.getDescribe().getName();
		String po = TreatmentJourneySteps__mdt.POStatus__c.getDescribe().getName();
		return (List<TreatmentJourneySteps__mdt>) Database.query(
				newQueryFactory()
						.setCondition(careplan + ' =:carePlanStatus AND ' + order + ' =:orderStatus AND ' + slot + ' =:slotStatus AND ' + po + ' =:poStatus AND ' + section + ' =:APHERESISPICKUP')
						.toSOQL()
		);
	}

	public List<TreatmentJourneySteps__mdt> selectShippingStepsByStatuses(String carePlanStatus, String orderStatus, String slotStatus, String poStatus,  String shippingStatus)
	{
		String section = TreatmentJourneySteps__mdt.SectionName__c.getDescribe().getName();
		String careplan = TreatmentJourneySteps__mdt.CarePlanStatus__c.getDescribe().getName();
		String order = TreatmentJourneySteps__mdt.OrderStatus__c.getDescribe().getName();
		String slot = TreatmentJourneySteps__mdt.SlotStatus__c.getDescribe().getName();
		String po = TreatmentJourneySteps__mdt.POStatus__c.getDescribe().getName();
		String ship = TreatmentJourneySteps__mdt.ShippingStatus__c.getDescribe().getName();
		return (List<TreatmentJourneySteps__mdt>) Database.query(
				newQueryFactory()
						.setCondition(careplan + ' =:carePlanStatus AND ' + order + ' =:orderStatus AND ' + slot + ' =:slotStatus AND ' + po + ' =:poStatus AND ' + ship + ' =:shippingStatus AND ' + section + ' =:SHIPPING')
						.toSOQL()
		);
	}

	public List<TreatmentJourneySteps__mdt> selectManufacturingStepsByStatuses(String carePlanStatus, String orderStatus, String slotStatus, String poStatus,  String manufacturingStatus)
	{
		String section = TreatmentJourneySteps__mdt.SectionName__c.getDescribe().getName();
		String careplan = TreatmentJourneySteps__mdt.CarePlanStatus__c.getDescribe().getName();
		String order = TreatmentJourneySteps__mdt.OrderStatus__c.getDescribe().getName();
		String slot = TreatmentJourneySteps__mdt.SlotStatus__c.getDescribe().getName();
		String po = TreatmentJourneySteps__mdt.POStatus__c.getDescribe().getName();
		String manufacturingStatusLabel = TreatmentJourneySteps__mdt.ManufacturingStatus__c.getDescribe().getName();
		return (List<TreatmentJourneySteps__mdt>) Database.query(
				newQueryFactory()
						.setCondition(careplan + ' =:carePlanStatus AND ' + order + ' =:orderStatus AND ' + slot + ' =:slotStatus AND ' + po + ' =:poStatus AND ' + manufacturingStatusLabel + ' =:manufacturingStatus AND ' + section + ' =:MANUFACTURING')
						.toSOQL()
		);
	}

	public List<TreatmentJourneySteps__mdt> selectDeliveryStepsByStatuses(String carePlanStatus, String orderStatus, String slotStatus, String poStatus,  String shippingStatus, String manufacturingStatus, String deliveryStatus)
	{
		String section = TreatmentJourneySteps__mdt.SectionName__c.getDescribe().getName();
		String careplan = TreatmentJourneySteps__mdt.CarePlanStatus__c.getDescribe().getName();
		String order = TreatmentJourneySteps__mdt.OrderStatus__c.getDescribe().getName();
		String slot = TreatmentJourneySteps__mdt.SlotStatus__c.getDescribe().getName();
		String po = TreatmentJourneySteps__mdt.POStatus__c.getDescribe().getName();
		String ship = TreatmentJourneySteps__mdt.ShippingStatus__c.getDescribe().getName();
		String manufacturingStatusLabel = TreatmentJourneySteps__mdt.ManufacturingStatus__c.getDescribe().getName();
		String deliveryStatusLabel = TreatmentJourneySteps__mdt.DeliveryStatus__c.getDescribe().getName();

		return (List<TreatmentJourneySteps__mdt>) Database.query(
				newQueryFactory()
						.setCondition(careplan + ' =:carePlanStatus AND ' + order + ' =:orderStatus AND ' + slot + ' =:slotStatus AND ' + po + ' =:poStatus AND ' + ship + ' =:shippingStatus AND ' + manufacturingStatusLabel + ' =:manufacturingStatus AND ' + deliveryStatusLabel + ' =:deliveryStatus AND '  + section + ' =:DELIVERY')
						.toSOQL()
		);

	}
}