objects/AssociatedLocation/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Formula field for address related to location object.</description>
    <formula>IF(ISBLANK(Location.AddressLine2__c),
Location.AddressLine1__c  + &quot;, &quot; + Location.City__c  + &quot;, &quot; +  Text(Location.State__c ) + &quot;, &quot; +  Text(Location.Country__c)  + &quot;, &quot; + Location.PostalCode__c,
Location.AddressLine1__c  + &quot;, &quot; +  Location.AddressLine2__c  + &quot;, &quot; +  Location.City__c  + &quot;, &quot; +  Text(Location.State__c ) + &quot;, &quot; +  Text(Location.Country__c)  + &quot;, &quot; + Location.PostalCode__c)</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PatientServicesEnrolleesController.cls
public with sharing class PatientServicesEnrolleesController  
{
	public Id pseId { get; set { pseId = value; getPseData();} }
	public Id patientId { get; set;}
	public List<HealthCloudGA__ContactContactRelation__c> contactContactRelationsList { get; set;}
	public List<AssociatedLocation> treatmentSiteList { get; set;}
	public String cartCoordinatorName { get; set;}
	public String treatmentSiteName { get; set;}
	public String treatmentSiteAddress { get; set;}
    
    public Id getPseData()
    {
        PatientServicesEnrolleesService service = (PatientServicesEnrolleesService) Application.Service
													.newInstance(PatientServicesEnrolleesService.class);
		patientId = service.getPatientIdForEmailTemplate(pseId);
		contactContactRelationsList = service.getRelatedContactForEmailTemplate(patientId);
		treatmentSiteList = service.getTreatmentSiteForEmailTemplate(contactContactRelationsList);

		if(String.isNotBlank(contactContactRelationsList[0].HealthCloudGA__Contact__r.Name))
		{
			this.cartCoordinatorName = contactContactRelationsList[0].HealthCloudGA__Contact__r.Name;
		}

		if(String.isNotBlank(treatmentSiteList[0].ParentRecord.Name) && String.isNotBlank(treatmentSiteList[0].Address__c))
		{
			this.treatmentSiteName = treatmentSiteList[0].ParentRecord.Name;
			this.treatmentSiteAddress = treatmentSiteList[0].Address__c;
		}
		
		return patientId;
	}
}