objects/AssociatedLocation/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <description>Formula field for address related to location object.</description>
    <formula>IF(ISBLANK(Location.AddressLine2__c),
Location.AddressLine1__c  + &quot;, &quot; + Location.City__c  + &quot;, &quot; +  Text(Location.State__c ) + &quot;, &quot; +  Text(Location.Country__c)  + &quot;, &quot; + Location.PostalCode__c,
Location.AddressLine1__c  + &quot;, &quot; +  Location.AddressLine2__c  + &quot;, &quot; +  Location.City__c  + &quot;, &quot; +  Text(Location.State__c ) + &quot;, &quot; +  Text(Location.Country__c)  + &quot;, &quot; + Location.PostalCode__c)</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

objects/Location/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

objects/Location/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

classes/AssociatedLocationsSelector.cls
public with sharing class AssociatedLocationsSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				Schema.AssociatedLocation.Id,
				Schema.AssociatedLocation.ParentRecordId,
				Schema.AssociatedLocation.Address__c,
				Schema.AssociatedLocation.LocationId,
				Schema.AssociatedLocation.Type
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Schema.AssociatedLocation.SObjectType;
	}

	public List<Schema.AssociatedLocation> getAddressesForSites(Set<Id> accountIds)
	{
		return ((List<Schema.AssociatedLocation>) Database.query(
				newQueryFactory()
						.selectFields(getSObjectFieldList())
						.selectField('Location.Country__c')
						.selectField('ParentRecord.Name')
						.selectField('ParentRecord.recordTypeId')
						.setCondition('ParentRecordId IN:accountIds')
						.toSOQL()
		));
	}

	public List<Schema.AssociatedLocation> elevatedGetAddressesForSites(Set<Id> accountIds)
	{
		fflib_QueryFactory queryFactory = newQueryFactory();
		return new elevatedContext(queryFactory).elevatedGetAddressesForSites(accountIds);
	}

	public List<Schema.AssociatedLocation> selectAccountAddressInfo(Set<Id> accountIds)
	{
		return ((List<Schema.AssociatedLocation>) Database.query(
				newQueryFactory()
						.selectFields(getSObjectFieldList())
						.selectField('Location.Country__c')
						.selectField('Location.City__c')
						.selectField('Location.AddressLine1__c')
						.selectField('Location.AddressLine2__c')
						.selectField('Location.State__c')
						.selectField('Location.PostalCode__c')
						.selectField('ParentRecord.Name')
						.setCondition('ParentRecordId IN:accountIds')
						.toSOQL()
		));
	}

	private without sharing class elevatedContext
	{
		private fflib_QueryFactory queryFactory;

		private elevatedContext(fflib_QueryFactory queryFactory)
		{
			this.queryFactory = queryFactory;
		}

		private List<AssociatedLocation> elevatedGetAddressesForSites(Set<Id> accountIds)
		{
			Set<String> fieldSet = new Set<String>();
			fieldSet.add('ParentRecord.recordTypeId');
			fieldSet.add('Location.Country__c');
			queryFactory.selectFields(fieldSet);
			queryFactory.setCondition('ParentRecordId IN:accountIds');
			return (List<AssociatedLocation>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}
	}
}