objects/OrderTaskConfig__mdt/OrderTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type to Create adhoc Tasks for Vein to Vein to manage outbound integrations.</description>
    <label>Order Task Config</label>
    <pluralLabel>Order Tasks Config</pluralLabel>
</CustomObject>

objects/OrderTaskConfig__mdt/fields/DaysToReachDueDate__c.field-meta.xml
<CustomField>
    <fullName>DaysToReachDueDate__c</fullName>
    <description>Days To Reach Due Date in the task</description>
    <label>Days To Reach Due Date</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>set Active the current metadata to create tasks</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <description>Picklist to select the Task Priority</description>
    <label>Task Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <description>Status for the tasks </description>
    <label>Task Status</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <description>Subjects for the current tasks</description>
    <label>Task Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <description>This field holds value to set for task while task creation</description>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
                <default>true</default>
                <label>Automated</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/OrderTaskConfigSelector.cls
public inherited sharing class OrderTaskConfigSelector extends sflib_SObjectSelector 
{
	public static List<OrderTaskConfig__mdt> orderTasksConfig
	{
		get
		{
			if (orderTasksConfig == null)
			{
				orderTasksConfig = ((OrderTaskConfigSelector) Application.Selector.newInstance(getObjectType()))
						.getActiveOrderTaskConfigInfo();
			}
			return orderTasksConfig;
		}
		private set;
	}

	public SObjectType getSObjectType()
	{
		return OrderTaskConfig__mdt.SobjectType;
	}

	public static sobjectType getObjectType()
	{
		return OrderTaskConfig__mdt.sObjectType;
	}

	public List<SObjectField> getSObjectFieldList()
	{
		return new List<SObjectField>
		{
				OrderTaskConfig__mdt.IsActive__c,
				OrderTaskConfig__mdt.DaysToReachDueDate__c,
				OrderTaskConfig__mdt.TaskPriority__c,
				OrderTaskConfig__mdt.TaskStatus__c,
				OrderTaskConfig__mdt.TaskSubject__c,
                OrderTaskConfig__mdt.TaskType__c
		};
	}

	public List<OrderTaskConfig__mdt> getActiveOrderTaskConfigInfo()
	{
		return selectOrderTaskConfigInfo(true);
	}

	public List<OrderTaskConfig__mdt> selectOrderTaskConfigInfo(Boolean isActive)
	{

		fflib_QueryFactory queryFactory = newQueryFactory();
		queryFactory.setCondition(OrderTaskConfig__mdt.isActive__c.getDescribe().getName() +
				' = :IsActive');
		return (List<OrderTaskConfig__mdt>) Database.query(queryFactory.toSOQL());
	}

	public Map<String, List<OrderTaskConfig__mdt>> selectActiveOrderTaskConfigInfoPerStatus()
	{
		Map<String, List<OrderTaskConfig__mdt>> orderTaskConfig = new Map<String, List<OrderTaskConfig__mdt>>();
		for (OrderTaskConfig__mdt objOrderTaskConfig : orderTasksConfig)
		{
			if (orderTaskConfig.containsKey(objOrderTaskConfig.TaskSubject__c))
			{
				orderTaskConfig.get(objOrderTaskConfig.TaskSubject__c).add(objOrderTaskConfig);
			}
			else
			{
				orderTaskConfig.put(objOrderTaskConfig.TaskSubject__c, new List<OrderTaskConfig__mdt> {objOrderTaskConfig});
			}
		}
		return orderTaskConfig;
	}

}