objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User to whom the alert has been assigned</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The detailed description of the Alert created for the user</description>
    <label>Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Notification__c/fields/ReadDate__c.field-meta.xml
<CustomField>
    <fullName>ReadDate__c</fullName>
    <description>Date when the alert was read by the user</description>
    <label>Read Date</label>
    <type>Date</type>
</CustomField>

objects/Notification__c/fields/ReadStatus__c.field-meta.xml
<CustomField>
    <fullName>ReadStatus__c</fullName>
    <description>Used to track whether the user has read the alert or not</description>
    <label>Read Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Unread</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>Salesforce Id of the record associated with the alert</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the alert to control number of alerts visible to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The Subject of the alert</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/NotificationsSelector.cls
public with sharing class NotificationsSelector extends fflib_SObjectSelector
{
	String assignedTo = Notification__c.AssignedTo__c.getDescribe().getName();
	String notificationReadStatus = Notification__c.ReadStatus__c.getDescribe().getName();
	String notificationRelatedRecordId = Notification__c.RelatedRecordId__c.getDescribe().getName();

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				Notification__c.AssignedTo__c,
				Notification__c.Id,
				Notification__c.Message__c,
				Notification__c.Name,
				Notification__c.ReadDate__c,
				Notification__c.ReadStatus__c,
				Notification__c.RelatedRecordId__c,
				Notification__c.Status__c,
				Notification__c.Subject__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Notification__c.SObjectType;
	}

	public List<Notification__c> selectAll()
	{
		return (List<Notification__c>) Database.query(
				newQueryFactory()
						.toSOQL()
		);
	}

	public Notifications selectById(Set<Id> notificationId)
	{
		return (Notifications) Application.Domain.newInstance(
				(List<Notification__c>) selectSObjectsById(notificationId)
		);
	}

	public Notifications selectByAssignedToWithStatusWithLimit(Set<id> assignedUserId, Set<String> status)
	{
		return (Notifications) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.setCondition(assignedTo + ' IN: assignedUserId AND ' + notificationReadStatus + ' IN: status')
								.setOrdering('LastModifiedDate', fflib_QueryFactory.SortOrder.DESCENDING)
								.setLimit(Integer.valueOf(System.Label.notificationCountLimit))
								.toSOQL()
				)
		);
	}

	public Notifications selectByAssignedToWithStatus(Set<Id> assignedUserId, Set<String> status)
	{
		return (Notifications) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.setCondition(assignedTo + ' IN: assignedUserId AND ' + notificationReadStatus + ' IN: status')
								.setOrdering('LastModifiedDate', fflib_QueryFactory.SortOrder.DESCENDING)
								.toSOQL()
				)
		);
	}

	public Notifications selectRelatedRecordId(Set<Id> relatedRecordId, Set<String> status)
	{
		return (Notifications) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.setCondition(notificationRelatedRecordId + ' IN: relatedRecordId AND ' + notificationReadStatus + ' IN: status')
								.setOrdering('LastModifiedDate', fflib_QueryFactory.SortOrder.DESCENDING)
								.toSOQL()
				)
		);
	}
}