objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The detailed description of the Alert created for the user</description>
    <label>Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

objects/NotificationEngine__mdt/NotificationEngine__mdt.object-meta.xml
<CustomObject>
    <label>Notification Engine</label>
    <pluralLabel>Notification Engine</pluralLabel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/ReasonforReschedule__c.field-meta.xml
<CustomField>
    <fullName>ReasonforReschedule__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Reason for Re-schedule of the apheresis pick-up date.</description>
    <label>Reason for Reschedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient Health</fullName>
            </value>
            <value>
                <fullName>Patient Scheduling Conflict</fullName>
            </value>
            <value>
                <fullName>Site Scheduling Conflict</fullName>
            </value>
            <value>
                <fullName>Weather/Travel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SpecifyTheOtherReasonForReschedule__c.field-meta.xml
<CustomField>
    <fullName>SpecifyTheOtherReasonForReschedule__c</fullName>
    <description>This field stores the reason of rescheduling order when user reschedules the order submission</description>
    <label>Specify The Other Reason For Reschedule</label>
    <type>TextArea</type>
</CustomField>

classes/NotificationsServiceTest.cls
@isTest(seeAllData=false)
public with sharing class NotificationsServiceTest
{
	public static final String SCRIPTTHROWNEXCEPTION = 'Script-thrown exception';
	public static final string strSuccess = 'SUCCESS';

	@testSetup
	static void setup()
	{
		List<Account> patientAccountsList = TestDataFactory.getPatientAccountsList();
		insert patientAccountsList;

		Map<Id, Contact> contactsByAccountIds = ((ContactsSelector) Application.Selector
				.newInstance(Contact.SObjectType))
				.selectByAccountId(new Set<Id> {patientAccountsList[0].Id})
				.getContactsByAccountId();

		List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
		insert carePlanList;
	}

	@IsTest
	public static void itShouldCreateNotificationRecords()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system
			Map<Id, Account> patientAccountsByIds = new Accounts(((AccountsSelector) Application.Selector
					.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {StaticConstants.PatientRecordTypeDeveloperName}))
					.getById();

			List<Case> carePlanList = ((CasesSelector) Application.Selector.newInstance(Case.SObjectType)).selectByPatientAccountId((new Map<Id, Account>(patientAccountsByIds)).keySet()).getRecords();

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});

			List<NotificationEngine__mdt> notificationEngineList = ((NotificationEngineSelector) Application.Selector
					.newInstance(NotificationEngine__mdt.SObjectType))
					.selectAll();

			List<UserRole> lstRole = ((UserRolesSelector) Application.Selector.newInstance(UserRole.SObjectType)).selectByName(new Set<String> {'Internal Site Administrator'});
			List<User> userList = TestDataFactory.getUsersToInsert('Internal Base User', 9);
			for (User objUser : userList)
			{
				objUser.UserRoleId = lstRole[0].Id;
			}
			insert userList;

			//WHEN - Notifications are being initiated for creation

			System.runAs(userList[0])
			{
				new NotificationsService().createNotificationRecords(new List<Account> {patientAccountsByIds.values()[0]}, notificationEngineList, userList, ordersList);
			}

			List<Notification__c> notificationsList = ((NotificationsSelector) Application.Selector.newInstance(Notification__c.SObjectType)).selectAll();

			//THEN - Notifications Alerts are being created for patients
			System.assertEquals(1, notificationsList.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateNotificationMessage()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system
			Map<Id, Account> patientAccountsByIds = new Accounts(((AccountsSelector) Application.Selector
					.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {StaticConstants.PatientRecordTypeDeveloperName}))
					.getById();

			List<Case> carePlanList = ((CasesSelector) Application.Selector.newInstance(Case.SObjectType)).selectByPatientAccountId((new Map<Id, Account>(patientAccountsByIds)).keySet()).getRecords();

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});
			ordersList[0].OrderStatus__c = 'Order Rescheduled';
			ordersList[0].ApheresisPickUpDate__c = System.today();
			ordersList[0].ReasonforReschedule__c = 'Patient Health';
			update ordersList;

			//WHEN - Order status is changed to meet the above criteria

			String initialNotificationMessage = 'Test Notification' + '<Apheresis Pick-Up Date>';
			Notification__c objNotification = new Notification__c();
			objNotification.Message__c = initialNotificationMessage;

			new NotificationsService().updateNotificationBodyForPickupDateAndReason(objNotification, ordersList);

			//THEN - Notifications Alerts are being created for patients
			System.assertNotEquals(objNotification.Message__c, initialNotificationMessage, strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateNotificationMessageForOther()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system
			Map<Id, Account> patientAccountsByIds = new Accounts(((AccountsSelector) Application.Selector
					.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {StaticConstants.PatientRecordTypeDeveloperName}))
					.getById();

			List<Case> carePlanList = ((CasesSelector) Application.Selector.newInstance(Case.SObjectType)).selectByPatientAccountId((new Map<Id, Account>(patientAccountsByIds)).keySet()).getRecords();

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});
			ordersList[0].OrderStatus__c = 'Order Rescheduled';
			ordersList[0].ApheresisPickUpDate__c = System.today();
			ordersList[0].ReasonforReschedule__c = 'Other';
			ordersList[0].SpecifyTheOtherReasonForReschedule__c = 'Test Reason';
			update ordersList;

			//WHEN - Order status is changed to meet the above criteria

			String initialNotificationMessage = 'Test Notification' + '<Apheresis Pick-Up Date>' + '<Reason for Rescheduling>';
			Notification__c objNotification = new Notification__c();
			objNotification.Message__c = initialNotificationMessage;

			new NotificationsService().updateNotificationBodyForPickupDateAndReason(objNotification, ordersList);

			//THEN - Notifications Alerts are being created for patients
			System.assertNotEquals(objNotification.Message__c, initialNotificationMessage, strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

}