objects/Case/fields/DateOfCancellationRequest__c.field-meta.xml
<CustomField>
    <fullName>DateOfCancellationRequest__c</fullName>
    <description>This field holds Created date Value</description>
    <formula>CreatedDate</formula>
    <label>Date of cancellation request</label>
    <type>Date</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ApheresisPO__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration, stores the Apheresis PO # value.</description>
    <externalId>true</externalId>
    <label>Apheresis PO #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/ApheresisPOStatus__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPOStatus__c</fullName>
    <description>Hidden field to track Apheresis PO status</description>
    <label>Apheresis PO Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/ApheresisSite__c.field-meta.xml
<CustomField>
    <fullName>ApheresisSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Apheresis Site recorded on Care Plan.</description>
    <label>Apheresis Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Apheresis Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Apheresis Site)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/ApheresisSitePickupAddress__c.field-meta.xml
<CustomField>
    <fullName>ApheresisSitePickupAddress__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Site Pickup Address</description>
    <label>Apheresis Site Pickup Address</label>
    <length>250</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/ASNToAnaplanStatus__c.field-meta.xml
<CustomField>
    <fullName>ASNToAnaplanStatus__c</fullName>
    <description>Apheresis Shipment Notice to Anaplan Status</description>
    <label>ASN to Anaplan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/AtlasOrderId__c.field-meta.xml
<CustomField>
    <fullName>AtlasOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration, stores the Atlas Order ID value.</description>
    <externalId>true</externalId>
    <label>Atlas Order ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/AttestedForCompletion__c.field-meta.xml
<CustomField>
    <fullName>AttestedForCompletion__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Attested for Completion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/ConfirmedFPDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedFPDeliveryDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Confirmed FP Delivery Date of the order.</description>
    <label>Confirmed DP Delivery Date from Site</label>
    <type>Date</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Coordinator__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAR-T Coordinator associated to the related Care Plan.</description>
    <label>CAR-T Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CryoCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>CryoCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Cell Pickup Date and Time related to the order.</description>
    <label>Cryo Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/CryoSite__c.field-meta.xml
<CustomField>
    <fullName>CryoSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cryo Site recorded on Care Plan.</description>
    <label>Cryo Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cryo Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Cryo Site)</relationshipLabel>
    <relationshipName>Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CryoSiteDropOffAddress__c.field-meta.xml
<CustomField>
    <fullName>CryoSiteDropOffAddress__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Site Drop-Off Address</description>
    <label>Cryo Site Drop-Off Address</label>
    <length>250</length>
    <type>Text</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/CryoSitePickupAddress__c.field-meta.xml
<CustomField>
    <fullName>CryoSitePickupAddress__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo Site Pickup Address</description>
    <label>Cryo Site Pickup Address</label>
    <length>250</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/CryoSiteType__c.field-meta.xml
<CustomField>
    <fullName>CryoSiteType__c</fullName>
    <description>This field holds value of Cryo Site records type field value</description>
    <formula>TEXT(CryoSite__r.Type)</formula>
    <label>Cryo Site Type</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo type related to the associated cryo site.</description>
    <label>Cryo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
                <isActive>false</isActive>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Raritan</fullName>
                <isActive>false</isActive>
                <label>Raritan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/DateOfCancellationRequest__c.field-meta.xml
<CustomField>
    <fullName>DateOfCancellationRequest__c</fullName>
    <description>Date when the order cancellation request is placed</description>
    <label>Date of Cancellation Request</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/DPOkToShipToSAPStatus__c.field-meta.xml
<CustomField>
    <fullName>DPOkToShipToSAPStatus__c</fullName>
    <description>DP Ok to Ship to SAP Status</description>
    <label>DP Ok to Ship to SAP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/EstimatedDrugProductDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDrugProductDeliveryDate__c</fullName>
    <label>Estimated Drug Product Delivery Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/FinalDPDateinVineti__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDateinVineti__c</fullName>
    <description>Final DP Date that is coming from Vineti</description>
    <label>Final DP Date Updated in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/FinalDPDropOffDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDropOffDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Final DP Drop-off Date and Time of the related order.</description>
    <label>Final DP Drop-Off Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FinalDPPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FinalDPPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Final DP Pickup Date and Time related to the order.</description>
    <label>Final DP Pickup Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FreshCellDropOffDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FreshCellDropOffDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Fresh Cell Drop Off Date and Time related to the order.</description>
    <label>Fresh Cell Drop Off Date and Time</label>
    <type>DateTime</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FreshCellPickupDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>FreshCellPickupDateAndTime__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Fresh Cell Pickup Date and Time related to the order.</description>
    <label>Fresh Cell Pickup Date and Time</label>
    <type>DateTime</type>
</CustomField>

objects/Order__c/fields/InfusionDate__c.field-meta.xml
<CustomField>
    <fullName>InfusionDate__c</fullName>
    <description>Infusion Date of the drug.</description>
    <label>Infusion Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ManufacturingSite__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manufacturing Site recorded on Care Plan.</description>
    <label>Manufacturing Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Manufacturing Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Manufacturing Site)</relationshipLabel>
    <relationshipName>Orders4</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the enrolled patient.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Patient)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>PO Status of the order.</description>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Pending</fullName>
                <default>true</default>
                <label>PO Pending</label>
            </value>
            <value>
                <fullName>PO Received</fullName>
            </value>
            <value>
                <fullName>PO Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/OrdersSelector.cls
public with sharing class OrdersSelector extends fflib_SObjectSelector
{
	public final static String carePlanStatusNew = 'New';
	public final static String carePlanStatusManufactured = 'Manufacturing';

	public final static String orderManufacturingStatusQRComplete = 'QR Complete';

	String patientId = Order__c.Patient__c.getDescribe().getName();

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				Order__c.ApheresisSite__c,
				Order__c.ApheresisSitePickupAddress__c,
				Order__c.ApheresisPickUpDate__c,
				Order__c.ApheresisPO__c,
                Order__c.ApheresisPOStatus__c,
				Order__c.ASNToAnaplanStatus__c,
				Order__c.AtlasOrderId__c,
				Order__c.AttestedForCompletion__c,
				Order__c.CarePlanId__c,
				Order__c.CartOrderId__c,
				Order__c.ConfirmedFPDeliveryDate__c,
				Order__c.Coordinator__c,
				Order__c.CryoSite__c,
				Order__c.CryoCellPickupDateAndTime__c,
				Order__c.CryoSiteType__c,
				Order__c.CryoType__c,
				Order__c.CryoSiteDropOffAddress__c,
				Order__c.CryoSitePickupAddress__c,
				Order__c.DateOfCancellationRequest__c,
				Order__c.DPOkToShipToSAPStatus__c,
				Order__c.EstimatedDrugProductDeliveryDate__c,
				Order__c.FinalDPDateinVineti__c,
				Order__c.FinalDPDropOffDateAndTime__c,
				Order__c.FinalDPPickupDateAndTime__c,
				Order__c.FreshCellDropOffDateAndTime__c,
				Order__c.FreshCellPickupDateAndTime__c,
				Order__c.Id,
				Order__c.InfusionDate__c,
				Order__c.ManufacturingSite__c,
				Order__c.ManufacturingSiteDropOffAddress__c,
				Order__c.ManufacturingSitePickupAddress__c,
				Order__c.ManufacturingStatus__c,
				Order__c.ManufacturingMilestoneDateTime__c,
				Order__c.Name,
				Order__c.OrderPlacementInfo__c,
				Order__c.OrderStatus__c,
				Order__c.OrderRescheduledinVineti__c,
				Order__c.Patient__c,
				Order__c.PatientID__c,
				Order__c.PatientStatus__c,
				Order__c.ProjectedDeliveryDate__c,
				Order__c.Physician__c,
				Order__c.POStatus__c,
				Order__c.ProjectedDeliveryDate__c,
				Order__c.QTCPOtoSDStatus__c,
				Order__c.ReasonForOrderWithdrawal__c,
				Order__c.ReasonforReschedule__c,
				Order__c.SDPO__c,
				Order__c.SitePO__c,
				Order__c.ShippingStatus__c,
				Order__c.SlotStatus__c,
				Order__c.SpecifyTheOtherReasonForReschedule__c,
				Order__c.TreatmentSite__c,
				Order__c.TreatmentSiteDropOffAddress__c,
				Order__c.VinetiCOI__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Order__c.SObjectType;
	}

	public Orders selectByAccountId(Set<Id> accountIds)
	{
		return (Orders) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.selectField('ApheresisSite__r.Name')
								.selectField('CarePlanID__r.Status')
								.selectField('ManufacturingStatus__c')
								.setCondition('Patient__c IN :accountIds')
								.toSOQL()
				)
		);
	}

	public Database.QueryLocator selectByApheresisDueDate()
	{
		String patientStatus = StaticConstants.PatientStatusVerified;
		return Database.getQueryLocator(
				newQueryFactory()
						.setCondition('ApheresisPickUpDate__c = TODAY AND PatientStatus__c =:patientStatus' )
						.toSOQL()
		);
	}

	public List<Order__c> selectOrdersByOrderId(Set<Id> orderIds)
	{
		return (List<Order__c>) Database.query(
				newQueryFactory()
						.selectField('CryoSite__c')
						.selectField('CryoSite__r.Type')
						.selectField('CryoSite__r.ERPSiteID__c')
						.selectField('ApheresisSite__r.ERPSiteID__c')
						.selectField('TreatmentSite__r.ERPSiteID__c')
						.selectField('ApheresisSite__r.AccountIdentifier__c')
						.selectField('TreatmentSite__r.AccountIdentifier__c')
						.selectField('ApheresisSite__r.Type')
						.setCondition('Id IN : orderIds')
						.toSOQL());
	}

	public List<Order__c> selectAll()
	{
		return((List<Order__c>) Database.query(
				newQueryFactory()
						.selectField('CryoSite__r.ERPSiteID__c')
						.selectField('ApheresisSite__r.ERPSiteID__c')
						.selectField('TreatmentSite__r.ERPSiteID__c')
						.selectField('ApheresisSite__r.Type')
						.setOrdering('Name', fflib_QueryFactory.SortOrder.ASCENDING)
						.toSOQL()));
	}

	public List<Order__c> selectOrdersByCarePlanId(Set<Id> carePlanIds)
	{
		return (List<Order__c>) Database.query(
				newQueryFactory()
						.selectField('CryoSite__c')
						.selectField('CryoSite__r.Type')
						.selectField('TreatmentSite__c')
						.setCondition('CarePlanId__c IN : carePlanIds')
						.toSOQL());
	}

	public List<Order__c> selectOrdersByPatientId(Set<Id> patientIds)
	{
		return (List<Order__c>) Database.query(
				newQueryFactory()
						.selectField('Patient__r.PatientID__c')
						.selectField('TreatmentSite__r.ERPSiteID__c')
						.selectField('Name')
						.setCondition(patientId + ' IN :patientIds')
						.toSOQL());
	}

	public List<Order__c> elevatedSelectByAccountIdAndCarePlanStatus(Set<Id> accountIds, Set<String> careplanStatuses)
	{
		ElevateContext elevatedContext = new ElevateContext(this);
		return elevatedContext.elevatedSelectByAccountIdAndCarePlanStatus(accountIds, careplanStatuses);
	}

	public List<Order__c> elevatedSelectByAccountId(Set<Id> accountIds)
	{
		ElevateContext elevatedContext = new ElevateContext(this);
		return elevatedContext.elevatedSelectByAccountId(accountIds);
	}

	public List<Order__c> elevatedSelectedByAccountCarePlanOrderStatus(Set<Id> accountIds)
	{
		ElevateContext elevatedContext = new ElevateContext(this);
		return elevatedContext.elevatedSelectedByAccountCarePlanOrderStatus(accountIds);
	}

	private without sharing class ElevateContext extends fflib_SObjectSelector
	{
		OrdersSelector selector;

		public ElevateContext(OrdersSelector selector)
		{
			super(true, false, false, true);
			this.selector = selector;
		}

		public List<Schema.SObjectField> getSObjectFieldList()
		{
			return selector.getSObjectFieldList();
		}

		public Schema.SObjectType getSObjectType()
		{
			return selector.getSObjectType();
		}

		public List<Order__c> elevatedSelectByAccountIdAndCarePlanStatus(Set<Id> accountIds, Set<String> careplanStatuses)
		{
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('ApheresisSite__r.Name');
			queryFactory.selectField('CarePlanID__r.Status');
			queryFactory.setCondition('Patient__c IN :accountIds AND CarePlanID__r.Status IN:careplanStatuses');
			return (List<Order__c>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		public List<Order__c> elevatedSelectByAccountId(Set<Id> accountIds)
		{
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('ApheresisSite__r.Name');
			queryFactory.selectField('CarePlanID__r.Status');
			queryFactory.selectField('DateOfCancellationRequestTCP__c');
			queryFactory.selectField('ManufacturingStatus__c');
			queryFactory.setCondition('Patient__c IN :accountIds');
			return (List<Order__c>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		public List<Order__c> elevatedSelectedByAccountCarePlanOrderStatus(Set<Id> accountIds)
		{
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('ApheresisSite__r.Name');
			queryFactory.selectField('OrderStatus__c');
			queryFactory.selectField('CarePlanID__r.Status');
			queryFactory.setCondition('Patient__c IN :accountIds AND (CarePlanID__r.Status =:carePlanStatusNew OR (CarePlanID__r.Status =:carePlanStatusManufactured AND ManufacturingStatus__c = :orderManufacturingStatusQRComplete))');
			queryFactory.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
			return (List<Order__c>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}
	}

    public Database.QueryLocator getQLOfOrdersCreatedEditedInLastNDays(Integer lastNDays)
	{
		return Database.getQueryLocator(
				newQueryFactory(false, false, false)
            			.selectField(Order__c.Patient__c.getDescribe().getName())
						.setCondition(String.format('{0} = LAST_N_DAYS:{1}',
						new List<String>{
								Order__c.LastModifiedDate.getDescribe().getName(),
								String.valueOf(lastNDays)}))
						.toSOQL());
	}


}