objects/CarePlanTasksConfigs__mdt/CarePlanTasksConfigs__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Task Due Date Update Config Info Like Prerequisite Conditions on Order Goal and Task Objects and Due Date Values to Set</description>
    <label>CarePlanTasksConfig</label>
    <pluralLabel>CarePlanTasksConfigs</pluralLabel>
</CustomObject>

objects/CountryToRegionMapping__mdt/CountryToRegionMapping__mdt.object-meta.xml
<CustomObject>
    <label>Country To Region Mapping</label>
    <pluralLabel>Country To Region Mapping</pluralLabel>
</CustomObject>

objects/HealthCloudGA__AccountAccountRelation__c/HealthCloudGA__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as between a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/KnowledgeDataCategory__mdt/KnowledgeDataCategory__mdt.object-meta.xml
<CustomObject>
    <description>Setting that describes the icon and page type associated to each data category for knowledge on community</description>
    <label>Knowledge Data Category</label>
    <pluralLabel>Knowledge Data Categories</pluralLabel>
</CustomObject>

objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NotificationEngine__mdt/NotificationEngine__mdt.object-meta.xml
<CustomObject>
    <label>Notification Engine</label>
    <pluralLabel>Notification Engine</pluralLabel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OrderMilestones__c/OrderMilestones__c.object-meta.xml
<CustomObject>
    <label>Order Milestones</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderMilestones__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order related to the milestone.</description>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Milestones</relationshipLabel>
    <relationshipName>OrderMilestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/OrderMilestonesDetails__mdt/OrderMilestonesDetails__mdt.object-meta.xml
<CustomObject>
    <label>Order Milestones Details</label>
    <pluralLabel>Order Milestones Details</pluralLabel>
</CustomObject>

objects/OrderMilestonesUpdateRules__mdt/OrderMilestonesUpdateRules__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to capture business rules for mapping on order manufacturing statuses.</description>
    <label>Order Milestones Update Rules</label>
    <pluralLabel>Order Milestones Update Rules</pluralLabel>
</CustomObject>

objects/OrderProcessingRule__mdt/OrderProcessingRule__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Order and its related tasks and goals to update through Entire Order Life Cycle</description>
    <label>Order Processing Rules</label>
    <pluralLabel>Order Processing Rules</pluralLabel>
</CustomObject>

objects/OrderTaskConfig__mdt/OrderTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type to Create adhoc Tasks for Vein to Vein to manage outbound integrations.</description>
    <label>Order Task Config</label>
    <pluralLabel>Order Tasks Config</pluralLabel>
</CustomObject>

objects/PatientEnrollmentSteps__mdt/PatientEnrollmentSteps__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch steps for patient enrollment dynamically</description>
    <label>Patient Enrollment Steps</label>
    <pluralLabel>Patient Enrollment Steps</pluralLabel>
</CustomObject>

objects/PatientEnrollmentSteps__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Custom field to store order for each step in the progress indicator</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/PatientLandingPageStatusValue__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch Patient Treatment Milestone for patients-TCP list view table</description>
    <label>Patient Landing Page Status Value</label>
    <pluralLabel>Patient Landing Page Status Values</pluralLabel>
</CustomObject>

objects/PatientServiceEnrolleeTaskConfig__mdt/PatientServiceEnrolleeTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata contains information related to Task Record Creation values on Patient Service Enrolled Record Creation.</description>
    <label>Patient Service Enrollee Task Config</label>
    <pluralLabel>Patient Service Enrollee Task Config</pluralLabel>
</CustomObject>

objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RecordShareConfig__mdt/RecordShareConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store public group values for setup CCM sharing rules for Patient, Caregiver and Sites.</description>
    <label>Record Share Config</label>
    <pluralLabel>Record Share Configs</pluralLabel>
</CustomObject>

objects/SiteProduct__c/SiteProduct__c.object-meta.xml
<CustomObject>
    <label>Site-Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TreatmentJourneySteps__mdt/TreatmentJourneySteps__mdt.object-meta.xml
<CustomObject>
    <label>Treatment Journey Steps</label>
    <pluralLabel>Treatment Journey Steps</pluralLabel>
</CustomObject>

classes/Application.cls
public class Application
{
	public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
			new fflib_Application.UnitOfWorkFactory(
					new List<SObjectType>
					{
							Account.SObjectType,
							AccountShare.SObjectType,
							AccountContactRelation.SObjectType,
							Attachment.SObjectType,
							ContentVersion.SObjectType,
							ContentDocumentLink.SObjectType,
							Schema.Location.SObjectType,
							Schema.AssociatedLocation.SObjectType,
							CareProgramEnrollee.SObjectType,
							CareProgramEnrolleeProduct.SObjectType,
							CareProgramEnrolleeProductShare.SObjectType,
							Case.SObjectType,
							CaseShare.SObjectType,
							CaseTeamMember.SObjectType,
							Contact.SObjectType,
							Group.SObjectType,
							GroupMember.SObjectType,
                            HealthCloudGA__AccountAccountRelation__c.SObjectType,
							HealthCloudGA__AccountAccountRelation__Share.SObjectType,
							HealthCloudGA__CarePlanGoal__c.SObjectType,
							HealthCloudGA__CarePlanGoal__share.SObjectType,
							HealthCloudGA__ContactContactRelation__c.SObjectType,
                            HealthCloudGA__ContactContactRelation__Share.SObjectType,
                            Notification__c.SObjectType,
							Order__share.SObjectType,
							Order__c.SObjectType,
							OrderMilestones__c.SObjectType,
                            PatientServicesEnrollee__c.SObjectType,
							PatientServicesEnrollee__Share.SObjectType,
							Task.SObjectType,
							User.SObjectType,
							UserLogin.SObjectType
					});

	public static final fflib_Application.ServiceFactory Service =
			new fflib_Application.ServiceFactory(
					new Map<Type, Type>
					{
							AccountAccountRelationsService.class => AccountAccountRelationsService.class,
							AccountContactRelationsService.class => AccountContactRelationsService.class,
							AccountsService.class => AccountsService.class,
							AccountSharesService.class => AccountSharesService.class,
							AnaplanNotificationService.class => AnaplanNotificationService.class,
							RecordsSharingService.class => RecordsSharingService.class,
							AssociatedLocationsService.class => AssociatedLocationsService.class,
							CasesService.class => CasesService.class,
							CaseTeamMembersService.class => CaseTeamMembersService.class,
							CarePlanGoalsService.class => CarePlanGoalsService.class,
							CareProgramEnrolleesService.class => CareProgramEnrolleesService.class,
                            CareProgramEnrolleeProductsService.class => CareProgramEnrolleeProductsService.class,
							CaseSharesService.class => CaseSharesService.class,
							ContactContactRelationsService.class => ContactContactRelationsService.class,
							ContactsService.class => ContactsService.class,
							GroupMembersService.class => GroupMembersService.class,
							GroupsService.class => GroupsService.class,
							KnowledgeTopicService.class => KnowledgeTopicService.class,
							KnowledgeArticleService.class => KnowledgeArticleService.class,
							ManufacturingMilestonesUpdateService.class => ManufacturingMilestonesUpdateService.class,
							NotificationsService.class => NotificationsService.class,
							OrdersService.class => OrdersService.class,
							OrderMilestonesService.class => OrderMilestonesService.class,
							PatientServicesEnrolleesService.class => PatientServicesEnrolleesService.class,
							PatientTreatmentMilestonesService.class => PatientTreatmentMilestonesService.class,
							PurchaseOrderService.class => PurchaseOrderService.class,
							SalesOrderUpdateService.class => SalesOrderUpdateService.class,
							SiteProductsService.class => SiteProductsService.class,
							TasksService.class => TasksService.class,
							UsersLoginService.class => UsersLoginService.class,
							UsersService.class => UsersService.class
					});

	public static final fflib_Application.SelectorFactory Selector =
			new fflib_Application.SelectorFactory(
					new Map<SObjectType, Type>
					{
							Account.SObjectType => AccountsSelector.class,
                            AccountShare.SObjectType => AccountSharesSelector.class,
							AccountContactRelation.SObjectType => AccountContactRelationsSelector.class,
							BusinessHours.SObjectType => BusinessHoursSelector.class,
							CarePlanTasksConfigs__mdt.SObjectType => CarePlanTasksConfigsSelector.class,
							CareProgramEnrollee.SObjectType => CareProgramEnrolleesSelector.class,
							CareProgramEnrolleeProduct.SObjectType => CareProgramEnrolleeProductsSelector.class,
							CareProgramProduct.SObjectType => CareProgramProductsSelector.class,
							CareProgramEnrolleeProductShare.SObjectType => CareProgramEnrolleeProductSharesSelector.class,
							Case.SObjectType => CasesSelector.class,
							CaseShare.SObjectType => CaseSharesSelector.class,
							CaseTeamRole.SObjectType => CaseTeamRoleSelector.class,
							CaseTeamMember.SObjectType => CaseTeamMembersSelector.class,
							Contact.SObjectType => ContactsSelector.class,
							ContentDocument.SObjectType => ContentDocumentsSelector.class,
							ContentDocumentLink.SObjectType => ContentDocumentLinksSelector.class,
							ContentVersion.SObjectType => ContentVersionsSelector.class,
							CountryToRegionMapping__mdt.SObjectType => CountryToRegionMappingSelector.class,
							EmailTemplate.SObjectType => EmailTemplatesSelector.class,
							Group.SObjectType => GroupsSelector.class,
							GroupMember.SObjectType => GroupMembersSelector.class,
							HealthCloudGA__AccountAccountRelation__c.SObjectType => AccountAccountRelationSelector.class,
                            HealthCloudGA__AccountAccountRelation__Share.SObjectType => AccountAccountRelationSharesSelector.class,
							HealthCloudGA__CarePlanGoal__c.SObjectType => CarePlanGoalsSelector.class,
							HealthCloudGA__CarePlanGoal__Share.SObjectType => CarePlanGoalSharesSelector.class,
							HealthCloudGA__CarePlanTemplate__c.SObjectType => CarePlanTemplatesSelector.class,
							HealthCloudGA__CarePlanTemplateGoal__c.SObjectType => CarePlanTemplateGoalsSelector.class,
							HealthCloudGA__CarePlanTemplateTask__c.SObjectType => CarePlanTemplateTasksSelector.class,
							HealthCloudGA__ContactContactRelation__c.SObjectType => ContactContactRelationSelector.class,
                            HealthCloudGA__ContactContactRelation__Share.SObjectType => ContactContactRelationSharesSelector.class,
							HealthCloudGA__ReciprocalRole__c.SObjectType => ReciprocalRoleSelector.class,
							KnowledgeArticleVersion.SObjectType => KnowledgeArticleSelector.class,
							KnowledgeDataCategory__mdt.SObjectType => KnowledgeDataCategorySelector.class,
                            Notification__c.SObjectType => NotificationsSelector.class,
							NotificationEngine__mdt.SObjectType => NotificationEngineSelector.class,
							Order__c.SObjectType => OrdersSelector.class,
							Order__Share.SObjectType => OrderSharesSelector.class,
							OrderMilestones__c.SObjectType =>OrderMilestonesSelector.class,
							OrderProcessingRule__mdt.SObjectType => OrderProcessingRulesSelector.class,
							OrderMilestonesDetails__mdt.SObjectType => OrderMilestonesDetailsSelector.class,
							OrderMilestonesUpdateRules__mdt.SObjectType => OrderMilestonesUpdateRulesSelector.class,
							OrderTaskConfig__mdt.SObjectType => OrderTaskConfigSelector.class,
							PatientEnrollmentSteps__mdt.SObjectType => PatientEnrollmentStepsSelector.class,
							PatientLandingPageStatusValue__mdt.SObjectType => PatientTreatmentMilestonesSelector.class,
							PatientServicesEnrollee__c.SObjectType => PatientServicesEnrolleesSelector.class,
							PatientServicesEnrollee__Share.SObjectType => PatientServicesEnrolleeSharesSelector.class,
							PatientServiceEnrolleeTaskConfig__mdt.SObjectType => PatientServiceEnrolleeTaskConfigSelector.class,
							PermissionSet.SObjectType => PermissionSetSelector.class,
							Profile.SObjectType => ProfilesSelector.class,
							Schema.AssociatedLocation.SObjectType => AssociatedLocationsSelector.class,
							RecordShareConfig__mdt.SObjectType => RecordShareConfigSelector.class,
							SiteProduct__c.SObjectType => SiteProductsSelector.class,
							Task.SObjectType => TasksSelector.class,
							TreatmentJourneySteps__mdt.SObjectType => TreatmentJourneyStepsSelector.class,
							Topic.SObjectType => KnowledgeTopicSelector.class,
							TopicAssignment.SObjectType => TopicAssignmentSelector.class,
							User.SObjectType => UsersSelector.class,
							UserLogin.SObjectType => UsersLoginSelector.class,
							UserRole.SObjectType => UserRolesSelector.class
					});

	public static final fflib_Application.SelectorFactory ElevatedSelector =
			new fflib_Application.SelectorFactory(
					new Map<SObjectType, Type>
					{
							CareProgram.SObjectType => CareProgramsSelectorElevatedImp.class
					});

	public static final fflib_Application.DomainFactory Domain =
			new fflib_Application.DomainFactory(
					Application.Selector,
					new Map<SObjectType, Type>
					{
							Account.SObjectType => Accounts.Constructor.class,
                            CareProgramEnrolleeProduct.SObjectType => CareProgramEnrolleeProducts.Constructor.class,
							CareProgramProduct.SObjectType => CareProgramProducts.Constructor.class,
							Case.SObjectType => Cases.Constructor.class,
							CaseTeamMember.SObjectType => CaseTeamMembers.Constructor.class,
							Contact.SObjectType => Contacts.Constructor.class,
							EmailTemplate.SObjectType => EmailTemplates.Constructor.class,
							Group.SObjectType => Groups.Constructor.class,
							GroupMember.SObjectType => GroupMembers.Constructor.class,
							User.SObjectType => Users.Constructor.class,
							HealthCloudGA__AccountAccountRelation__c.SObjectType => AccountAccountRelations.Constructor.class,
							HealthCloudGA__CarePlanGoal__c.SObjectType => CarePlanGoals.Constructor.class,
							HealthCloudGA__ContactContactRelation__c.SObjectType => ContactContactRelations.Constructor.class,
                            Notification__c.SObjectType => Notifications.Constructor.class,
							Order__c.SObjectType => Orders.Constructor.class,
							OrderMilestones__c.SObjectType =>OrderMilestones.Constructor.class,
							PatientServicesEnrollee__c.SObjectType =>PatientServicesEnrollees.Constructor.class,
							Schema.AssociatedLocation.SObjectType => AssociatedLocations.class,
							SiteProduct__c.SObjectType => SiteProducts.Constructor.class,
							Task.SObjectType => Tasks.Constructor.class
					});

	public static final sflib_ILogger logEntry = new sflib_Logger().addAppender(new sflib_logEventAppender());

	public static fflib_ISObjectUnitOfWork getUnitOfWork()
	{
		return Application.UnitOfWork.newInstance();
	}

    public static ISObjectShareSelector getSObjectShareSelectorInstance(SObjectType sObjectType)
    {
        return (ISObjectShareSelector) Application.Selector.newInstance(sObjectType);
    }

}