objects/CarePlanTasksConfigs__mdt/CarePlanTasksConfigs__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Task Due Date Update Config Info Like Prerequisite Conditions on Order Goal and Task Objects and Due Date Values to Set</description>
    <label>CarePlanTasksConfig</label>
    <pluralLabel>CarePlanTasksConfigs</pluralLabel>
</CustomObject>

objects/CarePlanTasksConfigs__mdt/fields/APINamesOfChangedFieldsToRunLogic__c.field-meta.xml
<CustomField>
    <fullName>APINamesOfChangedFieldsToRunLogic__c</fullName>
    <description>This Field stores Comma separated fields list to Set Due Daye</description>
    <label>API Names of Changed Fields To Run Logic</label>
    <type>TextArea</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/InheritDueDateFromOrderField__c.field-meta.xml
<CustomField>
    <fullName>InheritDueDateFromOrderField__c</fullName>
    <description>This Field is used to get Due Date from Order Field</description>
    <inlineHelpText>If you need to get Due Date from one of the Order Object Field , then please specify Order Object Fields API Name</inlineHelpText>
    <label>Inherit Due Date From Order Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/NoOfDaysToAddToInheritedDate__c.field-meta.xml
<CustomField>
    <fullName>NoOfDaysToAddToInheritedDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NoOfDaysToAddToInheritedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/OrderConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderConditionsInfo__c</fullName>
    <description>Please provide Conditions in JSON format .For or conditions provide comma separated list against field name</description>
    <inlineHelpText>Please provide Conditions in JSON format .
For or conditions provide comma separated list against field name</inlineHelpText>
    <label>Order Conditions Info</label>
    <type>TextArea</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/TasksConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>TasksConditionsInfo__c</fullName>
    <description>This field stores the prerequisite conditions for order update</description>
    <label>Task Conditions Info</label>
    <type>TextArea</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/OrderGoalTaskPreSync.cls
public with sharing class OrderGoalTaskPreSync
{
	private static final String COMMA = ',';
	private static final String TODAYSTRING = 'Today';

	private List<Order__c> orders = new List<Order__c>();

	public OrderGoalTaskPreSync(List<Order__c> orders)
	{
		this.orders = orders;
	}

	public void processOrderGoalsAndSetTaskDueDate(fflib_ISObjectUnitOfWork uow, Map<Id, Case> carePlanInfo, Map<Id, Set<String>> changedFieldsPerRec)
	{
		List<CarePlanTasksConfigs__mdt> taskDueDateConfigs = ((CarePlanTasksConfigsSelector) Application.Selector.newInstance(CarePlanTasksConfigs__mdt.SObjectType)).selectAllActiveRules();
		if (taskDueDateConfigs.isEmpty())
		{
			return ;
		}

		for (Order__c order : orders)
		{
			for (CarePlanTasksConfigs__mdt taskDueDateConfig : taskDueDateConfigs)
			{
				if (checkIfRuleIsSatisfied(order, changedFieldsPerRec.get(order.Id), taskDueDateConfig))
				{
					Application.logEntry.Debug('Satisfied Rule Name' + taskDueDateConfig.MasterLabel);
					setTaskDueDate(uow, carePlanInfo.get(order.CarePlanID__c), taskDueDateConfig, order);
				}
			}
		}
	}

	private Boolean checkIfRuleIsSatisfied(Order__c order, Set<String> changedFieldsOfOrder, CarePlanTasksConfigs__mdt rule)
	{
		return checkIfRelevantFieldsAreUpdated(changedFieldsOfOrder, rule.APINamesOfChangedFieldsToRunLogic__c) && validateOrderConditions(order, rule.OrderConditionsInfo__c);
	}

	private Boolean checkIfRelevantFieldsAreUpdated(Set<String> changedFieldsOfOrder, String apiNamesOfChangedFieldsToRun)
	{
		return String.isBlank(apiNamesOfChangedFieldsToRun) || checkIfSetContainsAllElements(changedFieldsOfOrder, apiNamesOfChangedFieldsToRun.split(COMMA));
	}

	private Boolean checkIfSetContainsAllElements(Set<String> allElements, List<String> elementsListToCheck)
	{
		if (allElements == null || allElements.isEmpty())
		{
			return false;
		}

		for (String element : elementsListToCheck)
		{
			if (!allElements.contains(element))
			{
				return false;
			}
		}
		return true;
	}

	private Boolean validateOrderConditions(Order__c order, String orderConditionsInfo)
	{
		if (string.isBlank(OrderConditionsInfo))
		{
			return true;
		}

		List<OrderCondition> conditions = (List<OrderCondition>) JSON.deserialize(orderConditionsInfo, List<OrderCondition>.class);

		for (OrderCondition condition : conditions)
		{
			if (!condition.value.split(COMMA).contains((string) order.get(condition.fieldName)))
			{
				return false;
			}
		}
		return true;
	}

	private void setTaskDueDate(fflib_ISObjectUnitOfWork uow, Case carePlan, CarePlanTasksConfigs__mdt taskUpdateConfig, Order__c order)
	{
		if (carePlan == null || carePlan.tasks == null || carePlan.tasks.isEmpty())
		{
			return ;
		}

		TaskUpdateCondition condition = (TaskUpdateCondition) JSON.deserialize(taskUpdateConfig.TasksConditionsInfo__c, TaskUpdateCondition.class);
		Date activityDate = null;
		for (Task taskRecord : getGoalRelatedTasks(condition, carePlan.tasks))
		{
			activityDate = getDueDate(order, taskUpdateConfig.InheritDueDateFromOrderField__c, Integer.valueOf(taskUpdateConfig.NoOfDaysToAddToInheritedDate__c));
			if (activityDate != null)
			{
				taskRecord.ActivityDate = activityDate;
				uow.registerDirty(taskRecord);
			}
		}
	}

	private Date getDueDate(Order__c order, String fieldNameToInheritFrom, Integer noOfDaysToAdd)
	{
		Date dueDate = Date.Today();

		if (TODAYSTRING.equalsIgnoreCase(fieldNameToInheritFrom))
		{
			dueDate = dueDate.addDays(noOfDaysToAdd);
		}
		else if (order.get(fieldNameToInheritFrom) != null)
		{
			dueDate = Date.valueOf(order.get(fieldNameToInheritFrom)).addDays(noOfDaysToAdd);
		}
		return dueDate;
	}

	private List<Task> getGoalRelatedTasks(TaskUpdateCondition condition, List<Task> tasks)
	{
		List<Task> filteredTasks = new List<Task>();
		for (Task taskRecord : tasks)
		{
			if (String.valueOf(condition.subject).equalsIgnoreCase(taskRecord.Subject)
					&& String.valueOf(condition.goalName).equalsIgnoreCase(taskRecord.GoalName__c))
			{
				filteredTasks.add(taskRecord);
			}
		}
		return filteredTasks;
	}

	Class OrderCondition
	{
		String fieldName { get; set; }
		String value { get; set; }
	}

	Class TaskUpdateCondition
	{
		String subject { get; set; }
		String goalName { get; set; }
	}
}