objects/CarePlanTasksConfigs__mdt/CarePlanTasksConfigs__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Task Due Date Update Config Info Like Prerequisite Conditions on Order Goal and Task Objects and Due Date Values to Set</description>
    <label>CarePlanTasksConfig</label>
    <pluralLabel>CarePlanTasksConfigs</pluralLabel>
</CustomObject>

objects/CarePlanTasksConfigs__mdt/fields/APINamesOfChangedFieldsToRunLogic__c.field-meta.xml
<CustomField>
    <fullName>APINamesOfChangedFieldsToRunLogic__c</fullName>
    <description>This Field stores Comma separated fields list to Set Due Daye</description>
    <label>API Names of Changed Fields To Run Logic</label>
    <type>TextArea</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/InheritDueDateFromOrderField__c.field-meta.xml
<CustomField>
    <fullName>InheritDueDateFromOrderField__c</fullName>
    <description>This Field is used to get Due Date from Order Field</description>
    <inlineHelpText>If you need to get Due Date from one of the Order Object Field , then please specify Order Object Fields API Name</inlineHelpText>
    <label>Inherit Due Date From Order Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/NoOfDaysToAddToInheritedDate__c.field-meta.xml
<CustomField>
    <fullName>NoOfDaysToAddToInheritedDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>NoOfDaysToAddToInheritedDate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/OrderConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderConditionsInfo__c</fullName>
    <description>Please provide Conditions in JSON format .For or conditions provide comma separated list against field name</description>
    <inlineHelpText>Please provide Conditions in JSON format .
For or conditions provide comma separated list against field name</inlineHelpText>
    <label>Order Conditions Info</label>
    <type>TextArea</type>
</CustomField>

objects/CarePlanTasksConfigs__mdt/fields/TasksConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>TasksConditionsInfo__c</fullName>
    <description>This field stores the prerequisite conditions for order update</description>
    <label>Task Conditions Info</label>
    <type>TextArea</type>
</CustomField>

classes/CarePlanTasksConfigsSelector.cls
public with sharing class CarePlanTasksConfigsSelector extends sflib_SObjectSelector
{
    public sObjectType getSobjectType()
    {
        return CarePlanTasksConfigs__mdt.SObjectType;
    }

    public List<SObjectField> getSObjectFieldList()
    {
        return new List<SObjectField>
        {
                CarePlanTasksConfigs__mdt.APINamesOfChangedFieldsToRunLogic__c,
                CarePlanTasksConfigs__mdt.InheritDueDateFromOrderField__c,
                CarePlanTasksConfigs__mdt.IsActive__c,
                CarePlanTasksConfigs__mdt.MasterLabel,
                CarePlanTasksConfigs__mdt.NoOfDaysToAddToInheritedDate__c,
                CarePlanTasksConfigs__mdt.OrderConditionsInfo__c,
                CarePlanTasksConfigs__mdt.TasksConditionsInfo__c
                
        };
    }

    public List<CarePlanTasksConfigs__mdt> selectAllActiveRules()
    {
        return (List<CarePlanTasksConfigs__mdt> ) Database.query(
                 newQueryFactory()
                    .setCondition(String.format('{0} = true',
                     new List<String>{CarePlanTasksConfigs__mdt.IsActive__c.getDescribe().getName()})).toSOQL());

    }

}