objects/OrderProcessingRule__mdt/OrderProcessingRule__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Order and its related tasks and goals to update through Entire Order Life Cycle</description>
    <label>Order Processing Rules</label>
    <pluralLabel>Order Processing Rules</pluralLabel>
</CustomObject>

objects/OrderProcessingRule__mdt/fields/APINamesOfChangedFieldsToRunLogic__c.field-meta.xml
<CustomField>
    <fullName>APINamesOfChangedFieldsToRunLogic__c</fullName>
    <label>API Names of Changed Fields To Run Logic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/CarePlanConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>CarePlanConditionsInfo__c</fullName>
    <label>Care Plan Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/CarePlanUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>CarePlanUpdateInfo__c</fullName>
    <label>Care Plan Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <label>Cryo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party</fullName>
                <default>true</default>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>Raritan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderProcessingRule__mdt/fields/GoalsConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>GoalsConditionsInfo__c</fullName>
    <description>This field is used to store prerequisite conditions for order update to check along with order record</description>
    <label>Goals Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/GoalsUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>GoalsUpdateInfo__c</fullName>
    <label>Goals Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/OrderConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderConditionsInfo__c</fullName>
    <description>Please provide Conditions in JSON format .
For or conditions provide comma separated list  against field name</description>
    <label>Order Conditions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/OrderUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderUpdateInfo__c</fullName>
    <label>Order Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/RuleOrder__c.field-meta.xml
<CustomField>
    <fullName>RuleOrder__c</fullName>
    <label>Rule Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/TaskConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>TaskConditionsInfo__c</fullName>
    <description>This field stores the prerequisite conditions for order update</description>
    <label>Task Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/TaskUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>TaskUpdateInfo__c</fullName>
    <label>Task Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/OrderProcessingRulesSelector.cls
public with sharing class OrderProcessingRulesSelector extends sflib_SObjectSelector
{
	public static List<OrderProcessingRule__mdt> orderProcessingRules
	{
		get
		{
			if (orderProcessingRules == null)
			{
				orderProcessingRules = ((OrderProcessingRulesSelector) Application.Selector.newInstance(getObjectType()))
						.selectAllActiveRules();
			}
			return orderProcessingRules;
		}
		private set;
	}
	public sObjectType getSobjectType()
	{
		return OrderProcessingRule__mdt.sObjectType;
	}
	public static sobjectType getObjectType()
	{
		return OrderProcessingRule__mdt.sObjectType;
	}
	public List<sObjectField> getSObjectFieldList()
	{
		return new List<sObjectField>
		{
				OrderProcessingRule__mdt.CarePlanConditionsInfo__c,
                OrderProcessingRule__mdt.CarePlanUpdateInfo__c,
                OrderProcessingRule__mdt.OrderConditionsInfo__c,
				OrderProcessingRule__mdt.CryoType__c,
                OrderProcessingRule__mdt.GoalsConditionsInfo__c,
				OrderProcessingRule__mdt.GoalsUpdateInfo__c,
				OrderProcessingRule__mdt.IsActive__c,
				OrderProcessingRule__mdt.ApiNamesOfChangedFieldsToRunLogic__c,
                OrderProcessingRule__mdt.MasterLabel,
				OrderProcessingRule__mdt.OrderUpdateInfo__c,
				OrderProcessingRule__mdt.RuleOrder__c,
				OrderProcessingRule__mdt.TaskUpdateInfo__c,
                OrderProcessingRule__mdt.TaskConditionsInfo__c
		};
	}

	public List<OrderProcessingRule__mdt> selectAllActiveRules()
	{
		return selectActive(true);
	}

	private List<OrderProcessingRule__mdt> selectActive(Boolean isActive)
	{
		fflib_QueryFactory queryFactory = newQueryFactory();
		queryFactory.setCondition(OrderProcessingRule__mdt.isActive__c.getDescribe().getName() + ' = :IsActive');
		return (List<OrderProcessingRule__mdt>) Database.query(queryFactory.toSOQL());
	}
	public override String getOrderBy()
	{
		return OrderProcessingRule__mdt.RuleOrder__c.getDescribe().getName() + ' DESC';
	}
	public Map<String, List<OrderProcessingRule__mdt>> getActiveRulesPerCryoType()
	{
		Map<String, List<OrderProcessingRule__mdt>> rulesPerCryoType = new Map<String, List<OrderProcessingRule__mdt>>();
		String cryoType;
		for (OrderProcessingRule__mdt rule : orderProcessingRules)
		{
			cryoType = '';
			cryoType = rule.CryoType__c.toLowerCase();
			if (rulesPerCryoType.containsKey(cryoType))
			{
				rulesPerCryoType.get(cryoType).add(rule);
			}
			else
			{
				rulesPerCryoType.put(cryoType, new List<OrderProcessingRule__mdt> {rule});
			}
		}
		return rulesPerCryoType;
	}
}