objects/OrderMilestonesUpdateRules__mdt/OrderMilestonesUpdateRules__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to capture business rules for mapping on order manufacturing statuses.</description>
    <label>Order Milestones Update Rules</label>
    <pluralLabel>Order Milestones Update Rules</pluralLabel>
</CustomObject>

objects/OrderMilestonesUpdateRules__mdt/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <description>Cryo type of the Order Milestone for which the rule applies</description>
    <label>CryoType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneName__c.field-meta.xml
<CustomField>
    <fullName>MilestoneName__c</fullName>
    <description>Name of the Order Milestone for which the rule applies</description>
    <label>Milestone Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneSource__c.field-meta.xml
<CustomField>
    <fullName>MilestoneSource__c</fullName>
    <description>This field describes the Milestone Source for the Order Milestone</description>
    <label>Milestone Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/MilestoneType__c.field-meta.xml
<CustomField>
    <fullName>MilestoneType__c</fullName>
    <description>Type of the Order Milestone for which the rule applies</description>
    <label>Milestone Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/OrderMilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderMilestoneStatus__c</fullName>
    <description>Manufacturing status of the Order Milestone.</description>
    <label>Order Milestone Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/SourceFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>SourceFieldAPIName__c</fullName>
    <description>API Name of the source field on the Order for the update related to the rule</description>
    <label>Source Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/TargetFieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldAPIName__c</fullName>
    <description>API Name of the target field on the Order for the update related to the rule</description>
    <label>Target Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/OrderMilestonesUpdateRules__mdt/fields/TargetStatusAPIName__c.field-meta.xml
<CustomField>
    <fullName>TargetStatusAPIName__c</fullName>
    <description>API Name of the target Status fields on the Order for the update related to the rule.</description>
    <label>Target Status API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

classes/OrderMilestonesUpdateRulesSelector.cls
public with sharing class OrderMilestonesUpdateRulesSelector extends fflib_SObjectSelector
{
    public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
            	OrderMilestonesUpdateRules__mdt.CryoType__c,
				OrderMilestonesUpdateRules__mdt.MilestoneName__c,
				OrderMilestonesUpdateRules__mdt.OrderMilestoneStatus__c,
				OrderMilestonesUpdateRules__mdt.MilestoneSource__c,
				OrderMilestonesUpdateRules__mdt.MilestoneType__c,
				OrderMilestonesUpdateRules__mdt.SourceFieldAPIName__c,
				OrderMilestonesUpdateRules__mdt.TargetFieldAPIName__c,
				OrderMilestonesUpdateRules__mdt.TargetStatusAPIName__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return OrderMilestonesUpdateRules__mdt.sObjectType;
	}

	public List<OrderMilestonesUpdateRules__mdt> selectAll()
	{
		return (List<OrderMilestonesUpdateRules__mdt>) Database.query(
				newQueryFactory()
						.toSOQL()
		);
	}
}