objects/KnowledgeDataCategory__mdt/KnowledgeDataCategory__mdt.object-meta.xml
<CustomObject>
    <description>Setting that describes the icon and page type associated to each data category for knowledge on community</description>
    <label>Knowledge Data Category</label>
    <pluralLabel>Knowledge Data Categories</pluralLabel>
</CustomObject>

objects/KnowledgeDataCategory__mdt/fields/IconName__c.field-meta.xml
<CustomField>
    <fullName>IconName__c</fullName>
    <description>Name of data category (topic)</description>
    <label>Icon Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/KnowledgeDataCategory__mdt/fields/PageType__c.field-meta.xml
<CustomField>
    <fullName>PageType__c</fullName>
    <description>Name of the page section where the data category is supposed to appear</description>
    <label>Page Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

classes/KnowledgeDataCategorySelector.cls
public with sharing class KnowledgeDataCategorySelector extends fflib_SObjectSelector{

    public List<Schema.SObjectField> getSObjectFieldList() 
    { 
        return new List<Schema.SObjectField>
		{
            KnowledgeDataCategory__mdt.label,
            KnowledgeDataCategory__mdt.IconName__c,
            KnowledgeDataCategory__mdt.PageType__c
		};
    }

    public SObjectType getSObjectType()
	{
		return KnowledgeDataCategory__mdt.SObjectType;
    }

    public List<KnowledgeDataCategory__mdt> selectAll()
	{      
        return (List<KnowledgeDataCategory__mdt>) 
                Database.query(
                    newQueryFactory()
                        .toSOQL()
                );
    }
}