objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/NotificationEngine__mdt/NotificationEngine__mdt.object-meta.xml
<CustomObject>
    <label>Notification Engine</label>
    <pluralLabel>Notification Engine</pluralLabel>
</CustomObject>

objects/PatientServiceEnrolleeTaskConfig__mdt/PatientServiceEnrolleeTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata contains information related to Task Record Creation values on Patient Service Enrolled Record Creation.</description>
    <label>Patient Service Enrollee Task Config</label>
    <pluralLabel>Patient Service Enrollee Task Config</pluralLabel>
</CustomObject>

objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientServicesEnrollee__c/fields/CaregiverFirstName__c.field-meta.xml
<CustomField>
    <fullName>CaregiverFirstName__c</fullName>
    <description>Caregiver's First Name</description>
    <label>Caregiver First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/CaregiverLastName__c.field-meta.xml
<CustomField>
    <fullName>CaregiverLastName__c</fullName>
    <description>Caregiver's Last Name</description>
    <label>Caregiver Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/CaregiverMiddleName__c.field-meta.xml
<CustomField>
    <fullName>CaregiverMiddleName__c</fullName>
    <description>Caregiver's Middle Name</description>
    <label>Caregiver Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/CarePlan__c.field-meta.xml
<CustomField>
    <fullName>CarePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Care Plan the patient is enrolled into</description>
    <label>Care Plan</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CarePlan</value>
        </filterItems>
        <filterItems>
            <field>Case.RecordTypeId</field>
            <operation>equals</operation>
            <value>CareGap</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Patient Services Enrollees</relationshipLabel>
    <relationshipName>Patient_Services_Enrollees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <description>Patient record of the patient requesting Patient Services</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Services Enrollees</relationshipLabel>
    <relationshipName>Patient_Services_Enrollees</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/PatientServicesStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServicesStatus__c</fullName>
    <description>Status of the Patient Services Record</description>
    <defaultValue>&apos;New Patient Services request&apos;</defaultValue>
    <label>Patient Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Patient Services Request</fullName>
                <default>true</default>
                <label>New Patient Services Request</label>
            </value>
            <value>
                <fullName>Request to Enroll Confirmed</fullName>
            </value>
            <value>
                <fullName>Patient Enrollment Form Received</fullName>
            </value>
            <value>
                <fullName>Missing Information in Form</fullName>
            </value>
            <value>
                <fullName>Processing Eligibility</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Enrolled in Service</fullName>
            </value>
            <value>
                <fullName>Opted out of Patient Services</fullName>
            </value>
            <value>
                <fullName>Request for Information Only</fullName>
            </value>
            <value>
                <fullName>Patient Services Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientServicesEnrolleesService.cls
public with sharing class PatientServicesEnrolleesService
{
	static final String ELIGIBLE = 'Eligible';
	static final String PATIENTSERVICEENROLLEEQUEUE = 'PatientServicesEnrolleeQueue';
	private static final String PatientServicesEnrolleeObject = 'PatientServicesEnrollee__c';

	public void createTasksForPatientServiceEnrollees(PatientServicesEnrollees patientServiceEnrolleees)
	{
		List<PatientServicesEnrollee__c> pseRecods = patientServiceEnrolleees.getRecords();

		if (pseRecods.isEmpty()) return;

		createTasksForPatientServiceEnrollees(pseRecods);
	}

	public void createTasksForPatientServiceEnrollees(List<PatientServicesEnrollee__c> pseRecords)
	{
		PatientServiceEnrolleeTaskConfigSelector pseSelector =
				(PatientServiceEnrolleeTaskConfigSelector) Application.Selector.newInstance(PatientServiceEnrolleeTaskConfig__mdt.SObjectType);

		Map<String, List<PatientServiceEnrolleeTaskConfig__mdt>> pseStatusAndTaskConfigInfo =
				pseSelector.selectActivePSEnrolleeTaskConfigInfoPerStatus();
		List<BusinessHours> businessHours = ((BusinessHoursSelector) Application.Selector.newInstance(BusinessHours.SObjectType)).
				selectBusinessHoursByName(Label.BusinessHoursNameForPatientServiceEnrolleeTasks);

		if (pseRecords.isEmpty() || businessHours.isEmpty() || pseStatusAndTaskConfigInfo.isEmpty()) return;

		List<Task> tasksToCreate = ((TasksService) Application.Service.newInstance(TasksService.Class)).
				getTasksForPatientServiceEnrollee(pseRecords, pseStatusAndTaskConfigInfo, businessHours[0].Id);

		try
		{
			if (tasksToCreate.isEmpty()) return;

			fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.newInstance(new ElevatedContextDML());
			unitOfWork.registerNew(tasksToCreate);
			unitOfWork.commitWork();
		}
		catch (Exception exceptionWhileTaskCreation)
		{
			Application.logEntry.error(exceptionWhileTaskCreation);
		}
	}

	public List<PatientServicesEnrollee__c> getPatientServiceEnrolleeRecordsForCarePlans(List<Case> carePlans)
	{
		Set<Id> patientIds = new Set<Id>();
		patientIds=sflib_ArrayUtils.pluckIdField(carePlans, Case.AccountId);
		Map<Id,Account> patientsInfo = new Map<Id,Account>();
		patientsInfo = ((AccountsSelector) Application.Selector.newInstance(Account.SObjectType)).selectById(patientIds).getById();
		Map<Id,Contact> patientIdNCareGiverInfo = new Map<Id,Contact>();

		if(!patientsInfo.isEmpty())
		{
			patientIdNCareGiverInfo = ((AccountsService) Application.Service.newInstance(AccountsService.class)).
					getCareGiverInformationPerPatient(sflib_ArrayUtils.pluckIdField(patientsInfo.values(),Account.PersonContactId));
		}

		List<PatientServicesEnrollee__c> patientServiceEnrollees = new List<PatientServicesEnrollee__c>();
		PatientServicesEnrollee__c pse = new PatientServicesEnrollee__c();
		Id ownerIdForPSERecords = getPatientServiceEnrolleeRecsOwnerId();

		for(Case carePlan : carePlans)
		{
			pse = new PatientServicesEnrollee__c(CarePlan__c = carePlan.Id, OwnerId = ownerIdForPSERecords);
			setPatientInfo(pse,patientsInfo.get(carePlan.AccountId));
			setCaregiverInfo(pse,patientIdNCareGiverInfo.get(carePlan.AccountId));
			patientServiceEnrollees.add(pse);
		}

		return patientServiceEnrollees;
	}
	void setPatientInfo(PatientServicesEnrollee__c pse,Account patientInfo)
	{
		if (patientInfo == null) return;

		pse.Patient__c = patientInfo.Id;
	}

	void setCaregiverInfo(PatientServicesEnrollee__c pse,Contact careGiver)
	{
		if (careGiver == null) return;

		pse.CaregiverFirstName__c = careGiver.FirstName;
		pse.CaregiverMiddleName__c = careGiver.MiddleName;
		pse.CaregiverLastName__c = careGiver.LastName;
	}

	Id getPatientServiceEnrolleeRecsOwnerId() {
		List<Group> pseQueue = ((GroupsSelector) Application.Selector.newInstance(Group.SObjectType))
									.selectQueuesByDeveloperName(
									new Set<String>{PATIENTSERVICEENROLLEEQUEUE	});
		return pseQueue.isEmpty() ? UserInfo.getUserId() : pseQueue[0].Id ;
	}

	public void sendPatientServicesLetters(Map<String,Set<Id>> pseIdsByEmailTemplateDeveloperNames)
	{
		List<EmailTemplate> emailTemplateList = ((EmailTemplatesSelector) Application.Selector.newInstance(EmailTemplate.SObjectType))
												.selectAll();
		
		EmailTemplates emailTemplates = (EmailTemplates) Application.Domain.newInstance(emailTemplateList);
		
		PatientServicesEnrolleesLetterService pseLetterService = new PatientServicesEnrolleesLetterService(
															emailTemplates.getEmailTemplatesByDeveloperName(), 
															pseIdsByEmailTemplateDeveloperNames);
		System.enqueueJob(pseLetterService);
	}

	public static String getPDFNameByDevelopername(String developerName)
	{
		String PDFName = '';

		if(developerName.equalsIgnoreCase(Label.PSETemplateForThePatientDevName))
		{
			PDFName = Label.PatientServicesEligibilityLetterPatient;
		}
		else if(developerName.equalsIgnoreCase(Label.PSETemplateForTheCARTCoordinatorDevName))
		{
			PDFName = Label.PatientServicesEligibilityLetterCARTCoordinator;
		}
		else if(developerName.equalsIgnoreCase(Label.PSITemplateForThePatientDevName))
		{
			PDFName = Label.PatientServicesIneligibilityLetterPatient;
		}
		else if(developerName.equalsIgnoreCase(Label.PSITemplateForTheCARTCoordinatorDevName))
		{
			PDFName = Label.PatientServicesIneligibilityLetterCARTCoordinator;
		}

		return PDFName += '.pdf';
	}

	public Id getPatientIdForEmailTemplate(Id pseId)
	{
		List<PatientServicesEnrollee__c> pseList = ((PatientServicesEnrolleesSelector) Application.Selector.newInstance(PatientServicesEnrollee__c.SObjectType))
				.selectById(new Set<Id>{pseId});

		return pseList[0].Patient__c;
	}

	public static Map<Id, PatientServicesEnrollee__c> fetchPatientServicesStatus(Set<Id> carePlanIds)
	{
		return new PatientServicesEnrollees(((PatientServicesEnrolleesSelector) Application.Selector.newInstance(PatientServicesEnrollee__c.SObjectType))
				.selectByCarePlanId(carePlanIds)).getPatientServicesByCareplanId();
	}

	public List<HealthCloudGA__ContactContactRelation__c>  getRelatedContactForEmailTemplate(Id patientId)
	{
		return ((ContactContactRelationSelector) Application.Selector.newInstance(HealthCloudGA__ContactContactRelation__c.SObjectType))
				.selectAssociatedContactsByPatientAndSitePersona(new Set<Id>{patientId},new Set<String>{Label.CARTCoordinator});
	}

	public List<AssociatedLocation>  getTreatmentSiteForEmailTemplate(List<HealthCloudGA__ContactContactRelation__c> contactContactRelationsList)
	{
		return ((AssociatedLocationsSelector) Application.Selector.newInstance(AssociatedLocation.SObjectType))
            	.getAddressesForSites(new Set<Id> {contactContactRelationsList[0].HealthCloudGA__Contact__r.AccountId});
	}

	public void grantAccessToPublicGroups(PatientServicesEnrollees pse)
	{
		fflib_ISObjectUnitOfWork elevatedGroupUnitOfWork = Application.UnitOfWork.newInstance(new ElevatedContextDML());
		grantAccessToRelatedPublicGroups(elevatedGroupUnitOfWork, pse.getRecords());
		elevatedGroupUnitOfWork.commitWork();
	}

	public void grantAccessToRelatedPublicGroups(fflib_ISObjectUnitOfWork uow, List<PatientServicesEnrollee__c> pseList)
    {
        Map<Id, Id> pseIdByAccountIdToCloneMap = new Map<Id, Id>();
        
        for(PatientServicesEnrollee__c pse : pseList)
        {
            pseIdByAccountIdToCloneMap.put(pse.Id, pse.Patient__c);
        }

        if(! pseIdByAccountIdToCloneMap.isEmpty())
        {
            new RecordsSharingService().cloneSharingSettings(uow, pseIdByAccountIdToCloneMap, AccountShare.SObjectType);
        }
	}
	
	public void fetchNotificationAlertDetails(List<PatientServicesEnrollee__c> changedRecords, List<PatientServicesEnrollee__c> existingRecords, Set<Schema.SObjectField> sObjectFieldSet)
	{
		List<String> fieldschema = new List<String>();
		for (Schema.SObjectField sfield : sObjectFieldSet)
		{
			fieldschema.add('' + sfield);
		}
		NotificationEngineSelector notificationEngineSelector = (NotificationEngineSelector) Application.Selector.newInstance(NotificationEngine__mdt.SObjectType);
		List<NotificationEngine__mdt> notificationEngineList = new List<NotificationEngine__mdt>();
		notificationEngineList =
				notificationEngineSelector.selectNotificationAlert(PatientServicesEnrolleeObject,
						fieldschema, existingRecords[0].PatientServicesStatus__c,
						changedRecords[0].PatientServicesStatus__c);

		if (notificationEngineList.isEmpty()) return ;

		List<HealthCloudGA__ContactContactRelation__c> cartCoordinatorContactRecord = getRelatedContactForEmailTemplate(changedRecords[0].Patient__c);

		UsersSelector usersSelectorInstance = (UsersSelector) Application.Selector.newInstance(User.SObjectType);
		List<User> cartCoordinatorList = usersSelectorInstance.selectByContactId(new Set<Id> {cartCoordinatorContactRecord[0].HealthCloudGA__Contact__c});
		if (cartCoordinatorList.isEmpty()) return ;

		AccountsSelector accountsSelectorInstance = (AccountsSelector) Application.Selector.newInstance(Account.SObjectType);
		List<Account> patientsList = (List<Account>) accountsSelectorInstance.selectById(new Set<Id> {changedRecords[0].Patient__c}).getRecords();

		createNotificationAlert(patientsList, notificationEngineList, cartCoordinatorList);
	}

	public void createNotificationAlert(List<Account> patientsList, List<NotificationEngine__mdt> notificationEngineList, List<User> cartCoordinatorList)
	{
		NotificationsService notificationsServiceInstance = (NotificationsService) Application.Service.newInstance(NotificationsService.class);
		notificationsServiceInstance.createNotificationRecords(patientsList, notificationEngineList, cartCoordinatorList, null);
	}
	
	private without sharing class ElevatedContextDML implements fflib_SObjectUnitOfWork.IDML
	{
		public void dmlInsert(List<SObject> objList)
		{
			if (objList != null && !objList.isEmpty())
			{
				Database.insert(objList, false);
			}
		}
		public void dmlUpdate(List<SObject> objList)
		{
			update objList;
		}
		public void dmlDelete(List<SObject> objList)
		{
			delete objList;
		}
		public void eventPublish(List<SObject> objList)
		{
			//not implemented
		}

		public void emptyRecycleBin(List<SObject> objList)
		{
			if (objList.isEmpty())
			{
				return;
			}
			Database.emptyRecycleBin(objList);
		}

	}

}