objects/PatientLandingPageStatusValue__mdt/PatientLandingPageStatusValue__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch Patient Treatment Milestone for patients-TCP list view table</description>
    <label>Patient Landing Page Status Value</label>
    <pluralLabel>Patient Landing Page Status Values</pluralLabel>
</CustomObject>

objects/PatientLandingPageStatusValue__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom field to store Active/Inactive value for Milestone Status field</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/CarePlanStatus__c.field-meta.xml
<CustomField>
    <fullName>CarePlanStatus__c</fullName>
    <description>Custom field to store Care Plan Status of the patient</description>
    <label>Care Plan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>Custom field to store Order Status of the patient</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientJourneyStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientJourneyStatus__c</fullName>
    <description>To display the patient status in the patient&apos;s highlight bar section- Patient journey screen</description>
    <label>Patient Journey Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <description>Custom field to store Patient Status of the patient</description>
    <label>Patient Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientTreatmentMilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientTreatmentMilestoneStatus__c</fullName>
    <description>Custom field to store Patient Treatment Milestone Status of the patient</description>
    <label>Patient Treatment Milestone Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/PatientTreatmentMilestonesSelector.cls
public with sharing class PatientTreatmentMilestonesSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				PatientLandingPageStatusValue__mdt.Active__c,
				PatientLandingPageStatusValue__mdt.CarePlanStatus__c,
				PatientLandingPageStatusValue__mdt.DeveloperName,
				PatientLandingPageStatusValue__mdt.Id,
				PatientLandingPageStatusValue__mdt.MasterLabel,
				PatientLandingPageStatusValue__mdt.OrderStatus__c,
				PatientLandingPageStatusValue__mdt.PatientJourneyStatus__c,
				PatientLandingPageStatusValue__mdt.PatientStatus__c,
				PatientLandingPageStatusValue__mdt.PatientTreatmentMilestoneStatus__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return PatientLandingPageStatusValue__mdt.SObjectType;
	}

	public List<PatientLandingPageStatusValue__mdt> selectAll()
	{
		return (List<PatientLandingPageStatusValue__mdt>) Database.query(
				newQueryFactory()
						.toSOQL()
		);
	}

}