objects/SiteProduct__c/SiteProduct__c.object-meta.xml
<CustomObject>
    <label>Site-Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>This Field Stores Product Name</description>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

classes/SiteProducts.cls
public with sharing class SiteProducts extends sflib_SObjectDomain
{
    public SiteProducts(List<SiteProduct__c> records)
    {
        super(records, SiteProduct__c.SObjectType);
    }

	private SiteProductsService Service
    {
        get
        {
            if (null == Service)
            {
                Service = (SiteProductsService) Application.Service.newInstance(SiteProductsService.class);
            }
            return Service;
        }
        set;
    }

    public Type getType()
	{
		return SiteProducts.class;
    }

	public override void onAfterInsert()
	{
		handleSiteProductsSharing();
	}

	public override void onAfterUpdate(Map<Id,SObject> existingRecords)
	{
		handleSiteProductsSharing();
	}

	public void handleSiteProductsSharing()
	{
		Service.shareSiteWithRelevantPublicGroups(selectSiteProductsWithProducts());
	}

	public SiteProducts selectSiteProductsWithProducts()
	{
		List<SObject> siteProducts =  matching(new sflib_Criteria().notEqualTo(SiteProduct__c.ProductName__c,null));
		return new SiteProducts(siteProducts);
	}

    public class Constructor implements fflib_SObjectDomain.IConstructable2
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new SiteProducts(sObjectList);
		}

		public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
		{
			return construct(sObjectList);
		}
	}

}