objects/Activity/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <description>Care Plan Name for the Activity</description>
    <formula>HealthCloudGA__CarePlanGoal__r.HealthCloudGA__CarePlan__r.CaseNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Care Plan ID</label>
    <type>Text</type>
</CustomField>

objects/Activity/fields/GoalName__c.field-meta.xml
<CustomField>
    <fullName>GoalName__c</fullName>
    <description>This field holds the value of related goal Name</description>
    <formula>HealthCloudGA__CarePlanGoal__r.Name</formula>
    <label>Goal Name</label>
    <type>Text</type>
</CustomField>

objects/HealthCloudGA__CarePlanGoal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to indicate the status of the Goal based on the status of the Tasks related to the Goal.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CryoSiteType__c.field-meta.xml
<CustomField>
    <fullName>CryoSiteType__c</fullName>
    <description>This field holds value of Cryo Site records type field value</description>
    <formula>TEXT(CryoSite__r.Type)</formula>
    <label>Cryo Site Type</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/OrderPlacementInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderPlacementInfo__c</fullName>
    <description>Hidden field to track order placement status.</description>
    <label>Order Placement Info</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Slot status of the order.</description>
    <inlineHelpText>If the Slot Status is &apos;Slot Rejected&apos; then please select a new Apheresis Pickup Date.</inlineHelpText>
    <label>Slot Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slot Requested</fullName>
            </value>
            <value>
                <fullName>Slot Confirmed</fullName>
            </value>
            <value>
                <fullName>Slot Blocked</fullName>
                <isActive>false</isActive>
                <label>Slot Blocked</label>
            </value>
            <value>
                <fullName>Slot Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderProcessingRule__mdt/OrderProcessingRule__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata is used to store Order and its related tasks and goals to update through Entire Order Life Cycle</description>
    <label>Order Processing Rules</label>
    <pluralLabel>Order Processing Rules</pluralLabel>
</CustomObject>

objects/OrderProcessingRule__mdt/fields/APINamesOfChangedFieldsToRunLogic__c.field-meta.xml
<CustomField>
    <fullName>APINamesOfChangedFieldsToRunLogic__c</fullName>
    <label>API Names of Changed Fields To Run Logic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/CarePlanConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>CarePlanConditionsInfo__c</fullName>
    <label>Care Plan Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/CarePlanUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>CarePlanUpdateInfo__c</fullName>
    <label>Care Plan Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/GoalsConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>GoalsConditionsInfo__c</fullName>
    <description>This field is used to store prerequisite conditions for order update to check along with order record</description>
    <label>Goals Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/GoalsUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>GoalsUpdateInfo__c</fullName>
    <label>Goals Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/OrderConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderConditionsInfo__c</fullName>
    <description>Please provide Conditions in JSON format .
For or conditions provide comma separated list  against field name</description>
    <label>Order Conditions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/OrderUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>OrderUpdateInfo__c</fullName>
    <label>Order Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/RuleOrder__c.field-meta.xml
<CustomField>
    <fullName>RuleOrder__c</fullName>
    <label>Rule Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/TaskConditionsInfo__c.field-meta.xml
<CustomField>
    <fullName>TaskConditionsInfo__c</fullName>
    <description>This field stores the prerequisite conditions for order update</description>
    <label>Task Conditions Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/OrderProcessingRule__mdt/fields/TaskUpdateInfo__c.field-meta.xml
<CustomField>
    <fullName>TaskUpdateInfo__c</fullName>
    <label>Task Update Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

classes/OrderGoalTaskSync.cls
public without sharing class OrderGoalTaskSync
{
	public static final String ORDERSTATUSNEW = 'New';
	public static final String ORDERSTATUSRESCHEDULED = 'Order Rescheduled';
	public static final String ORDERSTATUSSUBMITTED = 'Order Submitted';
	public static final String ORDERSTATUSVERIFIED = 'Order Verified';
	public static final String SLOT_CONFIRMED = 'Slot Confirmed';

	public List<Order__c> ordersToProcess = new List<Order__c>();
	public Map<String, List<OrderProcessingRule__mdt>> processingRulesPerCryoType;

	public OrderGoalTaskSync(List<Order__c> ordersToProcess)
	{
		this.ordersToProcess = ordersToProcess;
	}

	public OrderGoalTaskSync(Set<Id> orderIds)
	{
		this(((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType)).selectOrdersByOrderId(orderIds));
	}

	public Map<String, List<OrderProcessingRule__mdt>> getActiveOrderProcessingRulesPerCryoType()
	{
		Map<String, List<OrderProcessingRule__mdt>> teststst = new OrderProcessingRulesSelector().getActiveRulesPerCryoType();
		return teststst;
	}

	public void processOrderUpdateRules(fflib_ISObjectUnitOfWork uow, Map<Id, Case> carePlanInfo,
			Map<Id, Set<HealthCloudGA__CarePlanGoal__c>> carePlanIdNRelatedGoals,
			Map<Id, Set<String>> changedFieldsPerRec, Map<Id, Set<Task>> goalAndRelatedTasks)
	{
		try
		{
			OrderProcessingRule__mdt rule = new OrderProcessingRule__mdt();
			Map<String, List<OrderProcessingRule__mdt>> rulesPerCryoType = getActiveOrderProcessingRulesPerCryoType();
			String goalStatusField = HealthCloudGA__CarePlanGoal__c.status__C.getDescribe().getName();
			String taskStatusField = Task.Status.getDescribe().getName();
			Set<Id> relevantGoalIdsForTaskUpdate = new Set<Id>();

			for (Order__c order : ordersToProcess)
			{
				if (String.isBlank(order.CryoSiteType__c) || !rulesPerCryoType.containsKey(order.CryoSiteType__c.toLowerCase()))
				{
					continue;
				}

				rule = getSatisFieldRuleInfo(carePlanInfo.get(order.CarePlanID__c), order, rulesPerCryoType.get(order.CryoSiteType__c.toLowerCase()), changedFieldsPerRec.get(order.Id),
						carePlanIdNRelatedGoals.get(order.CarePlanID__c), carePlanInfo.get(order.CarePlanID__c).Tasks);

				if (rule != null && rule.MasterLabel != null)
				{
					Application.logEntry.debug('Satisfied Rule Number :' + rule.RuleOrder__c + ' and Rule Info : ' + JSON.serialize(rule));
					processOrderUpdate(order, rule);
					processCarePlanUpdate(uow, carePlanInfo.get(order.CarePlanID__c), rule.CarePlanUpdateInfo__c);
					processRelevantGoalUpdateNPassGoalIds(uow, rule.GoalsUpdateInfo__c, carePlanIdNRelatedGoals.get(order.CarePlanID__c), goalStatusField);
					processRelevantTasksUpdate(uow, rule.TaskUpdateInfo__c, carePlanInfo.get(order.CarePlanID__c).Tasks, taskStatusField);
				}
			}
			processOrdersIfNontriggerContext(uow, ordersToProcess);
		}
		catch (Exception excp)
		{
			Application.logEntry.error(excp);
		}
	}

	private void processOrdersIfNontriggerContext(fflib_ISObjectUnitOfWork uow,List<SObject> ordersToProcess)
	{
		if (!Trigger.isExecuting)
		{
			uow.registerDirty(ordersToProcess);
			fflib_SObjectDomain.getTriggerEvent(Orders.class).disableAll();
		}
	}

	public void processRelevantTasksUpdate(fflib_ISObjectUnitOfWork uow, String taskStatusUpdateInfo, List<Task> activities,String fieldName)
	{
		if (String.isNotBlank(taskStatusUpdateInfo) && !activities.isEmpty())
		{
			List<TaskUpdateNode> tasksStatusUpdateInfo = (List<TaskUpdateNode>) JSON.deserialize(taskStatusUpdateInfo, List<TaskUpdateNode>.class);
			String goalNameOnTask = Task.GoalName__c.getDescribe().getName();
			for (TaskUpdateNode taskUpdateInfo : tasksStatusUpdateInfo)
			{
				for (Task activity : activities)
				{
					if (taskUpdateInfo.taskSubject.equalsIgnoreCase(activity.Subject) && verifyTaskRelatedGoalName(activity, taskUpdateInfo.goalNameForTasksFilter, goalNameOnTask))
					{
						uow.registerDirty(processSobjectUpdate(activity, fieldName, taskUpdateInfo.taskStatusToSet));
					}
				}
			}
		}
	}

	public Set<Id> processRelevantGoalUpdateNPassGoalIds(fflib_ISObjectUnitOfWork uow, String goalStatusUpdateInfo, Set<HealthCloudGA__CarePlanGoal__c> goals, String fieldName)
	{
		Set<Id> relevantGoalIdsForTaskUpdate = new Set<Id>();
		if (String.isNotBlank(goalStatusUpdateInfo) && !goals.isEmpty())
		{
			List<GoalUpdateNode> goalsStatusUpdateInfo = (List<GoalUpdateNode>) JSON.deserialize(goalStatusUpdateInfo, List<GoalUpdateNode>.class);
			for (GoalUpdateNode goalInUpdatefo : goalsStatusUpdateInfo)
			{
				for (HealthCloudGA__CarePlanGoal__c goal : goals)
				{
					if (goalInUpdatefo.goalName.equalsIgnoreCase(goal.Name))
					{
						uow.registerDirty(processSobjectUpdate(goal, fieldName, goalInUpdatefo.goalStatusToSet));
						relevantGoalIdsForTaskUpdate.add(goal.Id);
					}
				}
			}
		}
		return relevantGoalIdsForTaskUpdate;
	}

	private void processCarePlanUpdate(fflib_ISObjectUnitOfWork uow,SObject record, String fieldUpdateInfo)
	{
		if (String.isNotBlank(fieldUpdateInfo))
		{
			List<FieldUpdateNode> fieldsUpdateInfo = (List<FieldUpdateNode>) JSON.deserialize(fieldUpdateInfo, List<FieldUpdateNode>.class);
			for (FieldUpdateNode fieldInfoToSet : fieldsUpdateInfo)
			{
				record.put(fieldInfoToSet.fieldName, fieldInfoToSet.valueToSet);
				uow.registerDirty(record);
			}
		}
	}

	private SObject processSobjectUpdate(SObject record, String fieldName, String value)
	{
		record.put(fieldName, value);
		return record;
	}

	public Order__c processOrderUpdate(Order__c order, OrderProcessingRule__mdt rule)
	{
		setOrderStatusWhenSlotIsConfirmed(order);
		if (String.isNotBlank(rule.OrderUpdateInfo__c))
		{
			List<FieldUpdateNode> fieldsUpdateInfo = (List<FieldUpdateNode>) JSON.deserialize(rule.OrderUpdateInfo__c, List<FieldUpdateNode>.class);
			for (FieldUpdateNode fieldInfoToSet : fieldsUpdateInfo)
			{
				order.put(fieldInfoToSet.fieldName, fieldInfoToSet.valueToSet);
			}
		}
		return order;
	}

	public void setOrderStatusWhenSlotIsConfirmed(Order__c order)
	{
		Set<String> orderStatusSet = new Set<String>{ORDERSTATUSNEW,ORDERSTATUSVERIFIED,ORDERSTATUSSUBMITTED,ORDERSTATUSRESCHEDULED};
		if(SLOT_CONFIRMED.equals(order.SlotStatus__c)
				&& String.isNotBlank(order.OrderPlacementInfo__c)
				&& orderStatusSet.contains(order.OrderStatus__c))
		{
			order.OrderStatus__c = order.OrderPlacementInfo__c;
		}
	}

	private OrderProcessingRule__mdt getSatisFieldRuleInfo(Case carePlan, Order__c order, List<OrderProcessingRule__mdt> rules, Set<String> changedFields,
			Set<HealthCloudGA__CarePlanGoal__c> goals, List<Task> tasks)
	{
		OrderProcessingRule__mdt satisFieldRule;
		List<HealthCloudGA__CarePlanGoal__c> goalsList = new List<HealthCloudGA__CarePlanGoal__c>(goals);
		for (OrderProcessingRule__mdt rule : rules)
		{
			if (isRecSatisfyingTheRuleCondition(order, rule.OrderConditionsInfo__c) && isRecSatisfyingTheRuleCondition(carePlan, rule.CarePlanConditionsInfo__c) &&
					checkForChangedFieldsEligibility(rule.APINamesOfChangedFieldsToRunLogic__c, changedFields) &&
					areRecsSatisfyingRuleCondition(getAppropriateRecsToCheck(goalsList, rule.GoalsConditionsInfo__c, StaticConstants.NAMELABEL), rule.GoalsConditionsInfo__c)
					&& areRecsSatisfyingRuleCondition(getAppropriateRecsToCheck(tasks, rule.TaskConditionsInfo__c, StaticConstants.SUBJECTLABEL), rule.TaskConditionsInfo__c))
			{
				satisFieldRule = rule;
			}
		}

		return satisFieldRule;
	}

	private Boolean compareWhetherValuesAreEqual(String valueToCompare, String valueToCompareAganist)
	{
		return String.isBlank(valueToCompareAganist) || (String.isNotBlank(valueToCompare) && valueToCompareAganist.split(StaticConstants.COMMA).contains(valueToCompare));
	}

	private Boolean checkForChangedFieldsEligibility(String fieldsListToCheck, Set<String> changedFieldsCollection)
	{
		if (String.isNotBlank(fieldsListToCheck) && (changedFieldsCollection == null || changedFieldsCollection.isEmpty()))
		{
			return false;
		}
		List<String> fieldsListToValidate = String.isNotBlank(fieldsListToCheck) ? fieldsListToCheck.split(StaticConstants.COMMA)
				: new List<String>();
		for (String fieldName : fieldsListToValidate)
		{
			if (!changedFieldsCollection.contains(fieldName))
			{
				return false;
			}
		}
		return true;
	}

	private Boolean areRecsSatisfyingRuleCondition(List<SObject> records, String conditionsInfo)
	{
		Boolean isSatisfied = true;
		for (SObject record : records)
		{
			if (!isRecSatisfyingTheRuleCondition(record, conditionsInfo))
			{
				isSatisfied = false;
				break;
			}
		}
		return isSatisfied;
	}

	private Boolean isRecSatisfyingTheRuleCondition(SObject record, String conditionInfo)
	{
		try
		{
			Boolean isSatisfied = true;
			String goalNameOnTask = Task.GoalName__c.getDescribe().getName();
			if (String.isNotBlank(conditionInfo) && record != null)
			{
				List<ConditionsNode> conditions = (List<ConditionsNode>) JSON.deserialize(conditionInfo, List<ConditionsNode>.class);
				for (ConditionsNode condition : conditions)
				{
					if (!compareWhetherValuesAreEqual((String) record.get(condition.fieldName), condition.valueToCompare))
					{
						isSatisfied = false;
						break;
					}
				}
			}
			return isSatisfied;
		}
		catch (Exception excp)
		{
			Application.logEntry.error(excp);
			return false;
		}
	}

	private Boolean verifyTaskRelatedGoalName(SObject record, String goalNameFilter, String goalNameOnTask)
	{
		return String.isBlank(goalNameFilter) || compareWhetherValuesAreEqual((String) record.get(goalNameOnTask), goalNameFilter);
	}

	private List<sObject> getAppropriateRecsToCheck(List<SObject> records, String conditionInfo, String fieldNameToFilter)
	{
		List<sObject> targetRecords = new List<sObject>();
		SObject targetRecord;
		String taskObjectGoalNameField = Task.GoalName__c.getDescribe().getName();
		if (String.isNotBlank(conditionInfo))
		{
			List<ConditionsNode> conditions = (List<ConditionsNode>) JSON.deserialize(conditionInfo, List<ConditionsNode>.class);

			for (ConditionsNode condition : conditions)
			{
				for (SObject record : records)
				{
					if (validateGoalNameIfTaskSObject(record,condition.goalNameOrTaskSub,taskObjectGoalNameField) &&
							isAppropriateRecToCheck(condition.goalNameOrTaskSub, record, fieldNameToFilter))
					{
						targetRecords.add(record);
					}
				}
			}
		}
		return targetRecords;
	}

	private Boolean validateGoalNameIfTaskSObject(SObject record,String goalNameForTasksFilter,String taskObjectGoalNameField)
	{
		return Task.SObjectType != record.Id.getSObjectType() ||
				compareWhetherValuesAreEqual(goalNameForTasksFilter,(String) record.get(taskObjectGoalNameField));
	}

	private Boolean isAppropriateRecToCheck(String recName, SObject record, String fieldNameToFilter)
	{
		return String.isBlank(recName) || (record.get(fieldNameToFilter) != null &&
				String.valueOf(record.get(fieldNameToFilter)).equalsIgnoreCase(recName));
	}


	class ConditionsNode
	{
		public String goalNameOrTaskSub { get; set; }
		String fieldName { get; set; }
		String valueToCompare { get; set; }
		public String goalNameForTasksFilter { get; set; }
	}

	class FieldUpdateNode
	{
		String fieldName { get; set; }
		String valueToSet { get; set; }
	}

	class GoalUpdateNode
	{
		String goalName { get; set; }
		String goalStatusToSet { get; set; }
	}

	class TaskUpdateNode
	{
		String taskSubject { get; set; }
		String taskStatusToSet { get; set; }
		String goalNameForTasksFilter { get; set; }
	}
}