objects/PatientServiceEnrolleeTaskConfig__mdt/PatientServiceEnrolleeTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata contains information related to Task Record Creation values on Patient Service Enrolled Record Creation.</description>
    <label>Patient Service Enrollee Task Config</label>
    <pluralLabel>Patient Service Enrollee Task Config</pluralLabel>
</CustomObject>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/DaysToReachDueDate__c.field-meta.xml
<CustomField>
    <fullName>DaysToReachDueDate__c</fullName>
    <label>Days To Reach Due Date</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/PatientServiceEnrolleeStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServiceEnrolleeStatus__c</fullName>
    <label>Patient Service Enrollee Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <defaultValue>&apos;Normal&apos;</defaultValue>
    <label>Task Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <label>Task Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <label>Task Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <description>This Fields Holds Value to map to Task Type Field on Task Object</description>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
                <default>true</default>
                <label>Automated</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientServiceEnrolleeTaskConfigSelector.cls
public inherited sharing class PatientServiceEnrolleeTaskConfigSelector extends sflib_SObjectSelector
{
	public static List<PatientServiceEnrolleeTaskConfig__mdt> patientServiceEnrolleeTaskConfigs
	{
		get
		{
			if (patientServiceEnrolleeTaskConfigs == null)
			{
				patientServiceEnrolleeTaskConfigs = ((PatientServiceEnrolleeTaskConfigSelector) Application.Selector.newInstance(getObjectType()))
						.getActivePatientServiceEnrolleeTaskConfigInfo();
			}
			return patientServiceEnrolleeTaskConfigs;
		}
		private set;
	}

	Public SObjectType getSObjectType()
	{
		return PatientServiceEnrolleeTaskConfig__mdt.SobjectType;
	}

	public static sobjectType getObjectType()
	{
		return PatientServiceEnrolleeTaskConfig__mdt.sObjectType;
	}

	Public List<SObjectField> getSObjectFieldList()
	{
		return new List<SObjectField>
		{
				PatientServiceEnrolleeTaskConfig__mdt.IsActive__c,
				PatientServiceEnrolleeTaskConfig__mdt.DaysToReachDueDate__c,
				PatientServiceEnrolleeTaskConfig__mdt.PatientServiceEnrolleeStatus__c,
				PatientServiceEnrolleeTaskConfig__mdt.TaskPriority__c,
				PatientServiceEnrolleeTaskConfig__mdt.TaskStatus__c,
				PatientServiceEnrolleeTaskConfig__mdt.TaskSubject__c,
                PatientServiceEnrolleeTaskConfig__mdt.TaskType__c
		};
	}

	Public List<PatientServiceEnrolleeTaskConfig__mdt> getActivePatientServiceEnrolleeTaskConfigInfo()
	{
		return selectPatientServiceEnrolleeTaskConfigInfo(true);
	}

	Public List<PatientServiceEnrolleeTaskConfig__mdt> selectPatientServiceEnrolleeTaskConfigInfo(Boolean isActive)
	{

		fflib_QueryFactory queryFactory = newQueryFactory();
		queryFactory.setCondition(PatientServiceEnrolleeTaskConfig__mdt.isActive__c.getDescribe().getName() +
				' = :IsActive');
		return (List<PatientServiceEnrolleeTaskConfig__mdt>) Database.query(queryFactory.toSOQL());
	}

	public Map<String, List<PatientServiceEnrolleeTaskConfig__mdt>> selectActivePSEnrolleeTaskConfigInfoPerStatus()
	{
		Map<String, List<PatientServiceEnrolleeTaskConfig__mdt>> pseTaskConfigs = new Map<String, List<PatientServiceEnrolleeTaskConfig__mdt>>();
		for (PatientServiceEnrolleeTaskConfig__mdt pseTaskConfig : patientServiceEnrolleeTaskConfigs)
		{
			if (pseTaskConfigs.containsKey(pseTaskConfig.PatientServiceEnrolleeStatus__c))
			{
				pseTaskConfigs.get(pseTaskConfig.PatientServiceEnrolleeStatus__c).add(pseTaskConfig);
			}
			else
			{
				pseTaskConfigs.put(pseTaskConfig.PatientServiceEnrolleeStatus__c, new List<PatientServiceEnrolleeTaskConfig__mdt> {pseTaskConfig});
			}
		}
		return pseTaskConfigs;
	}

}