objects/Account/fields/AccountIdentifier__c.field-meta.xml
<CustomField>
    <fullName>AccountIdentifier__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Unique identifier for Institute, Site or Patient that is system generated.</description>
    <displayFormat>ACT{0000}</displayFormat>
    <label>Account Identifier</label>
    <type>AutoNumber</type>
</CustomField>

objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>This field is used to store treatment site customer code from SAP</description>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/ERPSiteID__c.field-meta.xml
<CustomField>
    <fullName>ERPSiteID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan.</description>
    <externalId>true</externalId>
    <inlineHelpText>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan</inlineHelpText>
    <label>ERP Site ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Location/fields/AddressLine1__c.field-meta.xml
<CustomField>
    <fullName>AddressLine1__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/AddressLine2__c.field-meta.xml
<CustomField>
    <fullName>AddressLine2__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HealthCloudGA__Countries</valueSetName>
    </valueSet>
</CustomField>

objects/Location/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
</CustomField>

objects/Location/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/CryoSiteType__c.field-meta.xml
<CustomField>
    <fullName>CryoSiteType__c</fullName>
    <description>This field holds value of Cryo Site records type field value</description>
    <formula>TEXT(CryoSite__r.Type)</formula>
    <label>Cryo Site Type</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/ProjectedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectedDeliveryDate__c</fullName>
    <description>This field is used to store Apheresis Projected Delivery Date From Anaplan</description>
    <label>Projected Delivery Date From Anaplan</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/SDPO__c.field-meta.xml
<CustomField>
    <fullName>SDPO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>SD PO# integrated with SD.</description>
    <label>SD PO#</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/SitePO__c.field-meta.xml
<CustomField>
    <fullName>SitePO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Site PO# from TCP.</description>
    <label>Site PO#</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/TreatmentSite__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Treatment Site recorded on Care Plan.</description>
    <label>Treatment Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Treatment Site)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product2/fields/ApheresisMaterialCodeFresh__c.field-meta.xml
<CustomField>
    <fullName>ApheresisMaterialCodeFresh__c</fullName>
    <description>If the cryo type is local, then the fresh apheresis cell material code will be captured</description>
    <label>Apheresis Material Code Fresh</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/ApheresisMaterialCodeFrozen__c.field-meta.xml
<CustomField>
    <fullName>ApheresisMaterialCodeFrozen__c</fullName>
    <description>If the cryo type is central/raritan, then the cells will be cryo-preserved and their material no will be captured</description>
    <label>Apheresis Material Code Frozen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/MaterialNoFG__c.field-meta.xml
<CustomField>
    <fullName>MaterialNoFG__c</fullName>
    <description>The field is used to track the material no for the finished good</description>
    <label>Material No FG</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/QuantityAphersis__c.field-meta.xml
<CustomField>
    <fullName>QuantityAphersis__c</fullName>
    <description>The quantity of the Apheresed cells will be captured here</description>
    <label>Quantity Aphersis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/QuantityFG__c.field-meta.xml
<CustomField>
    <fullName>QuantityFG__c</fullName>
    <description>The quantity of the finished good will be captured here</description>
    <label>Quantity FG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/SalesOrderType__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderType__c</fullName>
    <description>Defines the types of sales order like verified sales order or new sales order etc.</description>
    <label>Sales Order Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/UOMApheresis__c.field-meta.xml
<CustomField>
    <fullName>UOMApheresis__c</fullName>
    <description>Defines the unit of measurement for apheresed cells</description>
    <label>UOM Apheresis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/UOMFG__c.field-meta.xml
<CustomField>
    <fullName>UOMFG__c</fullName>
    <description>Defines the unit output for the manufactured cells</description>
    <label>UOM Finished Goods</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SiteProduct__c/SiteProduct__c.object-meta.xml
<CustomObject>
    <label>Site-Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Corresponds to the product name</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Site-Products</relationshipLabel>
    <relationshipName>Site_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteProduct__c/fields/SpecialtyDistributor__c.field-meta.xml
<CustomField>
    <fullName>SpecialtyDistributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field lookup to the SD account to be associated with the product</description>
    <label>Specialty Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SpecialtyDistributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specialty Distributor</relationshipLabel>
    <relationshipName>Site_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/SalesOrderUpdateServiceHelper.cls
public with sharing class SalesOrderUpdateServiceHelper implements ICalloutServiceHelper
{

	static final String EMPTYSTRING ='';

	Public Map<Id, String> getCalloutInputRequestBody(Set<Id> orderIds)
	{
		Map<Id, String> orderIdNInputBody = new Map<Id, String>();
		Map<Id, Account> spIdNSDInfo = new Map<Id, Account>();

		List<Order__c> orders = ((OrdersSelector) Application.Selector
				                .newInstance(Order__c.SObjectType))
				                .selectOrdersByOrderId(orderIds);

		Set<Id> treatmentSiteIds = sflib_ArrayUtils.pluckIdField(orders, Order__c.TreatmentSite__c);

		if (treatmentSiteIds.isEmpty()) return orderIdNInputBody;


		Map<Id, Account> treatmentSitesInfo = ((AccountsSelector) Application.Selector.newInstance
				(Account.SObjectType)).selectById(treatmentSiteIds).getById();

		Map<Id, AssociatedLocation> accountIdNLocationInfo = ((AssociatedLocationsService) Application.service
                                                             .newInstance(AssociatedLocationsService.class))
				                                             .getAccountsAddressInfo(treatmentSiteIds);

		SiteProductsService spService = (SiteProductsService) Application.Service.newInstance(SiteProductsService.class);

		Map<Id, SiteProduct__c> siteIdNsiteProductInfo = spService.getSiteIdNsiteProductInfo(treatmentSiteIds);

		SalesOrderUpdateServiceInput input = new SalesOrderUpdateServiceInput();
		for (Order__c order : orders)
		{
			if (order.TreatmentSite__c == null) continue;
			input = new SalesOrderUpdateServiceInput();
			setOrderInfo(input, order);
			input.CARTShipToAccount = treatmentSitesInfo.get(order.TreatmentSite__c).AccountIdentifier__c;
			input.shipToCode = nullCheckStringAndPassBlankIfEmpty(treatmentSitesInfo.get(order.TreatmentSite__c).CustomerCode__c);
			input.soldToCode = getSoldToCode(siteIdNsiteProductInfo?.get(order.TreatmentSite__c));
			input.shipToAddress = getShipToAddress(accountIdNLocationInfo?.get(order.TreatmentSite__c));
			input.atlasVendorCode = nullCheckStringAndPassBlankIfEmpty(treatmentSitesInfo?.get(order.TreatmentSite__c)?.ERPSiteID__c);
			setProductInfo(input, siteIdNsiteProductInfo.get(order.TreatmentSite__c), order.CryoSiteType__c);
			orderIdNInputBody.put(order.Id, JSON.serialize((SalesOrderUpdateServiceInput) input));
		}

		return orderIdNInputBody;
	}

	String getSoldToCode(SiteProduct__c siteProduct)
	{
		return nullCheckStringAndPassBlankIfEmpty(siteProduct?.SpecialtyDistributor__r?.ERPSiteID__c);
	}

	SalesOrderUpdateServiceInput.shipToAddress getShipToAddress(Schema.AssociatedLocation treatmentSiteLocation)
	{
		if (treatmentSiteLocation == null || treatmentSiteLocation.Location == null) return null;

		SalesOrderUpdateServiceInput.shipToAddress shipToAddress = new SalesOrderUpdateServiceInput.shipToAddress();
		shipToAddress.shipToName = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.ParentRecord.Name);
		shipToAddress.city = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.City__c);
		shipToAddress.zipCodeNo = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.PostalCode__c);
		shipToAddress.addressLine2 = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.AddressLine2__c) ;
		shipToAddress.stateRegion = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.State__c);
		shipToAddress.addressLine1 = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.AddressLine1__c);
		shipToAddress.addressLine3 = '';
		shipToAddress.addressLine4 = '';
		shipToAddress.country = nullCheckStringAndPassBlankIfEmpty(treatmentSiteLocation.Location.Country__c);

		return shipToAddress;
	}

	String nullCheckStringAndPassBlankIfEmpty(String sourceValue)
	{
		return String.isNotBlank(sourceValue) ? sourceValue : EMPTYSTRING;
	}

	void setProductInfo(SalesOrderUpdateServiceInput input, SiteProduct__c siteProduct, String cryoType)
	{
		if (siteProduct == null || siteProduct.Product__r == null) return ;

		SalesOrderUpdateServiceInput.apheresis apheresis = new SalesOrderUpdateServiceInput.apheresis();

		input.salesOrderType = siteProduct.Product__r.SalesOrderType__c;
		apheresis.UOM = siteProduct.Product__r.UOMApheresis__c;
		apheresis.quantity = siteProduct.Product__r.QuantityAphersis__c;
		apheresis.material = StaticConstants.cryoTypeRaritan.equalsIgnoreCase(cryoType) ?
				siteProduct.Product__r.ApheresisMaterialCodeFresh__c :
				siteProduct.Product__r.ApheresisMaterialCodeFrozen__c;
		input.apheresis = apheresis;

		input.finishedGoods = new SalesOrderUpdateServiceInput.finishedGoods(
				siteProduct.Product__r.MaterialNoFG__c,
				siteProduct.Product__r.QuantityFG__c,
				siteProduct.Product__r.UOMFG__c);

	}

	void setOrderInfo(SalesOrderUpdateServiceInput input, Order__c order)
	{
		input.SDPONo = nullCheckStringAndPassBlankIfEmpty(order.SDPO__c);
		input.QTCPONo = nullCheckStringAndPassBlankIfEmpty(order.SitePO__c);
		input.projectedDeliveryDueDate = string.valueOf(order.ProjectedDeliveryDate__c);
		input.CARTOrderId = order.CartOrderId__c;
	}
}