objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Look up to account for use in patient card configuration</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Contact/fields/SitePersona__c.field-meta.xml
<CustomField>
    <fullName>SitePersona__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>List of personas at the Treatment Center Portal.</description>
    <label>Site Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAR-T Coordinator</fullName>
            </value>
            <value>
                <fullName>Pharmacist</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCloudGA__ContactContactRelation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Contacts</relationshipLabel>
    <relationshipName>Associated_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientServicesEnrollee__c/fields/DateEligibilityCheckPerformed__c.field-meta.xml
<CustomField>
    <fullName>DateEligibilityCheckPerformed__c</fullName>
    <description>Date when the eligibility check was performed by the PAS Agent</description>
    <label>Date Eligibility Check Performed</label>
    <type>Date</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/DistanceMileage__c.field-meta.xml
<CustomField>
    <fullName>DistanceMileage__c</fullName>
    <description>Distance between the Patient's address and Treatment Site address in miles</description>
    <label>Distance - Mileage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/DistanceTime__c.field-meta.xml
<CustomField>
    <fullName>DistanceTime__c</fullName>
    <description>Distance between the Patient's address and Treatment Site address in hours and minutes</description>
    <label>Distance - Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/PatientServicesEnrollee__c/fields/IncomeEligibility__c.field-meta.xml
<CustomField>
    <fullName>IncomeEligibility__c</fullName>
    <description>Eligibility based on Income</description>
    <defaultValue>&apos;Eligibility check not performed&apos;</defaultValue>
    <label>Income Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility check not performed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not-eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/InsuranceEligibility__c.field-meta.xml
<CustomField>
    <fullName>InsuranceEligibility__c</fullName>
    <description>Eligibility based on Insurance	</description>
    <defaultValue>&apos;Eligibility check not performed&apos;</defaultValue>
    <label>Insurance Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility check not performed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not-eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/LodgingEligibility__c.field-meta.xml
<CustomField>
    <fullName>LodgingEligibility__c</fullName>
    <description>Eligibility based on lodging</description>
    <defaultValue>&apos;Eligibility check not performed&apos;</defaultValue>
    <label>Lodging Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility check not performed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not-eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/LodgingSupport__c.field-meta.xml
<CustomField>
    <fullName>LodgingSupport__c</fullName>
    <description>Lodging support provided by the site</description>
    <defaultValue>&apos;No&apos;</defaultValue>
    <label>Lodging Support</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Yes - but no availability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/MileageEligibility__c.field-meta.xml
<CustomField>
    <fullName>MileageEligibility__c</fullName>
    <description>Eligibility based on Mileage</description>
    <defaultValue>&apos;Eligibility check not performed&apos;</defaultValue>
    <label>Mileage  Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility check not performed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not-eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/NonEmergencyMedicalTravel__c.field-meta.xml
<CustomField>
    <fullName>NonEmergencyMedicalTravel__c</fullName>
    <description>Confirmation whether patient is eligible for non-emergency medical travel</description>
    <defaultValue>&apos;No&apos;</defaultValue>
    <label>Non-emergency Medical Travel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/PatientServices__c.field-meta.xml
<CustomField>
    <fullName>PatientServices__c</fullName>
    <description>List of Patient Services available</description>
    <defaultValue>&apos;Travel (Ground and Air transport) Services​&apos;</defaultValue>
    <label>Patient Services</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Travel (Ground and Air transport) Services​</fullName>
            </value>
            <value>
                <fullName>Accommodation Services​</fullName>
            </value>
            <value>
                <fullName>Meals Services</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/PatientServicesStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServicesStatus__c</fullName>
    <description>Status of the Patient Services Record</description>
    <defaultValue>&apos;New Patient Services request&apos;</defaultValue>
    <label>Patient Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Patient Services Request</fullName>
                <default>true</default>
                <label>New Patient Services Request</label>
            </value>
            <value>
                <fullName>Request to Enroll Confirmed</fullName>
            </value>
            <value>
                <fullName>Patient Enrollment Form Received</fullName>
            </value>
            <value>
                <fullName>Missing Information in Form</fullName>
            </value>
            <value>
                <fullName>Processing Eligibility</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Enrolled in Service</fullName>
            </value>
            <value>
                <fullName>Opted out of Patient Services</fullName>
            </value>
            <value>
                <fullName>Request for Information Only</fullName>
            </value>
            <value>
                <fullName>Patient Services Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/fields/TimeEligibility__c.field-meta.xml
<CustomField>
    <fullName>TimeEligibility__c</fullName>
    <description>Eligibility based on time</description>
    <defaultValue>&apos;Eligibility check not performed&apos;</defaultValue>
    <label>Time Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eligibility check not performed</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Not-eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientServicesEnrolleesServiceTest.cls
@isTest(seeAlldata=false)
public with sharing class PatientServicesEnrolleesServiceTest 
{
    public static final String BILLING_STREET = 'Street 2';
    public static final String BILLING_CITY = 'City 2';
    public static final String BILLING_POSTAL_CODE = '76112';
    public static final String BILLING_COUNTRY = 'Mexico';
    public static final String CARE_PROGRAM = 'Test Care Program';
    public static final String LOCATION = 'Raritan Manufacturing Pickup';
    public static final String NEW_PATIENT_SERVICES_REQUEST = 'New Patient Services Request';
    public static final String REQUEST_TO_ENROLL_CONFIRMED = 'Request to Enroll Confirmed';
    public static final String PATIENT_ENROLLMENT_FORM_RECEIVED = 'Patient Enrollment Form Received';
    public static final String MISSING_INFORMATION_IN_FORM = 'Missing Information in Form';
    public static final String PROCESSING_ELIGIBILITY = 'Processing Eligibility';
    public static final String ELIGIBLE = 'Eligible';
    public static final String NOT_ELIGIBLE = 'Not-eligible';
    public static final String INELIGIBLE = 'Ineligible';
    public static final String SERVICES = 'Meals Services';
    public static final String NO = 'No';
    public static final String NUMBERS = '12';

    @testSetup static void testDataSetup()
    {
        List<Account> accToBeInserted = new List<Account>();
        Account trtSite = TestDataFactory.getBusinessAccountToInsert(StaticConstants.TreatmentSiteRecordTypeDeveloperName);
        accToBeInserted.add(trtSite);
        
        Account patient = TestDataFactory.getPatientAccountsToInsert(1);
        patient.BillingStreet = BILLING_STREET;
        patient.BillingCity = BILLING_CITY;
        patient.BillingPostalCode = BILLING_POSTAL_CODE;
        patient.BillingCountry = BILLING_COUNTRY;
        accToBeInserted.add(patient);
        insert accToBeInserted;
        
        List<Schema.Location> locationList = TestDataFactory.getLocationRecords(LOCATION,1);
        insert locationList;
        
        List<Id> siteIds = new List<Id>();
        siteIds.add(trtSite.Id);
        List<Schema.AssociatedLocation> associatedLocationRecords = TestDataFactory.getAssociatedLocationRecordsBasedOnSiteName(siteIds,locationList,1);
        insert associatedLocationRecords;
        
        Contact trtSiteContact = TestDataFactory.getSitePersonnelContact(StaticConstants.TREATMENTSITELABEL, trtSite.Id);
        Insert trtSiteContact;

        List<CareProgram> careProgramsList = TestDataFactory.getCareProgramsList(CARE_PROGRAM, 1);
		insert careProgramsList;
        
        CareProgramEnrollee patientEnrolled = TestDataFactory.getCareProgramEnrollee(careProgramsList[0].Id, patient.Id);
        insert patientEnrolled;
        
        Case carePlan = TestDataFactory.getCasestoInsert(trtSiteContact.Id,patient.Id);
        insert carePlan;
        
        PatientServicesEnrollee__c pseList = TestDataFactory.getPatientServicesEnrollee(carePlan.Id,patient.Id);
        insert pseList;
        
        HealthCloudGA__ReciprocalRole__c carTRole = TestDataFactory.getContactRole(StaticConstants.CARTCOORDINATOR, StaticConstants.contactRole);
        insert carTRole;
        
        HealthCloudGA__ContactContactRelation__c contactRel = new HealthCloudGA__ContactContactRelation__c();
        contactRel.Account__c = patient.Id;
        contactRel.HealthCloudGA__Contact__c = trtSiteContact.Id;
        contactRel.HealthCloudGA__Contact__r = trtSiteContact;
        contactRel.HealthCloudGA__Contact__r.SitePersona__c = StaticConstants.CARTCOORDINATOR;
		contactRel.HealthCloudGA__RelatedContact__r = trtSiteContact;
		contactRel.HealthCloudGA__Role__c = carTRole.Id;
        insert contactRel;
    }

    @isTest static void itShouldUpdatePSEAsEligible()
    {  
        //GIVEN - A Patient Services Enrollee record
        List<PatientServicesEnrollee__c> pseRecords = ((PatientServicesEnrolleesSelector) Application.Selector.newInstance(PatientServicesEnrollee__c.SobjectType)).selectAll();
        PatientServicesEnrollee__c currentPSE = new PatientServicesEnrollee__c();
        for (PatientServicesEnrollee__c objPSE: pseRecords)
        {
            if (objPSE.PatientServicesStatus__c.equalsIgnoreCase(NEW_PATIENT_SERVICES_REQUEST))
            {
                currentPSE = objPSE;
                break;
            }
        }

        Test.startTest();
        //WHEN - Update Patient information in Patient Enrollee Services
        currentPSE.PatientServicesStatus__c = REQUEST_TO_ENROLL_CONFIRMED;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = PATIENT_ENROLLMENT_FORM_RECEIVED;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = MISSING_INFORMATION_IN_FORM;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = PROCESSING_ELIGIBILITY;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = ELIGIBLE;
        currentPSE.DistanceMileage__c = NUMBERS;
        currentPSE.DistanceTime__c = NUMBERS;
        currentPSE.NonEmergencyMedicalTravel__c = NO;
        currentPSE.LodgingSupport__c = NO;
        currentPSE.DateEligibilityCheckPerformed__c = System.today()+1;
        currentPSE.MileageEligibility__c = ELIGIBLE;
        currentPSE.TimeEligibility__c = ELIGIBLE;
        currentPSE.InsuranceEligibility__c = ELIGIBLE;
        currentPSE.LodgingEligibility__c = ELIGIBLE;
        currentPSE.IncomeEligibility__c = ELIGIBLE;
        currentPSE.PatientServices__c = SERVICES;
        update currentPSE;
        
        //THEN - It should update the Patient Services Enrollee as Eligible
        System.assertEquals(currentPSE.PatientServicesStatus__c,ELIGIBLE);
        Test.stopTest(); 
    }
    
    @isTest static void itShouldUpdatePSEAsIneligible()
    {  
       //GIVEN - A Patient Services Enrollee record
        List<PatientServicesEnrollee__c> pseRecords = ((PatientServicesEnrolleesSelector) Application.Selector.newInstance(PatientServicesEnrollee__c.SobjectType)).selectAll();
        PatientServicesEnrollee__c currentPSE = new PatientServicesEnrollee__c();
        for (PatientServicesEnrollee__c objPSE: pseRecords)
        {
            if (objPSE.PatientServicesStatus__c.equalsIgnoreCase(NEW_PATIENT_SERVICES_REQUEST))
            {
                currentPSE = objPSE;
                break;
            }
        }

        Test.startTest();
        //WHEN - Update Patient information in Patient Enrollee Services
        currentPSE.PatientServicesStatus__c = REQUEST_TO_ENROLL_CONFIRMED;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = PATIENT_ENROLLMENT_FORM_RECEIVED;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = MISSING_INFORMATION_IN_FORM;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = PROCESSING_ELIGIBILITY;
        update currentPSE;
        currentPSE.PatientServicesStatus__c = INELIGIBLE;
        currentPSE.DistanceMileage__c = NUMBERS;
        currentPSE.DistanceTime__c = NUMBERS;
        currentPSE.NonEmergencyMedicalTravel__c = NO;
        currentPSE.LodgingSupport__c = NO;
        currentPSE.DateEligibilityCheckPerformed__c = System.today()+1;
        currentPSE.MileageEligibility__c = NOT_ELIGIBLE;
        currentPSE.TimeEligibility__c = NOT_ELIGIBLE;
        currentPSE.InsuranceEligibility__c = NOT_ELIGIBLE;
        currentPSE.LodgingEligibility__c = NOT_ELIGIBLE;
        currentPSE.IncomeEligibility__c = NOT_ELIGIBLE;
        currentPSE.PatientServices__c = SERVICES;
        update currentPSE;
        
        //THEN - It should update the Patient Services Enrollee as Ineligible
        System.assertEquals(currentPSE.PatientServicesStatus__c,INELIGIBLE);
        Test.stopTest(); 
    }
}