objects/Account/fields/AccountIdentifier__c.field-meta.xml
<CustomField>
    <fullName>AccountIdentifier__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Unique identifier for Institute, Site or Patient that is system generated.</description>
    <displayFormat>ACT{0000}</displayFormat>
    <label>Account Identifier</label>
    <type>AutoNumber</type>
</CustomField>

objects/Account/fields/CellTherapyOrderSpecialist__c.field-meta.xml
<CustomField>
    <fullName>CellTherapyOrderSpecialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to associate and operations coordinator with a treatment site</description>
    <label>Cell Therapy Order Specialist (CTOS)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RelatedAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Account/fields/CustomerCode__c.field-meta.xml
<CustomField>
    <fullName>CustomerCode__c</fullName>
    <description>This field is used to store treatment site customer code from SAP</description>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email Information</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

objects/Account/fields/ERPSiteID__c.field-meta.xml
<CustomField>
    <fullName>ERPSiteID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan.</description>
    <externalId>true</externalId>
    <inlineHelpText>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan</inlineHelpText>
    <label>ERP Site ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <description>External Patient Id For Patient Account</description>
    <externalId>true</externalId>
    <label>PatientID</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/PreferredMethodOfCommunication__c.field-meta.xml
<CustomField>
    <fullName>PreferredMethodOfCommunication__c</fullName>
    <description>This field will be used to capture the Preferred Method of Communication.</description>
    <label>Preferred Method of Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact Number</fullName>
                <default>true</default>
                <label>Primary Contact Number</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PrimaryContactNumberType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactNumberType__c</fullName>
    <description>Primary Contact Number Type captures the type of contact stored is Home or Mobile.</description>
    <label>Primary Contact Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/AccountsSelector.cls
public with sharing class AccountsSelector extends fflib_SObjectSelector
{
	public static final String PATIENTRECORDTYPEDEVELOPERNAME = 'Patient';
	string accountId = Account.Id.getDescribe().getName();

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				Account.AccountIdentifier__c,
				Account.PersonBirthdate,
				Account.CellTherapyOrderSpecialist__c,
				Account.CustomerCode__c,
				Account.Email__c,
				Account.ERPSiteID__c,
				Account.FirstName,
				Account.Id,
				Account.isPersonAccount,
				Account.LastName,
				Account.MiddleName,
				Account.Name,
				Account.ParentId,
				Account.PatientID__c,
				Account.PersonContactId,
				Account.PersonEmail,
				Account.PrimaryContactNumberType__c,
				Account.PreferredMethodOfCommunication__c,
				Account.Phone,
				Account.RecordTypeId,
				Account.Status__c,
				Account.Type
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Account.SObjectType;
	}

	public Accounts selectById(Set<Id> accountId)
	{
		return (Accounts) Application.Domain.newInstance(
				(List<Account>) selectSObjectsById(accountId)
		);
	}

	public Accounts selectAll()
	{
		return (Accounts) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING)
								.toSOQL()
				)
		);
	}

	public Accounts selectPatients()
	{
		Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PATIENTRECORDTYPEDEVELOPERNAME).getRecordTypeId();
		return (Accounts) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.selectField('PersonContactId')
								.selectField('PersonBirthdate')
								.selectField('Status__c')
								.setCondition('RecordTypeId=:recordTypeId')
								.setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING)
								.toSOQL()
				)
		);
	}

	public List<Account> selectContactsByAccountId(Set<Id> accountIds)
	{
		List<String> conFields = new List<String> {'Id', 'AccountId'};
		fflib_QueryFactory queryFactory = newQueryFactory();
		queryFactory.subselectQuery('Contacts')
				.selectFields(conFields);
		queryFactory.setCondition('Id IN:accountIds');
		return (List<Account>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
	}

	public List<Account> selectAllContactsForAccount(String recTypeId)
	{
		List<String> conFields = new List<String> {'Id', 'AccountId'};
		fflib_QueryFactory queryFactory = newQueryFactory()
				.setCondition('RecordTypeId =:recTypeId');
		queryFactory
				.subSelectQuery('Contacts')
				.selectFields(conFields);
		return (List<Account>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
	}

	public List<Account> getCryoTypeForSites(Set<Id> accountIds, Id recTypeId)
	{
		return ((List<Account>) Database.query(
				newQueryFactory()
						.selectField('Type')
						.setCondition('Id IN:accountIds AND RecordTypeId=:recTypeId')
						.toSOQL()
		));
	}

	public List<Account> selectByNameGenderAndDateOfBirth(String firstName, String middleName, String lastName, String gender, Date dateOfBirth)
	{
		return ((List<Account>) Database.query(
				newQueryFactory()
						.selectField('HealthCloudGA__Gender__pc')
						.selectField('PersonBirthdate')
						.setCondition('FirstName =:firstName AND MiddleName=:middleName AND LastName=:lastName AND HealthCloudGA__Gender__pc=:gender AND PersonBirthdate=:dateOfBirth')
						.toSOQL()
		));
	}

	public List<Account> selectByDeveloperName(String recTypeId)
	{
		return ((List<Account>) Database.query(
				newQueryFactory()
						.setCondition('RecordTypeId=:recTypeId')
						.toSOQL()));
	}

	public List<Account> elevatedGetCryoTypeForSites(Set<Id> accountIds, Id recTypeId)
	{
		fflib_QueryFactory queryFactory = newQueryFactory();
		return new elevatedContext(queryFactory).elevatedGetCryoTypeForSites(accountIds, recTypeId);

	}

	public List<Account> elevatedSelectByERPSiteId(String erpSiteId, String recTypeId)
	{
		fflib_QueryFactory queryFactory = newQueryFactory();
		return new elevatedContext(queryFactory).elevatedSelectByERPSiteId(erpSiteId, recTypeId);
	}

	public List<Account> elevatedSelectById(Set<Id> accountIds)
	{
		fflib_QueryFactory queryFactory = newQueryFactory();
		return new elevatedContext(queryFactory).elevatedSelectById(accountIds);
	}

	private without sharing class elevatedContext
	{
		private fflib_QueryFactory queryFactory;

		private elevatedContext(fflib_QueryFactory queryFactory)
		{
			this.queryFactory = queryFactory;
		}

	private List<Account> elevatedGetCryoTypeForSites(Set<Id> accountIds, Id recTypeId)
		{
			Set<String> fieldSet = new Set<String>();
			fieldSet.add('Type');
			queryFactory.selectFields(fieldSet);
			queryFactory.setCondition('Id IN:accountIds AND RecordTypeId=:recTypeId');
			return (List<Account>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		private List<Account> elevatedSelectByERPSiteId(String erpSiteId, String recTypeId)
		{
			String erpSite = Account.ERPSiteID__c.getDescribe().getName();
			queryFactory.setCondition(erpSite + ' =:erpSiteId AND RecordTypeId=:recTypeId');
			return (List<Account>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		private List<Account> elevatedSelectById(Set<Id> accountIds)
		{
			queryFactory.setCondition('Id IN:accountIds');
			queryFactory.selectField('Parent.RecordTypeId');
			return (List<Account>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}
	}

	public List<Account> selectTreatmentSiteByIds(Set<Id> treatmentSiteIds){
		return ((List<Account>) Database.query(
				newQueryFactory()
						.selectField('ERPSiteID__c')
						.setCondition( accountId +' IN :treatmentSiteIds')
						.toSOQL()));
	}

	public List<Account> selectByAccountIds(Set<Id> accountIds)
	{
		return ((List<Account>) Database.query(
				newQueryFactory()
						.setCondition('Id IN:accountIds')
						.toSOQL()));
	}

}