objects/Account/fields/CellTherapyOrderSpecialist__c.field-meta.xml
<CustomField>
    <fullName>CellTherapyOrderSpecialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to associate and operations coordinator with a treatment site</description>
    <label>Cell Therapy Order Specialist (CTOS)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RelatedAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/fields/BeginPatientSupportEligibilityCheck__c.field-meta.xml
<CustomField>
    <fullName>BeginPatientSupportEligibilityCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to capture Patient’s confirmation for Service Program</description>
    <label>Begin Patient Support Eligibility Check</label>
    <type>Checkbox</type>
</CustomField>

objects/Case/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to relate cancellation requested order</description>
    <label>Order ID</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Cancellation Cases</relationshipLabel>
    <relationshipName>OrderCancellationCases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/fields/ReasonForCancellation__c.field-meta.xml
<CustomField>
    <fullName>ReasonForCancellation__c</fullName>
    <description>This field is used to store Order Cancellation Reason</description>
    <label>Reason for Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Patient withdrew consent for treatment with Janssen CAR-T</fullName>
            </value>
            <value>
                <fullName>Patient health-related reason</fullName>
            </value>
            <value>
                <fullName>Other patient-related reason</fullName>
            </value>
            <value>
                <fullName>Other non-patient related reason</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Case/fields/TreatmentSite__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to the associated Treatment Site location.</description>
    <label>Treatment Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Treatment Site Cases</relationshipLabel>
    <relationshipName>TreatmentSiteCases</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/CasesSelector.cls
public with sharing class CasesSelector extends fflib_SObjectSelector
{
	private static String orderId = Case.OrderID__c.getDescribe().getName();

	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				Case.AccountId,
				Case.BeginPatientSupportEligibilityCheck__c,
				Case.ContactId,
				Case.Id,
				Case.OrderID__c,
				Case.ReasonForCancellation__c,
				Case.Status,
				Case.Subject,
				Case.TreatmentSite__c
		};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Case.SObjectType;
	}

	public Cases selectByPatientAccountId(Set<Id> accountIds)
	{
		return (Cases) Application.Domain.newInstance(
				Database.query(
						newQueryFactory()
								.selectField('Account.Name')
								.selectField('BeginPatientSupportEligibilityCheck__c')
								.selectField('RecordTypeId')
								.selectField('Status')
								.setCondition('AccountId IN :accountIds')
								.toSOQL()
				)
		);
	}

    public List<Case> selectByCarePlanId(Set<Id> setOfCarePlanIds)
    {
        return (List<Case>) Database.query(
                newQueryFactory()
					.selectField('TreatmentSite__r.CellTherapyOrderSpecialist__c')
                    .setCondition('Id IN: setOfCarePlanIds')
                    .toSOQL()
        );
    }

	public List<Case> elevatedSelectTasksByCarePlanId(Set<Id> setOfCarePlanIds)
	{
		return new ElevateContext(this).elevatedSelectTasksByCarePlanId(setOfCarePlanIds);
	}

	public List<Case> selectAll()
	{
		return (List<Case>) Database.query(
				newQueryFactory()
					.toSOQL()
		);
	}

	public List<Case> elevatedSelectByAccountId(Set<Id> accountIds)
	{
		ElevateContext elevatedContext = new ElevateContext(this);
		return elevatedContext.elevatedSelectByAccountId(accountIds);
	}

	public List<Case> elevatedSelectByCarePlanId(Set<Id> setOfCarePlanIds)
	{
		ElevateContext elevatedContext = new ElevateContext(this);
		return elevatedContext.elevatedSelectByCarePlanId(setOfCarePlanIds);
	}

	public List<Case> selectCasesByPatientIds(Set<Id> accountIds,Set<Id> recordTypeIds)
	{
		return (List<Case>) Database.query(
									 newQueryFactory(true,true,false)
													.selectField('AccountId')
													.setCondition('AccountId IN :accountIds AND RecordTypeId IN :recordTypeIds')
													.toSOQL());
	}

	public List<Case> selectCasesByOrderIds(Set<Id> orderIds)
	{
		return (List<Case>) Database.query(
				newQueryFactory()
						.setCondition( orderId + ' IN : orderIds')
						.toSOQL());
	}

	public Database.QueryLocator getQLOfCasesCreatedEditedInLastNDays(Integer lastNDays, Set<Id> recordTypeIds)
	{
		return Database.getQueryLocator(
				newQueryFactory(false, false, false)
            			.selectField(Case.AccountId.getDescribe().getName())
						.setCondition(String.format('{0} = LAST_N_DAYS:{1} AND RecordTypeId IN :recordTypeIds',
						new List<String>
						{
								Case.LastModifiedDate.getDescribe().getName(),
								String.valueOf(lastNDays)
						}))
						.toSOQL());
	}


	private without sharing class ElevateContext extends fflib_SObjectSelector
	{
		CasesSelector selector;

		public ElevateContext(CasesSelector selector)
		{
			super(true, false, false, true);
			this.selector = selector;
		}

		public List<Schema.SObjectField> getSObjectFieldList()
		{
			return selector.getSObjectFieldList();
		}

		public Schema.SObjectType getSObjectType()
		{
			return selector.getSObjectType();
		}

		public List<Case> elevatedSelectByAccountId(Set<Id> accountIds)
		{
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('Account.Name');
			queryFactory.selectField('BeginPatientSupportEligibilityCheck__c');
			queryFactory.selectField('RecordTypeId');
			queryFactory.selectField('Status');
			queryFactory.setCondition('AccountId IN :accountIds');
			return (List<Case>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		public List<Case> elevatedSelectByCarePlanId(Set<Id> setOfCarePlanIds)
		{
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.selectField('TreatmentSite__r.CellTherapyOrderSpecialist__c');
			queryFactory.setCondition('Id IN: setOfCarePlanIds');
			return (List<Case>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}

		public List<Case> elevatedSelectTasksByCarePlanId(Set<Id> setOfCarePlanIds)
		{
			String goalName = Schema.Task.GoalName__c.getDescribe().getName();
			fflib_QueryFactory queryFactory = newQueryFactory();
			queryFactory.setCondition('Id IN :setOfCarePlanIds');
			new TasksSelector().addQueryFactorySubselect(queryFactory, 'Tasks').setCondition(goalName + ' !=null ');
			return (List<Case>) Database.query(String.escapeSingleQuotes(queryFactory.toSOQL()));
		}
	}

}