objects/Account/fields/CellTherapyOrderSpecialist__c.field-meta.xml
<CustomField>
    <fullName>CellTherapyOrderSpecialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to associate and operations coordinator with a treatment site</description>
    <label>Cell Therapy Order Specialist (CTOS)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RelatedAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Case/fields/TreatmentSite__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field refers to the associated Treatment Site location.</description>
    <label>Treatment Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Treatment Site Cases</relationshipLabel>
    <relationshipName>TreatmentSiteCases</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Priority__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__CarePlanTemplateTask__c/fields/HealthCloudGA__Type__c.field-meta.xml
<CustomField>
    <fullName>HealthCloudGA__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
                <default>true</default>
                <label>Automated</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Administrative</fullName>
                <isActive>false</isActive>
                <label>Administrative</label>
            </value>
            <value>
                <fullName>Clinical</fullName>
                <isActive>false</isActive>
                <label>Clinical</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
            <value>
                <fullName>Uncategorized</fullName>
                <isActive>false</isActive>
                <label>Uncategorized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/FinalDPDateinVineti__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDateinVineti__c</fullName>
    <description>Final DP Date that is coming from Vineti</description>
    <label>Final DP Date Updated in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/OrderRescheduledinVineti__c.field-meta.xml
<CustomField>
    <fullName>OrderRescheduledinVineti__c</fullName>
    <description>Order Rescheduled Updated in Vineti System.</description>
    <label>Order Rescheduled in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/TreatmentSite__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Treatment Site recorded on Care Plan.</description>
    <label>Treatment Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Treatment Site)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/VinetiCOI__c.field-meta.xml
<CustomField>
    <fullName>VinetiCOI__c</fullName>
    <description>Field to track courier shipment details in the Vineti portal.</description>
    <externalId>true</externalId>
    <label>Vineti COI #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/OrderTaskConfig__mdt/OrderTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type to Create adhoc Tasks for Vein to Vein to manage outbound integrations.</description>
    <label>Order Task Config</label>
    <pluralLabel>Order Tasks Config</pluralLabel>
</CustomObject>

objects/OrderTaskConfig__mdt/fields/DaysToReachDueDate__c.field-meta.xml
<CustomField>
    <fullName>DaysToReachDueDate__c</fullName>
    <description>Days To Reach Due Date in the task</description>
    <label>Days To Reach Due Date</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <description>Picklist to select the Task Priority</description>
    <label>Task Priority</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <description>Status for the tasks </description>
    <label>Task Status</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <description>Subjects for the current tasks</description>
    <label>Task Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/OrderTaskConfig__mdt/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <description>This field holds value to set for task while task creation</description>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
                <default>true</default>
                <label>Automated</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/PatientServiceEnrolleeTaskConfig__mdt.object-meta.xml
<CustomObject>
    <description>This Custom Metadata contains information related to Task Record Creation values on Patient Service Enrolled Record Creation.</description>
    <label>Patient Service Enrollee Task Config</label>
    <pluralLabel>Patient Service Enrollee Task Config</pluralLabel>
</CustomObject>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/DaysToReachDueDate__c.field-meta.xml
<CustomField>
    <fullName>DaysToReachDueDate__c</fullName>
    <label>Days To Reach Due Date</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskPriority__c.field-meta.xml
<CustomField>
    <fullName>TaskPriority__c</fullName>
    <defaultValue>&apos;Normal&apos;</defaultValue>
    <label>Task Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskStatus__c.field-meta.xml
<CustomField>
    <fullName>TaskStatus__c</fullName>
    <label>Task Status</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskSubject__c.field-meta.xml
<CustomField>
    <fullName>TaskSubject__c</fullName>
    <label>Task Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

objects/PatientServiceEnrolleeTaskConfig__mdt/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <description>This Fields Holds Value to map to Task Type Field on Task Object</description>
    <label>Task Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
                <default>true</default>
                <label>Automated</label>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PatientServicesEnrollee__c/fields/PatientServicesStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientServicesStatus__c</fullName>
    <description>Status of the Patient Services Record</description>
    <defaultValue>&apos;New Patient Services request&apos;</defaultValue>
    <label>Patient Services Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Patient Services Request</fullName>
                <default>true</default>
                <label>New Patient Services Request</label>
            </value>
            <value>
                <fullName>Request to Enroll Confirmed</fullName>
            </value>
            <value>
                <fullName>Patient Enrollment Form Received</fullName>
            </value>
            <value>
                <fullName>Missing Information in Form</fullName>
            </value>
            <value>
                <fullName>Processing Eligibility</fullName>
            </value>
            <value>
                <fullName>Eligible</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Enrolled in Service</fullName>
            </value>
            <value>
                <fullName>Opted out of Patient Services</fullName>
            </value>
            <value>
                <fullName>Request for Information Only</fullName>
            </value>
            <value>
                <fullName>Patient Services Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Task/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <description>Represents a General Task</description>
    <label>General</label>
</RecordType>

classes/TasksService.cls
public with sharing class TasksService
{
	static final String GENERAL ='General';
	static final String INTERNAL_OPERATIONS_COORDINATOR = 'CellTherapyOrderSpecialist';

	public List<Task> elevatedCreateCarePlanTasks(List<HealthCloudGA__CarePlanTemplateGoal__c> carePlanTemplateGoals, List<HealthCloudGA__CarePlanGoal__c> lstCarePlanGoals)
	{
		List<Task> carePlanGoalTasks = new List<Task>();
		if (carePlanTemplateGoals.isEmpty() || lstCarePlanGoals.isEmpty()) return carePlanGoalTasks;

		Set<Id> carePlanTemplateGoalIds = sflib_ArrayUtils.pluckIdField(carePlanTemplateGoals, HealthCloudGA__CarePlanTemplateGoal__c.Id);
		List<HealthCloudGA__CarePlanTemplateTask__c> lstCarePlanTemplateTasks = ((CarePlanTemplateTasksSelector) Application.Selector.newInstance(HealthCloudGA__CarePlanTemplateTask__c.SObjectType)).selectByCarePlanTemplateGoalIds(carePlanTemplateGoalIds);

		Id carePlanTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CarePlanTask').getRecordTypeId();
		if (lstCarePlanTemplateTasks.isEmpty()) return carePlanGoalTasks;

		Set<Id> carePlanIds = sflib_ArrayUtils.pluckIdField(lstCarePlanGoals,HealthCloudGA__CarePlanGoal__c.HealthCloudGA__CarePlan__c);
		Map<Id,Case> carePlanMap = new Map<Id, Case>((List<Case>)((CasesSelector) Application.Selector.newInstance(Case.SObjectType))
				.elevatedSelectByCarePlanId(carePlanIds));

		for (HealthCloudGA__CarePlanTemplateTask__c objCarePlanTemplateTask : lstCarePlanTemplateTasks)
		{
			for (HealthCloudGA__CarePlanGoal__c objGoal : lstCarePlanGoals)
			{
				if (objCarePlanTemplateTask.HealthCloudGA__CarePlanTemplateGoal__r.Name == objGoal.Name)
				{
					Task objTask = new Task();
					objTask.HealthCloudGA__CarePlanGoal__c = objGoal.Id;
					objTask.HealthCloudGA__CarePlanTemplate__c = objGoal.HealthCloudGA__CarePlanTemplate__c;
					objTask.RecordTypeId = carePlanTaskRecordTypeId;
					objTask.HealthCloudGA__SortOrder__c = objCarePlanTemplateTask.HealthCloudGA__SortOrder__c;
					objTask.Priority = objCarePlanTemplateTask.HealthCloudGA__Priority__c;
					objTask.WhatId = objGoal.HealthCloudGA__CarePlan__c;
					if(carePlanMap.containsKey(objGoal.HealthCloudGA__CarePlan__c)
							&& carePlanMap.get(objGoal.HealthCloudGA__CarePlan__c).TreatmentSite__c != null
									&& carePlanMap.get(objGoal.HealthCloudGA__CarePlan__c).TreatmentSite__r.CellTherapyOrderSpecialist__c != null)
					{
						objTask.OwnerId = carePlanMap.get(objGoal.HealthCloudGA__CarePlan__c).TreatmentSite__r.CellTherapyOrderSpecialist__c;
					}
					objTask.HealthCloudGA__TaskType__c = objCarePlanTemplateTask.HealthCloudGA__Type__c;
					objTask.Status = objCarePlanTemplateTask.HealthCloudGA__Status__c;
					objTask.Subject = objCarePlanTemplateTask.HealthCloudGA__Subject__c;
					objTask.ActivityDate = System.today() + Integer.valueOf(objCarePlanTemplateTask.HealthCloudGA__Offset__c);
					objTask.Description = objCarePlanTemplateTask.HealthCloudGA__Description__c;
					carePlanGoalTasks.add(objTask);
				}
			}
		}
		try
		{
			fflib_ISObjectUnitOfWork elevatedUnitOfWork = Application.UnitOfWork.newInstance(new ElevatedContextDML());
			new ElevatedContextDML().elevatedCreateCarePlanTasks(carePlanGoalTasks, elevatedUnitOfWork);
			elevatedUnitOfWork.commitWork();
		}
		catch (Exception e)
		{
			Application.logEntry.error(e);
		}
		return carePlanGoalTasks;
	}

    public List<Task> getTasksForPatientServiceEnrollee(List<PatientServicesEnrollee__c> pseRecords,
            Map<String, List<PatientServiceEnrolleeTaskConfig__mdt>> pseStatusAndTaskConfigInfo,
            Id businessHoursId)
    {
        List<Task> tasks = new List<Task>();
        BusinessHoursCalculatorImp bhCalculatorImp = new BusinessHoursCalculatorImp(businessHoursId);
        DateTime nextBusinessHourDT = bhCalculatorImp.getNextBusinessHourDateTime(Date.today().addDays(1));
	    Id taskGeneralRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(GENERAL).getRecordTypeId();
        for (PatientServicesEnrollee__c pse : pseRecords)
        {
            if (!pseStatusAndTaskConfigInfo.containsKey(pse.PatientServicesStatus__c)) continue;
            for (PatientServiceEnrolleeTaskConfig__mdt pseConfig :
                    pseStatusAndTaskConfigInfo.get(pse.PatientServicesStatus__c))
            {
                tasks.add(getNewTask(pse, pseConfig, businessHoursId, nextBusinessHourDT, bhCalculatorImp, taskGeneralRecordTypeId));
            }
        }
        return tasks;
    }

    Task getNewTask(PatientServicesEnrollee__c pse, PatientServiceEnrolleeTaskConfig__mdt pseTaskConfig,
                    Id businessHoursId, DateTime nextBusinessHourDT, BusinessHoursCalculatorImp bhCalculatorImp,
                    Id recordTypeId)
    {
        return new Task(Subject = pseTaskConfig.TaskSubject__c, Status = pseTaskConfig.TaskStatus__c,
                whatId = pse.Id, OwnerId = pse.OwnerId,
                Priority = pseTaskConfig.TaskPriority__c,
                ActivityDate = bhCalculatorImp.getDueDateBasedOnBusinessHours(nextBusinessHourDT,
		        Integer.valueOf(pseTaskConfig.DaysToReachDueDate__c)),
                RecordTypeId=recordTypeId,
                HealthCloudGA__TaskType__c = pseTaskConfig.TaskType__c);
    }

	private without sharing class ElevatedContextDML implements fflib_SObjectUnitOfWork.IDML
	{
		public void dmlInsert(List<SObject> objList)
		{
			insert objList;
		}
		public void dmlUpdate(List<SObject> objList)
		{
			update objList;
		}
		public void dmlDelete(List<SObject> objList)
		{
			delete objList;
		}
		public void eventPublish(List<SObject> objList)
		{
			//not implemented
		}

		public void emptyRecycleBin(List<SObject> objList)
		{
			if (objList.isEmpty())
			{
				return;
			}
			Database.emptyRecycleBin(objList);
		}

		public void elevatedCreateCarePlanTasks(List<Task> tasks, fflib_ISObjectUnitOfWork unitOfWork)
		{
			unitOfWork.registerNew(tasks);
		}
	}

	public void closeTasks(List<Order__c> orderList, Map<Id,Order__c> existingOrders)
	{
		Map<Id,List<String>> tasksToCloseByCarePlanId = getTasksToCloseByCarePlanId(orderList, existingOrders);
		Set<Id> carePlanIds = sflib_ArrayUtils.pluckIdField(orderList, Order__c.CarePlanID__c);

		List<Task> openTasksList = ((TasksSelector) Application.Selector.newInstance(Task.SObjectType))
		.selectTasksByCarePlanIds(carePlanIds);

		List<Task> tasksToUpdate = new List<Task>();
		List<String> taskSubjectList;

		for(Task tsk : openTasksList)
		{
			Id carePlanId = tsk.whatId;

			if(tasksToCloseByCarePlanId.containsKey(carePlanId))
			{
				taskSubjectList = tasksToCloseByCarePlanId.get(carePlanId);

				if(taskSubjectList.contains(tsk.Subject))
				{
					tsk.Status = Label.StatusCompleted;
					tasksToUpdate.add(tsk);
				}
			}
		}

		if(!tasksToUpdate.isEmpty())
		{
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			uow.registerDirty(tasksToUpdate);
			uow.commitWork();
		}


	}

	private Map<Id,List<String>> getTasksToCloseByCarePlanId(List<Order__c> orderList, Map<Id,Order__c> existingRecords)
	{

		Map<Id,List<String>> tasksToCloseByCarePlanId = new Map<Id,List<String>>();
		List<String> subjects;
		Order__c oldOrder;
		Id carePlanId;

		for(Order__c ord : orderList)
		{
			oldOrder = existingRecords.get(ord.Id);
			carePlanId = ord.CarePlanID__c;

			if(!tasksToCloseByCarePlanId.containsKey(carePlanId))
			{
				tasksToCloseByCarePlanId.put(carePlanId, new List<String>());
			}

			if(ord.VinetiCOI__c	!= oldOrder.VinetiCOI__c)
			{
				subjects = tasksToCloseByCarePlanId.get(carePlanId);
				subjects.add(Label.OrderPlacement);

				tasksToCloseByCarePlanId.put(carePlanId, subjects);
			}

			if(ord.FinalDPDateinVineti__c != oldOrder.FinalDPDateinVineti__c)
			{
				subjects = tasksToCloseByCarePlanId.get(carePlanId);
				subjects.add(Label.ConfirmDeliveryDate);
				tasksToCloseByCarePlanId.put(carePlanId, subjects);
			}

			if(ord.OrderRescheduledinVineti__c != oldOrder.OrderRescheduledinVineti__c)
			{
				subjects = tasksToCloseByCarePlanId.get(carePlanId);
				subjects.add(Label.OrderReschedule);

				tasksToCloseByCarePlanId.put(carePlanId, subjects);
			}
		}
		return tasksToCloseByCarePlanId;
	}
	public List<Task> getAdhocTasksforVeinToVein(List<Order__c> orderRecords,
                                       Map<String, List<OrderTaskConfig__mdt>> orderTaskConfigInfo,
                                       Id businessHoursId, String taskSubject)
    {
        List<Group> queuesName = ((GroupsSelector) Application.Selector.newInstance(Group.SObjectType)).selectAll();
        String queueId = '';
        for(Group objGroup: queuesName){
            if(objGroup.Name == Label.V2VManagerQueue){
                queueId = objGroup.Id;
            }
        }
        List<Task> tasks = new List<Task>();
        BusinessHoursCalculatorImp bhCalculatorImp = new BusinessHoursCalculatorImp(businessHoursId);
        DateTime nextBusinessHourDT = bhCalculatorImp.getNextBusinessHourDateTime(Date.today().addDays(1));
	    Id taskGeneralRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get(GENERAL).getRecordTypeId();
        for (Order__c objOrder : orderRecords)
        {
            tasks.add(getNewAdhocTasksforVeinToVein(objOrder, orderTaskConfigInfo.get(taskSubject),
                                         nextBusinessHourDT,
                                         bhCalculatorImp, taskGeneralRecordTypeId,queueId));
        }
        return tasks;
    }
    Task getNewAdhocTasksforVeinToVein(Order__c objOrder,
                            List<OrderTaskConfig__mdt> orderTaskConfig,
                    		DateTime nextBusinessHourDT,
                            BusinessHoursCalculatorImp bhCalculatorImp,
                    		Id recordTypeId, String queueId)
    {
        return new Task(
            Subject = orderTaskConfig[0].TaskSubject__c,
            Status = orderTaskConfig[0].TaskStatus__c,
            WhatId = objOrder.CarePlanID__c,
            OwnerId = queueId,
            Priority = orderTaskConfig[0].TaskPriority__c,
            ActivityDate = bhCalculatorImp.getDueDateBasedOnBusinessHours(nextBusinessHourDT,Integer.valueOf(orderTaskConfig[0].DaysToReachDueDate__c)),
            RecordTypeId = recordTypeId,
            HealthCloudGA__TaskType__c = orderTaskConfig[0].TaskType__c
        );
    }

	public void assignOwnerId(List<Task> taskList)
	{
		List<HealthCloudGA__CarePlanTemplateTask__c> cptemplateTask = ((CarePlanTemplateTasksSelector) Application.Selector.newInstance(HealthCloudGA__CarePlanTemplateTask__c.SObjectType))
																		.selectRelatedToTemplateGoalByRole(INTERNAL_OPERATIONS_COORDINATOR);

		Set<String> tasksNameSet = sflib_ArrayUtils.pluckStringField(cptemplateTask, HealthCloudGA__CarePlanTemplateTask__c.HealthCloudGA__Subject__c);
		List<Task> tasksToUpdate = getTasksByName(tasksNameSet, taskList);
		Map<Id,List<Task>> tasksByCarePlan = (Map<Id,List<Task>>) new sflib_SObjects(tasksToUpdate).asSObjectsByIdField(Task.WhatId);
		Map<Id,Id> usersByCarePlanIdMap = getUsersByCarePlanIdMap(tasksByCarePlan.keySet());

		assignOwnerId(tasksByCarePlan, usersByCarePlanIdMap);
	}

	public void assignOwnerId(Map<Id,List<Task>> tasksByCarePlan, Map<Id,Id> usersByCarePlanId)
	{
		Id userId;

		for(Id carePlanId : tasksByCarePlan.keySet())
		{
			userId = usersByCarePlanId.get(carePlanId);

			if(userId != null)
			{
				for(Task task : tasksByCarePlan.get(carePlanId))
				{
					task.OwnerId = userId;
				}
			}

		}

	}

	public Map<Id,Id> getUsersByCarePlanIdMap(Set<Id> carePlanIds)
	{
		List<Case> carePlanList = ((CasesSelector) Application.Selector.newInstance(Case.SObjectType))
									.selectByCarePlanId(carePlanIds);

		Map<Id,Id> usersByCarePlanIdMap = new Map<Id,Id>();

		for(Case carePlan : carePlanList)
		{
			usersByCarePlanIdMap.put(carePlan.Id, carePlan.TreatmentSite__r.CellTherapyOrderSpecialist__c);
		}

		return usersByCarePlanIdMap;
	}

	public List<Task> getTasksByName(Set<String> tasksNameSet, List<Task> taskList)
	{
		List<Task> tasksToUpdate = new List<Task>();

		for(Task task : taskList)
		{
			if(tasksNameSet.contains(task.Subject))
			{
				tasksToUpdate.add(task);
			}
		}

		return tasksToUpdate;
	}

}