objects/Account/fields/ERPSiteID__c.field-meta.xml
<CustomField>
    <fullName>ERPSiteID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan.</description>
    <externalId>true</externalId>
    <inlineHelpText>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan</inlineHelpText>
    <label>ERP Site ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/AccountContactRelation/fields/MedicalRecordNumber__c.field-meta.xml
<CustomField>
    <fullName>MedicalRecordNumber__c</fullName>
	<complianceGroup>GxP</complianceGroup>
    <description>The medical record number is organization specific. The number is used by the hospital as a systematic documentation of a patient´s medical history and care during each hospital stay.</description>
    <label>Medical Record Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the enrolled patient.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Patient)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/SitePO__c.field-meta.xml
<CustomField>
    <fullName>SitePO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Site PO# from TCP.</description>
    <label>Site PO#</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/TreatmentSite__c.field-meta.xml
<CustomField>
    <fullName>TreatmentSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Treatment Site recorded on Care Plan.</description>
    <label>Treatment Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Treatment Site)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/PurchaseOrderServiceHelper.cls
public with sharing class PurchaseOrderServiceHelper implements ICalloutServiceHelper
{
	private static final String TREATMENTSITE = 'Treatment Site';

	public Map<Id, String> getCalloutInputRequestBody(Set<Id> orderIds)
	{
		Map<Id, String> orderIdNInputBody = new Map<Id, String>();

		List<Order__c> orders = ((OrdersSelector) Application.Selector
				.newInstance(Order__c.SObjectType))
				.selectOrdersByOrderId(orderIds);

		Set<Id> treatmentSiteIds = sflib_ArrayUtils.pluckIdField(orders, Order__c.TreatmentSite__c);

		if (treatmentSiteIds.isEmpty())
		{
			return orderIdNInputBody;
		}

		Map<Id, Account> treatmentSitesInfo = ((AccountsSelector) Application.Selector.newInstance
				(Account.SObjectType)).selectById(treatmentSiteIds).getById();

		SDNotificationServiceInput input = new SDNotificationServiceInput();
		Set<Id> patientIds = sflib_ArrayUtils.pluckIdField(orders, Order__c.Patient__c);
		Map<Id, String> patientMRNInfo = getPatientMRNInfo(patientIds);

		for (Order__c order : orders)
		{
			if (order.TreatmentSite__c == null || order.TreatmentSite__r.ERPSiteID__c == null)
			{
				continue;
			}
			input = new SDNotificationServiceInput();
			input.CARTOrderId = order.CartOrderId__c;
			input.TreatmentSiteID = order.TreatmentSite__r.ERPSiteID__c;
			input.QTCPO = String.valueOf(order.SitePO__c);
			input.MRN = patientMRNInfo ?.get(order.Patient__c);
			orderIdNInputBody.put(order.Id, JSON.serialize((SDNotificationServiceInput) input));
		}
		return orderIdNInputBody;
	}

	Map<Id, String> getPatientMRNInfo(Set<Id> patientIds)
	{
		AccountContactRelationsSelector acrSelector = (AccountContactRelationsSelector) Application.Selector
				.newInstance(AccountContactRelation.SObjectType);
		Map<Id, String> patientAndMRNInfo = new Map<Id, String>();
		for (AccountContactRelation acr : acrSelector.selectByContactAccountId(patientIds))
		{
			if (String.isNotBlank(acr.Roles) && acr.Roles.split(';').contains(TREATMENTSITE))
			{
				patientAndMRNInfo.put(acr.Contact.AccountId, acr.MedicalRecordNumber__c);
			}
		}
		return patientAndMRNInfo;
	}
}