objects/Account/fields/ERPSiteID__c.field-meta.xml
<CustomField>
    <fullName>ERPSiteID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan.</description>
    <externalId>true</externalId>
    <inlineHelpText>ERP Site ID for Treatment Sites will be received from ERP System and ERP Site ID for Apheresis Sites &amp; Cryo Sites will be received from Anaplan</inlineHelpText>
    <label>ERP Site ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Product2/fields/ApheresisMaterialCodeFresh__c.field-meta.xml
<CustomField>
    <fullName>ApheresisMaterialCodeFresh__c</fullName>
    <description>If the cryo type is local, then the fresh apheresis cell material code will be captured</description>
    <label>Apheresis Material Code Fresh</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/ApheresisMaterialCodeFrozen__c.field-meta.xml
<CustomField>
    <fullName>ApheresisMaterialCodeFrozen__c</fullName>
    <description>If the cryo type is central/raritan, then the cells will be cryo-preserved and their material no will be captured</description>
    <label>Apheresis Material Code Frozen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/MaterialNoFG__c.field-meta.xml
<CustomField>
    <fullName>MaterialNoFG__c</fullName>
    <description>The field is used to track the material no for the finished good</description>
    <label>Material No FG</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/QuantityAphersis__c.field-meta.xml
<CustomField>
    <fullName>QuantityAphersis__c</fullName>
    <description>The quantity of the Apheresed cells will be captured here</description>
    <label>Quantity Aphersis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/QuantityFG__c.field-meta.xml
<CustomField>
    <fullName>QuantityFG__c</fullName>
    <description>The quantity of the finished good will be captured here</description>
    <label>Quantity FG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/SalesOrderType__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderType__c</fullName>
    <description>Defines the types of sales order like verified sales order or new sales order etc.</description>
    <label>Sales Order Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/UOMApheresis__c.field-meta.xml
<CustomField>
    <fullName>UOMApheresis__c</fullName>
    <description>Defines the unit of measurement for apheresed cells</description>
    <label>UOM Apheresis</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Product2/fields/UOMFG__c.field-meta.xml
<CustomField>
    <fullName>UOMFG__c</fullName>
    <description>Defines the unit output for the manufactured cells</description>
    <label>UOM Finished Goods</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SiteProduct__c/SiteProduct__c.object-meta.xml
<CustomObject>
    <label>Site-Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteProduct__c/fields/ParentAccount__c.field-meta.xml
<CustomField>
    <fullName>ParentAccount__c</fullName>
    <description>Treatment site associated with the product</description>
    <label>Parent Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treatment Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site-Products</relationshipLabel>
    <relationshipName>SiteProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SiteProduct__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Corresponds to the product name</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Site-Products</relationshipLabel>
    <relationshipName>Site_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteProduct__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>This Field Stores Product Name</description>
    <formula>Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

objects/SiteProduct__c/fields/SpecialtyDistributor__c.field-meta.xml
<CustomField>
    <fullName>SpecialtyDistributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field lookup to the SD account to be associated with the product</description>
    <label>Specialty Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>SpecialtyDistributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Specialty Distributor</relationshipLabel>
    <relationshipName>Site_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/SiteProduct__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Site-Product</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SiteProductsSelector.cls
public with sharing class SiteProductsSelector extends sflib_SObjectSelector
{
	String ParentAccount = SiteProduct__c.ParentAccount__c.getDescribe().getName();
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField>
		{
				SiteProduct__c.Name,
				SiteProduct__c.ParentAccount__c,
				SiteProduct__c.Product__c,
				SiteProduct__c.ProductName__c,
				SiteProduct__c.SpecialtyDistributor__c,
				SiteProduct__c.Status__c
		};
	}

	public SObjectType getSObjectType()
	{
		return SiteProduct__c.SObjectType;
	}

	Public List<SiteProduct__c> getSiteProductInfo(Set<Id> treatmentSiteIds)
	{
		return (List<SiteProduct__c>) Database.query(
				newQueryFactory()
						.selectField('Product__r.QuantityFG__c')
						.selectField('Product__r.QuantityAphersis__c')
						.selectField('Product__r.UOMFG__c')
						.selectField('Product__r.UOMApheresis__c')
						.selectField('Product__r.SalesOrderType__c')
						.selectField('Product__r.ApheresisMaterialCodeFresh__c')
						.selectField('Product__r.ApheresisMaterialCodeFrozen__c')
						.selectField('Product__r.MaterialNoFG__c')
						.selectField('SpecialtyDistributor__r.ERPSiteID__c')
						.setCondition(ParentAccount + ' IN: treatmentSiteIds')
						.toSOQL());
	}

	public Database.QueryLocator getElevatedQLOfSiteProuctsCreatEditedInLastNDays(Integer lastNDays)
	{
		return new ElevatedContext(this).getElevatedQLOfSiteProuctsCreatEditedInLastNDays(lastNDays);
	}

	private without sharing class ElevatedContext extends fflib_SObjectSelector
	{
		private SiteProductsSelector siteProductsSelector;
		public ElevatedContext(SiteProductsSelector siteProductsSelector)
		{
			super(true, false, false, true);
			this.siteProductsSelector = siteProductsSelector;
		}

		public List<Schema.SObjectField> getSObjectFieldList()
		{
			return siteProductsSelector.getSObjectFieldList();
		}

		public Schema.SObjectType getSObjectType()
		{
			return siteProductsSelector.getSObjectType();
		}

		public Database.QueryLocator getElevatedQLOfSiteProuctsCreatEditedInLastNDays(Integer lastNDays)
		{
			return Database.getQueryLocator(
						newQueryFactory(false, false, true)
							.setCondition(String.format('{0} = LAST_N_DAYS:{1} ',
							new List<String>
							{
									SiteProduct__c.LastModifiedDate.getDescribe().getName(),
									String.valueOf(lastNDays)
							}))
							.toSOQL());
		}

	}
}