objects/Account/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <description>External Patient Id For Patient Account</description>
    <externalId>true</externalId>
    <label>PatientID</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>Salesforce Id of the record associated with the alert</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the alert to control number of alerts visible to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ConfirmedFPDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedFPDeliveryDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Confirmed FP Delivery Date of the order.</description>
    <label>Confirmed DP Delivery Date from Site</label>
    <type>Date</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/ManufacturingStatus__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Manufacturing Status related to the order.</description>
    <label>Manufacturing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>True</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>QC/QA Complete</fullName>
            </value>
            <value>
                <fullName>Manufacturing Started</fullName>
            </value>
            <value>
                <fullName>Manufacturing Complete</fullName>
            </value>
            <value>
                <fullName>QR Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the enrolled patient.</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Patient)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Patient Id autonumber from The patient</description>
    <formula>Patient__r.PatientID__c</formula>
    <label>Patient ID</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the enrolled Patient.</description>
    <formula>TEXT(CarePlanID__r.Account.Status__c)</formula>
    <label>Patient Status</label>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/PatientLandingPageStatusValue__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch Patient Treatment Milestone for patients-TCP list view table</description>
    <label>Patient Landing Page Status Value</label>
    <pluralLabel>Patient Landing Page Status Values</pluralLabel>
</CustomObject>

objects/PatientLandingPageStatusValue__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Custom field to store Active/Inactive value for Milestone Status field</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/CarePlanStatus__c.field-meta.xml
<CustomField>
    <fullName>CarePlanStatus__c</fullName>
    <description>Custom field to store Care Plan Status of the patient</description>
    <label>Care Plan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>Custom field to store Order Status of the patient</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <description>Custom field to store Patient Status of the patient</description>
    <label>Patient Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientTreatmentMilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientTreatmentMilestoneStatus__c</fullName>
    <description>Custom field to store Patient Treatment Milestone Status of the patient</description>
    <label>Patient Treatment Milestone Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/PatientsListViewController.cls
public with sharing class PatientsListViewController
{

	public static final String PHYSICIAN = 'Physician';
	public static final String CARTCOORDINATOR = 'CAR-T Coordinator';
	public final static String STATUSUNREAD = 'Unread';
	public final static String PATIENTCARD = 'patientCard';

	private PatientsListViewController()
	{

	}

	private static AccountsService AccountsService
	{
		get
		{
			if (null == AccountsService)
			{
				AccountsService = (AccountsService) Application.Service.newInstance(AccountsService.class);
			}
			return AccountsService;
		}
		set;
	}

	private static CasesService CasesService
	{
		get
		{
			if (null == CasesService)
			{
				CasesService = (CasesService) Application.Service.newInstance(CasesService.class);
			}
			return CasesService;
		}
		set;
	}

	private static ContactContactRelationsService ContactContactRelationsService
	{
		get
		{
			if (null == ContactContactRelationsService)
			{
				ContactContactRelationsService = (ContactContactRelationsService) Application.Service.newInstance(ContactContactRelationsService.class);
			}
			return ContactContactRelationsService;
		}
		set;
	}

	private static OrdersService OrdersService
	{
		get
		{
			if (null == OrdersService)
			{
				OrdersService = (OrdersService) Application.Service.newInstance(OrdersService.class);
			}
			return OrdersService;
		}
		set;
	}

	private static PatientTreatmentMilestonesService PatientTreatmentMilestonesService
	{
		get
		{
			if (null == PatientTreatmentMilestonesService)
			{
				PatientTreatmentMilestonesService = (PatientTreatmentMilestonesService) Application.Service.newInstance(PatientTreatmentMilestonesService.class);
			}
			return PatientTreatmentMilestonesService;
		}
		set;
	}

	private static AccountContactRelationsService AccountContactRelationsService
	{
		get
		{
			if (null == AccountContactRelationsService)
			{
				AccountContactRelationsService = (AccountContactRelationsService) Application.Service.newInstance(AccountContactRelationsService.class);
			}
			return AccountContactRelationsService;
		}
		set;
	}

	@AuraEnabled
	public static String fetchPatientDetails()
	{
		try
		{
			String strJsonPatient = '';
			List<PatientsWrapper> lstPatientWrapper = new List<PatientsWrapper>();
			Map<Id, Account> patientsById = AccountsService.getPatients();
			Map<Id, Id> PersonContactIdByPatientId = new Accounts(patientsById.values()).getPersonContactIdById();

			Set<Id> patientContactIds = new Accounts(patientsById.values()).getPersonContactIds();

			Map<Id, String> treatingPhysicianNameByContactId = ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, PHYSICIAN);
			Map<Id, String> cartCoordinatorByContactId = ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, CARTCOORDINATOR);

			Map<Id, Case> carePlanByPatientId = CasesService.elevatedGetCarePlanByPatientId(patientsById.keySet());
			Map<Id, Order__c> orderByPatientId = OrdersService.elevatedGetOrderByPatientId(patientsById.keySet());

			List<PatientLandingPageStatusValue__mdt> lstPatientStatus = PatientTreatmentMilestonesService.getPatientStatusValues();
			Map<Id, PatientLandingPageStatusValue__mdt> milestoneStatusValue = getPatientTreatmentMilestone(patientsById, carePlanByPatientId, orderByPatientId, lstPatientStatus);

			Map<String, List<Notification__c>> notificationsByPatientId = getNotificationsByPatientId(patientsById.keySet());
			Map<Id,String> mrnByPatientId = AccountContactRelationsService.getPatientMRNInfo(patientsById.keySet());
			for (Account objPatient : patientsById.values())
			{
				PatientsWrapper objPatientWrapper = new PatientsWrapper();
				objPatientWrapper.memberId = objPatient.Id;
				objPatientWrapper.setMemberName(objPatient.LastName, objPatient.MiddleName, objPatient.FirstName);
				objPatientWrapper.memberFirstName = objPatient.FirstName;
				objPatientWrapper.memberLastName = objPatient.LastName;
				objPatientWrapper.memberMRN = mrnByPatientId.containsKey(objPatient.Id) ? mrnByPatientId.get(objPatient.Id) : '';
				objPatientWrapper.memberDateOfBirth = objPatient.PersonBirthdate;
				if (notificationsByPatientId.isEmpty())
				{
					objPatientWrapper.alerts = '';
				}
				else
				{
					objPatientWrapper.alerts = notificationsByPatientId.keySet().contains(objPatient.Id) ? notificationsByPatientId.get(objPatient.Id).size() + '' : '';
				}
				assignRelatedData(objPatientWrapper, carePlanByPatientId, objPatient.Id, treatingPhysicianNameByContactId, PersonContactIdByPatientId, cartCoordinatorByContactId, milestoneStatusValue);
				lstPatientWrapper.add(objPatientWrapper);
			}
			strJsonPatient = JSON.serialize(lstPatientWrapper);
			return strJsonPatient;
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	private static Map<String, List<Notification__c>> getNotificationsByPatientId(Set<Id> accountsId)
	{
		Set<String> readStatus = new Set<String>();
		readStatus.add(STATUSUNREAD);
		List<Notification__c> notifications =
				(new NotificationsSelector().selectRelatedRecordId(accountsId, readStatus)).Records ;
		Map<String, List<Notification__c>> notificationsByPatientId = new Map<String, List<Notification__c>>();
		if (!notifications.isEmpty())
		{
			for (Notification__c notification : notifications)
			{
				if (notificationsByPatientId.containsKey(notification.RelatedRecordId__c))
				{
					List<Notification__c> notificationsForMap = notificationsByPatientId.get(notification.RelatedRecordId__c);
					notificationsForMap.add(notification);
					notificationsByPatientId.put(notification.RelatedRecordId__c, notificationsForMap);
				}
				else
				{
					notificationsByPatientId.put(notification.RelatedRecordId__c, new List<Notification__c> {notification});
				}
			}
		}
		return notificationsByPatientId;
	}

	public static Map<Id, PatientLandingPageStatusValue__mdt> getPatientTreatmentMilestone(Map<Id, Account> patientsById, Map<Id, Case> carePlanByPatientId, Map<Id, Order__c> orderByPatientId, List<PatientLandingPageStatusValue__mdt> lstPatientStatus)
	{
		Map<Id, PatientLandingPageStatusValue__mdt> enrollmentByAccountID = new Map<Id, PatientLandingPageStatusValue__mdt>();
		for (Account objacc : patientsById.values())
		{
			for (PatientLandingPageStatusValue__mdt milestoneStatusValue : lstPatientStatus)
			{
				if (milestoneStatusValue.PatientStatus__c == objacc.Status__c
						&& carePlanByPatientId.containsKey(objacc.Id)
						&& milestoneStatusValue.CarePlanStatus__c == carePlanByPatientId.get(objacc.Id).Status
						&& orderByPatientId.containsKey(objacc.Id)
						&& milestoneStatusValue.OrderStatus__c == orderByPatientId.get(objacc.Id).OrderStatus__c)
				{
					enrollmentByAccountID.put(objacc.Id, milestoneStatusValue);
				}
			}
		}
		return enrollmentByAccountID;
	}

	public static PatientsWrapper assignRelatedData(PatientsWrapper objPatientWrapper, Map<Id, Case> carePlanByPatientId, Id patientId, Map<Id, String> treatingPhysicianNameByContactId, Map<Id, Id> contactIdByPatientId, Map<Id, String> cartCoordinatorByContactId, Map<Id, PatientLandingPageStatusValue__mdt> milestoneStatusValue)
	{
		if (milestoneStatusValue.containsKey(patientId))
		{
			objPatientWrapper.patientTreatingMilestone = milestoneStatusValue.get(patientId).PatientTreatmentMilestoneStatus__c;
			objPatientWrapper.isPatientTreatingMilestoneActive = milestoneStatusValue.get(patientId).Active__c;
		}
		if (contactIdByPatientId.containsKey(patientId) && treatingPhysicianNameByContactId.containsKey(contactIdByPatientId.get(patientId)))
		{
			objPatientWrapper.treatingPhysician = treatingPhysicianNameByContactId.get(contactIdByPatientId.get(patientId));
		}
		if (contactIdByPatientId.containsKey(patientId) && cartCoordinatorByContactId.containsKey(contactIdByPatientId.get(patientId)))
		{
			objPatientWrapper.cartCoordinator = cartCoordinatorByContactId.get(contactIdByPatientId.get(patientId));
		}
		return objPatientWrapper;
	}

	@AuraEnabled
	public static String fetchPatientDetailsForSiteCalendar(String option){
		try {
			String strJsonPatient = '';
			List<PatientsWrapper> lstPatientWrapper = new List<PatientsWrapper>();

			Map<Id, Account> patientsById = AccountsService.getPatients();
			Map<Id, Id> PersonContactIdByPatientId = new Accounts(patientsById.values()).getPersonContactIdById();

			Set<Id> patientContactIds = new Accounts(patientsById.values()).getPersonContactIds();

			Map<Id, String> treatingPhysicianNameByContactId = ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, PHYSICIAN);
			Map<Id, String> cartCoordinatorByContactId = ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, CARTCOORDINATOR);

			Map<Id, Case> carePlanByPatientId = CasesService.getCarePlanByPatientId(patientsById.keySet());

			Map<Id, Order__c> orderByPatientId = getOrderForPatientId(patientsById.keySet(), option);



			List<PatientLandingPageStatusValue__mdt> lstPatientStatus = PatientTreatmentMilestonesService.getPatientStatusValues();

			Map<Id, PatientLandingPageStatusValue__mdt> milestoneStatusValue = getPatientTreatmentMilestone(patientsById, carePlanByPatientId, orderByPatientId, lstPatientStatus);
			Map<Id,String> mrnByPatientId = AccountContactRelationsService.getPatientMRNInfo(patientsById.keySet());


			for (Order__c objOrder : orderByPatientId.values())
			{
				Account objPatient = patientsById.get(objOrder.Patient__c);
				PatientsWrapper objPatientWrapper = new PatientsWrapper();
				objPatientWrapper.memberId = objPatient.Id;
				objPatientWrapper.patientId = objPatient.PatientID__c;
				objPatientWrapper.setMemberName(objPatient.LastName, objPatient.MiddleName, objPatient.FirstName);
				objPatientWrapper.memberFirstName = objPatient.FirstName;
				objPatientWrapper.memberLastName = objPatient.LastName;
				objPatientWrapper.memberMRN = mrnByPatientId.containsKey(objPatient.Id) ? mrnByPatientId.get(objPatient.Id) : '';
				assignRelatedData(objPatientWrapper, carePlanByPatientId, objPatient.Id, treatingPhysicianNameByContactId,
						PersonContactIdByPatientId, cartCoordinatorByContactId, milestoneStatusValue);
				getApheresisDetails(objPatientWrapper,orderByPatientId,objPatient.Id);
				System.debug(objPatientWrapper);
				lstPatientWrapper.add(objPatientWrapper);
			}
			strJsonPatient = JSON.serialize(lstPatientWrapper);
			return strJsonPatient;
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	public static Map<Id, Order__c> getOrderForPatientId(Set<Id> patientIds, String option)
	{
		Map<Id, Order__c> orderByPatientId = new Map<Id, Order__c>();

		if(String.isNotBlank(option) && option == PATIENTCARD)
		{
			orderByPatientId = OrdersService.getNewAndDrugDeliveredOrdersByPatientId(patientIds);
		}
		else
		{
			orderByPatientId = OrdersService.getScheduledApheresisAndDrugDeliveryOrdersByPatientId(patientIds);
		}

		return orderByPatientId;
	}

	public static PatientsWrapper getApheresisDetails(PatientsWrapper objPatientWrapper,Map<Id, Order__c> orderByPatientId,Id patientId){
		if (!orderByPatientId.isEmpty() && orderByPatientId.containskey(patientId))
		{
			objPatientWrapper.manufacturingStatus = orderByPatientId.get(patientId).ManufacturingStatus__c;
			if (orderByPatientId.get(patientId).ApheresisPickUpDate__c != null)
			{
				objPatientWrapper.apheresisPickupDate = orderByPatientId.get(patientId).ApheresisPickUpDate__c;
				objPatientWrapper.confirmedFPDeliveryDate = orderByPatientId.get(patientId).ConfirmedFPDeliveryDate__c;
			}
		}
		return objPatientWrapper;
	}
}