objects/Account/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <description>External Patient Id For Patient Account</description>
    <externalId>true</externalId>
    <label>PatientID</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Account/fields/PreferredMethodOfCommunication__c.field-meta.xml
<CustomField>
    <fullName>PreferredMethodOfCommunication__c</fullName>
    <description>This field will be used to capture the Preferred Method of Communication.</description>
    <label>Preferred Method of Communication</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact Number</fullName>
                <default>true</default>
                <label>Primary Contact Number</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/PrimaryContactNumberType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactNumberType__c</fullName>
    <description>Primary Contact Number Type captures the type of contact stored is Home or Mobile.</description>
    <label>Primary Contact Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
                <default>true</default>
                <label>Home</label>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ApheresisSite__c.field-meta.xml
<CustomField>
    <fullName>ApheresisSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Apheresis Site recorded on Care Plan.</description>
    <label>Apheresis Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Apheresis Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Apheresis Site)</relationshipLabel>
    <relationshipName>Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/PatientID__c.field-meta.xml
<CustomField>
    <fullName>PatientID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Patient Id autonumber from The patient</description>
    <formula>Patient__r.PatientID__c</formula>
    <label>Patient ID</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the enrolled Patient.</description>
    <formula>TEXT(CarePlanID__r.Account.Status__c)</formula>
    <label>Patient Status</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>PO Status of the order.</description>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Pending</fullName>
                <default>true</default>
                <label>PO Pending</label>
            </value>
            <value>
                <fullName>PO Received</fullName>
            </value>
            <value>
                <fullName>PO Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/ProjectedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectedDeliveryDate__c</fullName>
    <description>This field is used to store Apheresis Projected Delivery Date From Anaplan</description>
    <label>Projected Delivery Date From Anaplan</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Shipping status of the order.</description>
    <label>Shipping Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipping Fresh Cells</fullName>
            </value>
            <value>
                <fullName>Fresh Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Cryo-ed Cells</fullName>
            </value>
            <value>
                <fullName>Cryo-ed Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Drug Product</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Slot status of the order.</description>
    <inlineHelpText>If the Slot Status is &apos;Slot Rejected&apos; then please select a new Apheresis Pickup Date.</inlineHelpText>
    <label>Slot Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slot Requested</fullName>
            </value>
            <value>
                <fullName>Slot Confirmed</fullName>
            </value>
            <value>
                <fullName>Slot Blocked</fullName>
                <isActive>false</isActive>
                <label>Slot Blocked</label>
            </value>
            <value>
                <fullName>Slot Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/PatientLandingPageStatusValue__mdt.object-meta.xml
<CustomObject>
    <description>Meta data type to fetch Patient Treatment Milestone for patients-TCP list view table</description>
    <label>Patient Landing Page Status Value</label>
    <pluralLabel>Patient Landing Page Status Values</pluralLabel>
</CustomObject>

objects/PatientLandingPageStatusValue__mdt/fields/CarePlanStatus__c.field-meta.xml
<CustomField>
    <fullName>CarePlanStatus__c</fullName>
    <description>Custom field to store Care Plan Status of the patient</description>
    <label>Care Plan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>Custom field to store Order Status of the patient</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientJourneyStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientJourneyStatus__c</fullName>
    <description>To display the patient status in the patient&apos;s highlight bar section- Patient journey screen</description>
    <label>Patient Journey Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/PatientLandingPageStatusValue__mdt/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <description>Custom field to store Patient Status of the patient</description>
    <label>Patient Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/TreatmentJourneySteps__mdt.object-meta.xml
<CustomObject>
    <label>Treatment Journey Steps</label>
    <pluralLabel>Treatment Journey Steps</pluralLabel>
</CustomObject>

objects/TreatmentJourneySteps__mdt/fields/ApheresisCompleted__c.field-meta.xml
<CustomField>
    <fullName>ApheresisCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the Apheresis Section progress as Completed or Active in Treatment Journey Screen</description>
    <label>Apheresis Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ApheresisPickUpSectionStatus__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpSectionStatus__c</fullName>
    <description>To populate the corresponding Apheresis Section Status based on Order, Care Plan, PO and Slot statuses in Treatment Journey Screen</description>
    <label>Apheresis Pick-Up Section Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/CarePlanStatus__c.field-meta.xml
<CustomField>
    <fullName>CarePlanStatus__c</fullName>
    <description>To store Care Plan Status as per matrix for comparison with the Care Plan Status of the Patient in Treatment Journey Screen</description>
    <label>Care Plan Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>To store Order Status as per matrix for comparison with the Order Status of the Patient in Treatment Journey Screen</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <description>To store PO Status as per matrix for comparison with the PO Status of the Patients Order in Treatment Journey Screen</description>
    <label>PO Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ShippingCompleted__c.field-meta.xml
<CustomField>
    <fullName>ShippingCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the Shipping Section progress as Completed or Active in Treatment Journey Screen</description>
    <label>Shipping Completed</label>
    <type>Checkbox</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <description>To populate the corresponding Shipping Section Status based on Order, Care Plan, PO and Slot statuses in Treatment Journey Screen</description>
    <label>Shipping Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <description>To store Slot Status as per matrix for comparison with the Slot Status of the Patients Order in Treatment Journey Screen</description>
    <label>Slot Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/PatientJourneyController.cls
public with sharing class PatientJourneyController
{
	public static final String PHYSICIAN = 'Physician';
	public static final String CARTCOORDINATOR = 'CAR-T Coordinator';
	static final String NUMBEROFDAYSFORRESCHEDULE = 'Number of Days For Reschedule';
	public static final String INFUSIONCOMPLETE = 'Infusion Complete';

	private static ContactContactRelationsService ContactContactRelationsService
	{
		get
		{
			if (null == ContactContactRelationsService)
			{
				ContactContactRelationsService =
						(ContactContactRelationsService) Application.Service.newInstance(ContactContactRelationsService.class);
			}
			return ContactContactRelationsService;
		}
		set;
	}

	private static OrdersService OrdersService
	{
		get
		{
			if (null == OrdersService)
			{
				OrdersService =
						(OrdersService) Application.Service.newInstance(OrdersService.class);
			}
			return OrdersService;
		}
		set;
	}

	private static PatientTreatmentMilestonesService PatientTreatmentMilestonesService
	{
		get
		{
			if (null == PatientTreatmentMilestonesService)
			{
				PatientTreatmentMilestonesService = (PatientTreatmentMilestonesService) Application.Service.newInstance(PatientTreatmentMilestonesService.class);
			}
			return PatientTreatmentMilestonesService;
		}
		set;
	}

	private static AccountContactRelationsService AccountContactRelationsService
	{
		get
		{
			if (null == AccountContactRelationsService)
			{
				AccountContactRelationsService = (AccountContactRelationsService) Application.Service.newInstance(AccountContactRelationsService.class);
			}
			return AccountContactRelationsService;
		}
		set;
	}

	@AuraEnabled(cacheable=true)
	public static List<ContentVersion> getDocumentsByPatientId(Id patientId){
		try
		{
			List<ContentVersion> documentsList = new List<ContentVersion>();
			List<PatientServicesEnrollee__c> patientServicesEnrolleeList =
					((PatientServicesEnrolleesSelector) Application.Selector.newInstance(PatientServicesEnrollee__c.SObjectType))
							.elevatedSelectByAccountId(new Set<Id> {patientId});

			if (!patientServicesEnrolleeList.isEmpty())
			{
				Id patientServicesEnrolleeId = patientServicesEnrolleeList[0].Id;

				List<ContentDocumentLink> contentDocuments =
						((ContentDocumentLinksSelector) Application.Selector.newInstance(ContentDocumentLink.SObjectType))
								.elevatedSelectByLinkedEntity(patientServicesEnrolleeId);

				Set<Id> contentDocumentIds =
						sflib_ArrayUtils.pluckIdField(contentDocuments, ContentDocumentLink.ContentDocumentId);

				if(!contentDocumentIds.isEmpty()){
					documentsList =
							((ContentVersionsSelector) Application.Selector.newInstance(ContentVersion.SObjectType))
									.elevatedGetContentVersionByDocumentIds(contentDocumentIds);
				}
			}
			return documentsList;
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled
	public static List<Case> fetchPatientServiceEligibilty(Id patientId)
	{
		try
		{
			Map<Id, Case> carePlanByPatientId = CasesService.fetchCarePlanByPatientId(new Set<Id> {patientId});
			return carePlanByPatientId.values();
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled(cacheable=true)
	public static List<PatientServicesEnrollee__c> fetchPatientServiceEnrollees(Id patientId)
	{
		try
		{
			Map<Id, Case> carePlanByPatientId = CasesService.fetchCarePlanByPatientId(new Set<Id> {patientId});

			Set<Id> carePlanIds = sflib_ArrayUtils.pluckIdField(carePlanByPatientId.values(), Case.Id);

			Map<Id, PatientServicesEnrollee__c> patientServicesByPatientId = PatientServicesEnrolleesService.fetchPatientServicesStatus(carePlanIds);
			return patientServicesByPatientId.values();
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled
	public static void updateCarePlan(Id patientId,String strPatientServiceProgram)
	{
		try
		{
			Boolean isPatientServiceOpted = Boolean.valueOf(strPatientServiceProgram);

			Map<Id, Boolean> isPatientServiceOptedByAccount = new Map<Id, Boolean>();
			isPatientServiceOptedByAccount.put(patientId,isPatientServiceOpted);

			CasesService.updateCarePlan(isPatientServiceOptedByAccount);

		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled
	public static void updateOrder(Id patientId,String reasonForCancellation)
	{
		try
		{
			Map<Id,Order__c> orderByPatientId = OrdersService.getOrderByPatientId(new Set<Id>{patientId});
			Orders cancelledOrders = new Orders(orderByPatientId.values());
			cancelledOrders.setReasonForCancellation(reasonForCancellation);
			cancelledOrders.setOrderStatus('Order Cancellation Requested');
			cancelledOrders.setDateOfCancellationRequestTCP(System.Today());
			List<Order__c> cancelledOrdersList = cancelledOrders.getRecords();
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			uow.registerDirty(cancelledOrdersList);
			uow.commitWork();
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled
	public static void updateDeliveryDateOnOrder(Id patientId, String dpDeliveryDate)
	{
		try
		{
			Map<Id,Order__c> orderByPatientId = OrdersService.getOrderByPatientId(new Set<Id>{patientId});
			Orders patientOrders = new Orders(orderByPatientId.values());
			patientOrders.setConfirmedFPDeliveryDate(date.valueOf(dpDeliveryDate));
			List<Order__c> patientOrdersList = patientOrders.getRecords();
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			uow.registerDirty(patientOrdersList);
			uow.commitWork();
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	@AuraEnabled
	public static void updateInfusedDateOnOrder(Id patientId, String infusedDate)
	{
		try
		{
			Map<Id,Order__c> orderByPatientId = OrdersService.getOrderByPatientId(new Set<Id>{patientId});
			Orders patientOrders = new Orders(orderByPatientId.values());
			patientOrders.setInfusionDate(date.valueOf(infusedDate));
			patientOrders.setOrderStatus(INFUSIONCOMPLETE);
			List<Order__c> patientOrdersList = patientOrders.getRecords();
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			uow.registerDirty(patientOrdersList);
			uow.commitWork();
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	public static Map<Id, PatientLandingPageStatusValue__mdt> getPatientStatus(Map<Id, Account> patientsById, Map<Id, Case> carePlanByPatientId,List<PatientLandingPageStatusValue__mdt> lstPatientStatus)
	{
		Map<Id, PatientLandingPageStatusValue__mdt> enrollmentByAccountID = new Map<Id, PatientLandingPageStatusValue__mdt>();
		for (Account objacc : patientsById.values())
		{
			for (PatientLandingPageStatusValue__mdt milestoneStatusValue : lstPatientStatus)
			{
				if (milestoneStatusValue.PatientStatus__c == objacc.Status__c
						&& carePlanByPatientId.containsKey(objacc.Id)
						&& milestoneStatusValue.CarePlanStatus__c == carePlanByPatientId.get(objacc.Id).Status)
				{
					enrollmentByAccountID.put(objacc.Id, milestoneStatusValue);
				}
			}
		}
		return enrollmentByAccountID;
	}

	@AuraEnabled(cacheable=true)
	public static String getDetailsByPatientId(Id patientId)
	{
		try
		{
			String strJsonPatient = '';
			PatientsWrapper objPatientWrapper = new PatientsWrapper();
			List<Account> patients = new List<Account>();
			patients.add(new Account(id = patientId));
			Map<Id, Account> patientsById =
					((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
							.selectById(new Set<Id> {patientId}).getById();
			Map<Id, Id> PersonContactIdByPatientId =
					((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
							.selectById(new Set<Id> {patientId}).getPersonContactIdById();
			Set<Id> patientContactIds = new Set<Id>();
			patientContactIds.addAll(PersonContactIdByPatientId.values());
			Map<Id, String> treatingPhysicianNameByContactId =
					ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, PHYSICIAN);
			Map<Id, String> cartCoordinatorByContactId =
					ContactContactRelationsService.getRelatedContactIdsByRole(patientContactIds, CARTCOORDINATOR);

			Map<Id, Order__c> orderByPatientId =
					OrdersService.elevatedGetOrderByPatientId(new Set<Id> {patientId});
			Map<Id, Case> carePlanByPatientId =
					new CasesService().elevatedGetCarePlanByPatientId(new Set<Id> {patientId});

			List<PatientLandingPageStatusValue__mdt> lstPatientStatus = PatientTreatmentMilestonesService.getPatientStatusValues();

			Map<Id, PatientLandingPageStatusValue__mdt> patientStatusByPatientId = getPatientStatus(patientsById, carePlanByPatientId, lstPatientStatus);
			Map<Id,String> mrnByPatientId = AccountContactRelationsService.getPatientMRNInfo(patientsById.keySet());

			if (PersonContactIdByPatientId.containskey(patientId) && treatingPhysicianNameByContactId.containsKey(PersonContactIdByPatientId.get(patientId)))
			{
				objPatientWrapper.treatingPhysician =
						treatingPhysicianNameByContactId.get(PersonContactIdByPatientId.get(patientId));
			}
			if (PersonContactIdByPatientId.containskey(patientId) && cartCoordinatorByContactId.containsKey(PersonContactIdByPatientId.get(patientId)))
			{
				objPatientWrapper.cartCoordinator =
						cartCoordinatorByContactId.get(PersonContactIdByPatientId.get(patientId));
			}
			getApheresisDetails(objPatientWrapper,orderByPatientId,patientId);
			getShippingStatus(objPatientWrapper,orderByPatientId,patientId);
			getManufacturingDetails(objPatientWrapper, orderByPatientId, patientId);
			getDeliveryStatus(objPatientWrapper, orderByPatientId, patientId);
			if (patientsById.containskey(patientId))
			{
				if(patientStatusByPatientId.containsKey(patientId))
				{
					objPatientWrapper.patientJourneyStatus = patientStatusByPatientId.get(patientId).PatientJourneyStatus__c;
				}
				objPatientWrapper.patientStatus = patientsById.get(patientId).Status__c;
				objPatientWrapper.memberFirstName = patientsById.get(patientId).FirstName;
				objPatientWrapper.memberLastName = patientsById.get(patientId).LastName;
				objPatientWrapper.setMemberName(patientsById.get(patientId).FirstName, patientsById.get(patientId).MiddleName, patientsById.get(patientId).LastName);
				objPatientWrapper.memberMRN = mrnByPatientId.containsKey(patientId) ? mrnByPatientId.get(patientId) : '';
				objPatientWrapper.memberDateOfBirth = patientsById.get(patientId).PersonBirthdate;
				objPatientWrapper.patientId = patientsById.get(patientId).PatientID__c;
				objPatientWrapper.memberPhone = patientsById.get(patientId).Phone;
				objPatientWrapper.patientEmail = patientsById.get(patientId).PersonEmail;
				objPatientWrapper.patientPreferredMethodOfCommunication = patientsById.get(patientId).PreferredMethodOfCommunication__c;
				objPatientWrapper.patientPrimaryContactType = patientsById.get(patientId).PrimaryContactNumberType__c;
			}
			strJsonPatient = JSON.serialize(objPatientWrapper);
			return strJsonPatient;
		}
		catch (Exception e)
		{
			AuraHandledException auraHandledException = new AuraHandledException(e.getMessage());
			auraHandledException.setMessage(e.getStackTraceString());
			throw auraHandledException;
		}
	}

	public static PatientsWrapper getApheresisStatus(PatientsWrapper objPatientWrapper, Order__c order)
	{
		String carePlanStatus = order.CarePlanID__r.Status;
		String orderStatus = order.OrderStatus__c;
		String slotStatus = order.SlotStatus__c;
		String poStatus = order.POStatus__c;
		List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
				Application.Selector.newinstance(TreatmentJourneySteps__mdt.SObjectType))
				.selectApheresisStepsByStatuses(carePlanStatus, orderStatus, slotStatus, poStatus);
		if (!treatmentJourneySteps.isEmpty())
		{
			objPatientWrapper.apheresisPickupStatus = treatmentJourneySteps[0].ApheresisPickUpSectionStatus__c;
			objPatientWrapper.isApheresisCompleted = treatmentJourneySteps[0].ApheresisCompleted__c;
		}
		return objPatientWrapper;
	}

	public static PatientsWrapper getShippingStatus(PatientsWrapper objPatientWrapper,Map<Id, Order__c> orderByPatientId,Id patientId)
	{
		if (!orderByPatientId.isEmpty() && orderByPatientId.containskey(patientId))
		{
			String carePlanStatus = orderByPatientId.get(patientId).CarePlanID__r.Status;
			String orderStatus = orderByPatientId.get(patientId).OrderStatus__c;
			String slotStatus = orderByPatientId.get(patientId).SlotStatus__c;
			String poStatus = orderByPatientId.get(patientId).POStatus__c;
			String shippingStatus = orderByPatientId.get(patientId).ShippingStatus__c;
			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newinstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectShippingStepsByStatuses(carePlanStatus, orderStatus, slotStatus, poStatus, shippingStatus);

			if (!treatmentJourneySteps.isEmpty())
			{
				objPatientWrapper.projectedDeliveryDate = orderByPatientId.get(patientId).ProjectedDeliveryDate__c;
				objPatientWrapper.apheresisPickupStatus = treatmentJourneySteps[0].ApheresisPickUpSectionStatus__c;
				objPatientWrapper.isApheresisCompleted = treatmentJourneySteps[0].ApheresisCompleted__c;
				objPatientWrapper.shippingStatus = treatmentJourneySteps[0].ShippingStatus__c;
				objPatientWrapper.isShippingCompleted = treatmentJourneySteps[0].ShippingCompleted__c;
			}
		}
		return objPatientWrapper;
	}

	public static PatientsWrapper getApheresisDetails(PatientsWrapper objPatientWrapper,Map<Id, Order__c> orderByPatientId,Id patientId){
		if (!orderByPatientId.isEmpty() && orderByPatientId.containskey(patientId))
		{
			getApheresisStatus(objPatientWrapper, orderByPatientId.get(patientId));
			if (orderByPatientId.get(patientId).ApheresisPickUpDate__c != null)
			{
				objPatientWrapper.projectedDeliveryDate = orderByPatientId.get(patientId).ProjectedDeliveryDate__c;
				objPatientWrapper.apheresisPickupSite = orderByPatientId.get(patientId).ApheresisSite__r.Name;
				objPatientWrapper.apheresisCryoType = orderByPatientId.get(patientId).CryoType__c;
				objPatientWrapper.apheresisPickupDate = orderByPatientId.get(patientId).ApheresisPickUpDate__c;
				objPatientWrapper.apheresisSitePO = orderByPatientId.get(patientId).SitePO__c;
			}
			objPatientWrapper.orderStatus = orderByPatientId.get(patientId).OrderStatus__c;
			objPatientWrapper.orderCancellationRequestDate = orderByPatientId.get(patientId).DateOfCancellationRequestTCP__c;
			objPatientWrapper.carePlanStatus = orderByPatientId.get(patientId).CarePlanID__r.Status;
			objPatientWrapper.cryoType = orderByPatientId.get(patientId).CryoType__c;
		}
		return objPatientWrapper;
	}

	public static PatientsWrapper getManufacturingDetails(PatientsWrapper objPatientWrapper, Map<Id, Order__c> orderByPatientId, Id patientId)
	{
		if (!orderByPatientId.isEmpty() && orderByPatientId.containskey(patientId))
		{
			String carePlanStatus = orderByPatientId.get(patientId).CarePlanID__r.Status;
			String orderStatus = orderByPatientId.get(patientId).OrderStatus__c;
			String slotStatus = orderByPatientId.get(patientId).SlotStatus__c;
			String poStatus = orderByPatientId.get(patientId).POStatus__c;
			String manufacturingStatus = orderByPatientId.get(patientId).ManufacturingStatus__c;

			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newinstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectManufacturingStepsByStatuses(carePlanStatus, orderStatus, slotStatus, poStatus,manufacturingStatus );
			if (!treatmentJourneySteps.isEmpty())
			{
				objPatientWrapper.apheresisPickupStatus = treatmentJourneySteps[0].ApheresisPickUpSectionStatus__c;
				objPatientWrapper.isApheresisCompleted = treatmentJourneySteps[0].ApheresisCompleted__c;
				objPatientWrapper.shippingStatus = treatmentJourneySteps[0].ShippingStatus__c;
				objPatientWrapper.isShippingCompleted = treatmentJourneySteps[0].ShippingCompleted__c;
				objPatientWrapper.manufacturingStatus = treatmentJourneySteps[0].ManufacturingStatus__c;
				objPatientWrapper.isManufacturingCompleted = treatmentJourneySteps[0].ManufacturingCompleted__c;

			}
		}
		return objPatientWrapper;
	}

	public static PatientsWrapper getDeliveryStatus(PatientsWrapper objPatientWrapper,Map<Id, Order__c> orderByPatientId,Id patientId)
	{
		if (!orderByPatientId.isEmpty() && orderByPatientId.containskey(patientId))
		{
			String carePlanStatus = orderByPatientId.get(patientId).CarePlanID__r.Status;
			String orderStatus = orderByPatientId.get(patientId).OrderStatus__c;
			String slotStatus = orderByPatientId.get(patientId).SlotStatus__c;
			String poStatus = orderByPatientId.get(patientId).POStatus__c;
			String shippingStatus = orderByPatientId.get(patientId).ShippingStatus__c;
			String manufacturingStatus = orderByPatientId.get(patientId).ManufacturingStatus__c;
			String deliveryStatus = orderByPatientId.get(patientId).ShippingStatus__c;

			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newinstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectDeliveryStepsByStatuses(carePlanStatus, orderStatus, slotStatus, poStatus, shippingStatus, manufacturingStatus, deliveryStatus);

			if (!treatmentJourneySteps.isEmpty())
			{
				objPatientWrapper.apheresisPickupStatus = treatmentJourneySteps[0].ApheresisPickUpSectionStatus__c;
				objPatientWrapper.isApheresisCompleted = treatmentJourneySteps[0].ApheresisCompleted__c;
				objPatientWrapper.shippingStatus = treatmentJourneySteps[0].ShippingStatus__c;
				objPatientWrapper.isShippingCompleted = treatmentJourneySteps[0].ShippingCompleted__c;
				objPatientWrapper.manufacturingStatus = treatmentJourneySteps[0].ManufacturingStatus__c;
				objPatientWrapper.isManufacturingCompleted = treatmentJourneySteps[0].ManufacturingCompleted__c;
				objPatientWrapper.isDeliveryCompleted = treatmentJourneySteps[0].DeliveryCompleted__c;
				objPatientWrapper.deliveryStatus = treatmentJourneySteps[0].DeliveryStatus__c;
				objPatientWrapper.estimatedDrugProductDeliveryDate = orderByPatientId.get(patientId).EstimatedDrugProductDeliveryDate__c;
				objPatientWrapper.confirmedFPDeliveryDate = orderByPatientId.get(patientId).ConfirmedFPDeliveryDate__c;
				objPatientWrapper.isInfusionCompleted = treatmentJourneySteps[0].InfusionCompleted__c;
				objPatientWrapper.infusionStatus = treatmentJourneySteps[0].InfusionStatus__c;
				objPatientWrapper.infusionDate = orderByPatientId.get(patientId).InfusionDate__c;
			}
		}
		return objPatientWrapper;
	}

	@AuraEnabled(cacheable=true)
	public static Boolean isBussinessDayDueForReschedule(Id patientId)
	{
		List<Account> patients = new List<Account>();
		patients.add(new Account(id = patientId));
		Map<Id, Account> patientsById =
				((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
						.selectById(new Set<Id> {patientId}).getById();
		Map<Id, Order__c> orderByPatientId =
				OrdersService.elevatedGetOrderByPatientId(new Set<Id> {patientId});

		List<BusinessHours> businessHours = ((BusinessHoursSelector) Application.Selector.newInstance(BusinessHours.SObjectType))
				.selectBusinessHoursByName(Label.BusinessHoursNameForOrderSubmissionRescheduling);
		BusinessHoursCalculatorImp bhCalculatorImp = new BusinessHoursCalculatorImp(businessHours[0].Id);
		Integer noOfDays = Integer.valueOf(bhCalculatorImp.getDifferenceBetweenTimeSpans(Date.today(), orderByPatientId.get(patientId).ApheresisPickUpDate__c) / BusinessHoursCalculator.oneDayToMilliSeconds);

		sflib_Settings__c noOfDaysAllowed = sflib_Settings__c.getValues(NUMBEROFDAYSFORRESCHEDULE);

		if(noOfDays > Integer.ValueOf(NoOfDaysAllowed.Value__c)){
			return true;
		}
		return false;
	}

	@AuraEnabled
	public static Date getNextThreeBussinessDays(String startDate)
	{
		Date stDate = date.valueOf(startDate);
		Date estimatedDate = OrdersService.getEstimatedDate(stDate);
		return estimatedDate;
	}

}