objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/recordTypes/ApheresisSite.recordType-meta.xml
<RecordType>
    <fullName>ApheresisSite</fullName>
    <active>true</active>
    <description>Represents an apheresis site</description>
    <label>Apheresis Site</label>
</RecordType>

objects/Account/recordTypes/CryoSite.recordType-meta.xml
<RecordType>
    <fullName>CryoSite</fullName>
    <active>true</active>
    <description>Represents a cryo site</description>
    <label>Cryo Site</label>
</RecordType>

objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contact.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__AccountAccountRelation__c/HealthCloudGA__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as between a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCloudGA__CarePlanGoal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used to indicate the status of the Goal based on the status of the Tasks related to the Goal.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CryoSite__c.field-meta.xml
<CustomField>
    <fullName>CryoSite__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cryo Site recorded on Care Plan.</description>
    <label>Cryo Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Cryo Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Cryo Site)</relationshipLabel>
    <relationshipName>Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CryoType__c.field-meta.xml
<CustomField>
    <fullName>CryoType__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Cryo type related to the associated cryo site.</description>
    <label>Cryo Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
                <isActive>false</isActive>
                <label>3rd Party</label>
            </value>
            <value>
                <fullName>Raritan</fullName>
                <isActive>false</isActive>
                <label>Raritan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/PatientStatus__c.field-meta.xml
<CustomField>
    <fullName>PatientStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the enrolled Patient.</description>
    <formula>TEXT(CarePlanID__r.Account.Status__c)</formula>
    <label>Patient Status</label>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Slot status of the order.</description>
    <inlineHelpText>If the Slot Status is &apos;Slot Rejected&apos; then please select a new Apheresis Pickup Date.</inlineHelpText>
    <label>Slot Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slot Requested</fullName>
            </value>
            <value>
                <fullName>Slot Confirmed</fullName>
            </value>
            <value>
                <fullName>Slot Blocked</fullName>
                <isActive>false</isActive>
                <label>Slot Blocked</label>
            </value>
            <value>
                <fullName>Slot Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/UpdateOrderStatusBatchTest.cls
@isTest(seeAllData=false)
public class UpdateOrderStatusBatchTest
{
	public static final String CENTRAL = 'Central';
	public static final String THIRDPARTY = '3rd party';

	//GIVEN Test Data for Updating the Order & related records status to In Progress
	@testSetup
	private static void setUpTestData()
	{
		List<String> listOfSitesNames = new List<String>();
		List<Contact> contactList = new List<Contact>();
		List<Account> accToBeInserted = TestDataFactory.getPatientAccountsList();
		Id PatientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.PatientRecordtype).getRecordTypeId();
		listOfSitesNames.add('TreatmentSite');
		listOfSitesNames.add('ApheresisSite');
		listOfSitesNames.add('CryoSite');

		for (String siteName : listOfSitesNames)
		{
			accToBeInserted.add(TestDataFactory.getBusinessAccountToInsert(siteName));
		}
		insert accToBeInserted;
		List<Account> accountsToBeUpdated = new List<Account>();
		for (Account site : accToBeInserted)
		{
			if (PatientRecordTypeId.equals(site.RecordTypeId))
			{
				site.Status__c = StaticConstants.PatientStatusVerified;
				accountsToBeUpdated.add(site);
			}
			else
			{
				contactList.add(TestDataFactory.getBusinessAccRelatedContacts(site.Name, site.Id));
			}
		}
		update accountsToBeUpdated;
		insert contactList;

		List<HealthCloudGA__ReciprocalRole__c> roleList = new List<HealthCloudGA__ReciprocalRole__c>();

		HealthCloudGA__ReciprocalRole__c carTRole = TestDataFactory.getContactRole('CAR-T Coordinator', 'ContactRole');
		HealthCloudGA__ReciprocalRole__c aphSiteRole1 = TestDataFactory.getContactRole('Aphresis Site', 'AccountRole');
		HealthCloudGA__ReciprocalRole__c cryoSiteRole1 = TestDataFactory.getContactRole('Cryo Site', 'AccountRole');

		roleList.add(carTRole);
		roleList.add(aphSiteRole1);
		roleList.add(cryoSiteRole1);
		insert roleList;

		List<Account> accList = [select Id, (select Id,AccountId from Contacts) from Account LIMIT 5];
		List<Contact> conList = new List<Contact>();

		for (Account acc : accList)
		{
			conList.add(acc.Contacts);
		}

		List<HealthCloudGA__ContactContactRelation__c> conRelationList = new List<HealthCloudGA__ContactContactRelation__c>();
		HealthCloudGA__ContactContactRelation__c conRel1 = TestDataFactory.getContactRelationsToInsert(contactList[0].Id, conList[0].Id, carTRole.Id);
		conRelationList.add(conRel1);
		HealthCloudGA__ContactContactRelation__c conRel2 = TestDataFactory.getContactRelationsToInsert(contactList[1].Id, conList[1].Id, carTRole.Id);
		conRelationList.add(conRel2);
		insert conRelationList;
		List<HealthCloudGA__AccountAccountRelation__c> accRelationList = new List<HealthCloudGA__AccountAccountRelation__c>();
		HealthCloudGA__AccountAccountRelation__c accRel1 = TestDataFactory.getAccountRelationsToInsert(accToBeInserted[0].Id, accToBeInserted[1].Id, aphSiteRole1.Id);
		accRelationList.add(accRel1);
		HealthCloudGA__AccountAccountRelation__c accRel2 = TestDataFactory.getAccountRelationsToInsert(accToBeInserted[1].Id, accToBeInserted[3].Id, cryoSiteRole1.Id);
		accRelationList.add(accRel2);

		insert accRelationList;

		List<Case> caseList = TestDataFactory.getCareplanCasesList(conList);
		insert caseList;

		Id cryoSiteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName()
				.get(StaticConstants.CRYOSITELABEL)
				.getRecordTypeId();

		List<Account> cryoSiteAccountsList = new AccountsSelector().selectByDeveloperName(cryoSiteRecordTypeId);
		cryoSiteAccountsList[0].Type = THIRDPARTY;

		update cryoSiteAccountsList;

		List<Order__c> ordersList = new OrdersSelector().selectOrdersByCarePlanId((new Map<Id, Case>(caseList)).keySet());
		List<Order__c> updatedOrders = new List<Order__c>();

		for (Order__c order : ordersList)
		{
			order.CryoSite__c = cryoSiteAccountsList[0].Id;
			updatedOrders.add(order);
		}

		update updatedOrders;

		testDataSetup2(caseList);
	}

	private static void testDataSetup2(List<Case> caseList)
	{
		List<Id> caseIds = new List<Id>();
		for (Case cs : caseList)
		{
			caseIds.add(cs.Id);
		}
		List<HealthCloudGA__CarePlanGoal__c> listOfGoals = TestDataFactory.getGoalsForCaseIds(caseIds);
		insert listOfGoals;

		List<Task> taskList = TestDataFactory.getTasksForGoalIds(listOfGoals);
		insert taskList;

		List<Order__c> orderList = [select Id,SlotStatus__c,OrderStatus__c,PatientStatus__c,CarePlanId__c,CryoType__c,CryoSite__c,CryoSite__r.Type,ApheresisPickUpDate__c from Order__c where CarePlanId__c IN:caseIds LIMIT 5];
		for (Order__c ord : orderList)
		{
			ord.CryoType__c = CENTRAL;
			ord.ApheresisPickUpDate__c = system.today();
		}
		update orderList;

	}

	@isTest static void itShouldExecuteOrderStatusBatch()
	{
		//WHEN the Order PO Status is PO Received and Slot Status is Soft Slot Confirmed and Cryo Site is Central and Apheresis Pickup Date is Today and Patient Status is Verified
		String CRON_EXP = '0 0 0 15 3 ? *';

		Test.startTest();
		String jobId = System.schedule('Test', CRON_EXP, new UpdateOrderStatusBatchSchedulable());
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
		System.assertEquals(CRON_EXP, ct.CronExpression);
		System.assertEquals(0, ct.TimesTriggered);
		UpdateOrderStatusBatch bt = new UpdateOrderStatusBatch();
		Database.executeBatch(bt);
		Test.stopTest();
		List<Order__c> ordList = [select Id,OrderStatus__c,CarePlanId__r.Status,CryoType__c from Order__c where OrderStatus__c = :StaticConstants.orderInProgressStatus LIMIT 5];
		Map<Id, HealthCloudGA__CarePlanGoal__c> goalsMap = new Map<Id, HealthCloudGA__CarePlanGoal__c>([select Id,name,Status__c from HealthCloudGA__CarePlanGoal__c where Status__c = :StaticConstants.inProgressStatus LIMIT 5]);
		List<Task> tasksList = [select Status from Task where Status = :StaticConstants.inProgressStatus];

		//THEN the Goal Status and related Tasks Status should be updated as In Progress
		system.assert(!goalsMap.values().isEmpty());
		system.assert(!tasksList.isEmpty());
	}

}