objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Account/recordTypes/ApheresisSite.recordType-meta.xml
<RecordType>
    <fullName>ApheresisSite</fullName>
    <active>true</active>
    <description>Represents an apheresis site</description>
    <label>Apheresis Site</label>
</RecordType>

objects/Account/recordTypes/CryoSite.recordType-meta.xml
<RecordType>
    <fullName>CryoSite</fullName>
    <active>true</active>
    <description>Represents a cryo site</description>
    <label>Cryo Site</label>
</RecordType>

objects/Account/recordTypes/HealthSystem.recordType-meta.xml
<RecordType>
    <fullName>HealthSystem</fullName>
    <active>true</active>
    <description>Represents a health system</description>
    <label>Health System</label>
</RecordType>

objects/Account/recordTypes/SpecialtyDistributor.recordType-meta.xml
<RecordType>
    <fullName>SpecialtyDistributor</fullName>
    <active>true</active>
    <description>Represents a specialty distributor</description>
    <label>Specialty Distributor</label>
</RecordType>

objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contact.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__AccountAccountRelation__c/HealthCloudGA__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as between a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SiteProduct__c/SiteProduct__c.object-meta.xml
<CustomObject>
    <label>Site-Product</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Site Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site-Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SiteProduct__c/fields/REMSID__c.field-meta.xml
<CustomField>
    <fullName>REMSID__c</fullName>
    <externalId>true</externalId>
    <label>REMS ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/SiteProduct__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Site-Product</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/SiteProductsSharingBatchSchedulerTest.cls
@isTest
public class SiteProductsSharingBatchSchedulerTest {
    private static final String BATCHNAME = 'Sharing SiteProduct Accounts Records Batch';
    private static final String HYPEN = ' - ';
    private static final String CRONEXPR_FORDAILYSTARTOFDAY = '0 0 0 ? * * *';
    private static final String INDUSTRIESBUSINESS = 'IndustriesBusiness';
    private static final String SPECIALTYDISTRIBUTOR = 'SpecialtyDistributor';
    private static final String TESTLOCATION = 'Test Location';
    private static final String HEALTHSYSTEM = 'HealthSystem';
    private static final String PATIENTRECORDTYPEDEVELOPERNAME = 'Patient';

    @testSetup
    private static void setUpTestData()
    {
        List<Account> accToBeInserted = TestDataFactory.getPatientAccountsList();
        List<String> listOfSitesNames = new List<String>();
        listOfSitesNames.add(StaticConstants.TreatmentSiteRecordTypeDeveloperName);
        listOfSitesNames.add(StaticConstants.APHERESISSITE);
        listOfSitesNames.add(StaticConstants.CRYOSITE);
        listOfSitesNames.add(SPECIALTYDISTRIBUTOR);
        listOfSitesNames.add(HEALTHSYSTEM);

        for (String siteName : listOfSitesNames)
        {
            accToBeInserted.addAll(TestdataFactory.getBusinessAccountsList(siteName, 3));
        }
        insert accToBeInserted;

        List<Account> accountsToBeUpdated = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        Id patientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.PatientRecordtype).getRecordTypeId();
        Id trtSiteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            						.get(StaticConstants.TreatmentSiteRecordTypeDeveloperName)
            						.getRecordTypeId();
        Id aphSiteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            						.get(StaticConstants.APHERESISSITE)
            						.getRecordTypeId();
        Id cryoSiteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            						.get(StaticConstants.CRYOSITE)
            						.getRecordTypeId();
        Id specialtyDistributorId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
                                	.get(SPECIALTYDISTRIBUTOR)
            						.getRecordTypeId();
        Id healthSystemRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            						.get(HEALTHSYSTEM)
            						.getRecordTypeId();
        List<Id> treatmentSiteIds = new List<Id>();
        List<Id> apheresisSiteIds = new List<Id>();
        List<Id> cryoSiteIds = new List<Id>();
        List<Id> SDIds = new List<Id>();
        List<Id> healthSystemIds = new List<Id>();
        for (Account site : accToBeInserted)
        {
            if (patientRecordTypeId.equals(site.RecordTypeId))
            {
                site.Status__c = StaticConstants.PatientStatusVerified;
                accountsToBeUpdated.add(site);
            }
            else
            {
                contactList.add(TestDataFactory.getBusinessAccRelatedContacts(site.Name, site.Id));
                site.Type = StaticConstants.cryoSiteLocal;
                accountsToBeUpdated.add(site);
                if(healthSystemRecordTypeId.equals(site.RecordTypeId))
                {
                    healthSystemIds.add(site.Id);
                }
                else if (trtSiteRecordTypeId.equals(site.RecordTypeId))
                {
                    treatmentSiteIds.add(site.Id);
                }
                else if (aphSiteRecordTypeId.equals(site.RecordTypeId))
                {
                    apheresisSiteIds.add(site.Id);
                }
                else if (cryoSiteRecordTypeId.equals(site.RecordTypeId))
                {
                    cryoSiteIds.add(site.Id);
                }

                else
                {
                    SDIds.add(site.Id);
                }
            }
        }
        update accountsToBeUpdated;

        List<Product2> productList = TestDataFactory.getProductsList('JNJ-4528', 3);
        insert productList;

        List<SiteProduct__c> siteProductsList = TestDataFactory.getSiteProducts(treatmentSiteIds, SDIds, productList);
        insert siteProductsList;

        siteProductsList.get(0).REMSID__c = '232';
        Update siteProductsList;

        insert contactList;

        List<Schema.Location> locationsList = TestDataFactory.getLocationRecords(TESTLOCATION, 3);
        insert locationsList;

        List<Schema.AssociatedLocation> assLocList = TestDataFactory.getAssociatedLocationRecordsBasedOnSiteName(cryoSiteIds, locationsList, 3);
        insert assLocList;

        List<Schema.AssociatedLocation> assLocListforTreatmentSites = TestDataFactory.getAssociatedLocationRecordsBasedOnSiteName(treatmentSiteIds,locationsList,3);
        insert assLocListforTreatmentSites;

        system.assertNotEquals(NULL, assLocList[0].Id);

        List<Contact> businessContactsList = ((ContactsSelector) Application.Selector
                                              .newInstance(Contact.SObjectType))
            .selectAllByRecTypeDeveloperName(new Set<String> {INDUSTRIESBUSINESS});
        system.assertNotEquals(NULL, businessContactsList[0].Id);

        List<HealthCloudGA__ReciprocalRole__c> reciprocalRolesList = new List<HealthCloudGA__ReciprocalRole__c>();

        HealthCloudGA__ReciprocalRole__c carTCoordinatorRole = TestDataFactory.getContactRole(StaticConstants.CARTCOORDINATOR, StaticConstants.contactRole);
        reciprocalRolesList.add(carTCoordinatorRole);

        HealthCloudGA__ReciprocalRole__c aphSiteRole = TestDataFactory.getContactRole(Label.RoleAphresisSite, StaticConstants.accountRole);
        reciprocalRolesList.add(aphSiteRole);

        HealthCloudGA__ReciprocalRole__c cryoSiteRole = TestDataFactory.getContactRole(StaticConstants.CRYOSITELABEL, StaticConstants.accountRole);
        reciprocalRolesList.add(cryoSiteRole);
        insert reciprocalRolesList;

        List<Account> accountsList = new AccountsSelector().selectAllContactsForAccount(patientRecordTypeId);
        List<Contact> conList = new List<Contact>();
        for (Account acc : accountsList)
        {
            conList.add(acc.Contacts);
        }

        List<Id> conIdList = new List<Id>();
        conIdList.addAll(sflib_ArrayUtils.pluckIdField(conList, Contact.Id));

        List<Id> contactIdList = new List<Id>();
        contactIdList.addAll(sflib_ArrayUtils.pluckIdField(businessContactsList, Contact.Id));

        List<HealthCloudGA__ContactContactRelation__c> associatedContactsList = new List<HealthCloudGA__ContactContactRelation__c>();
        associatedContactsList = TestDataFactory.getAssociatedContactRelationsToInsert(contactIdList, conIdList, carTCoordinatorRole.Name, StaticConstants.contactRole, 2);
        insert associatedContactsList;

        List<HealthCloudGA__AccountAccountRelation__c> accRelationList =
            new List<HealthCloudGA__AccountAccountRelation__c>();
        accRelationList.addAll(TestDataFactory.getAccountRelationsToInsertBasedOnSites(treatmentSiteIds, apheresisSiteIds, aphSiteRole.Id, 2));
        accRelationList.addAll(TestDataFactory.getAccountRelationsToInsertBasedOnSites(apheresisSiteIds, cryoSiteIds, cryoSiteRole.Id, 2));
        insert accRelationList;
        system.assertNotEquals(NULL, accRelationList[0].Id);
    }

    @isTest
    static void itShouldExecuteSiteProductsSharingBatchScheduler()
    {
        //GIVEN When I'm on patient record
        Test.startTest();

        //WHEN i create a relationship Product via Site-Product related list
        SiteProductsSharingBatchScheduler batchJob = new SiteProductsSharingBatchScheduler();
        Database.executeBatch(batchJob);
        SiteProductsSharingBatchScheduler.scheduleBatch();

        Map<Id, Account> treatmentSiteByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
                                                           .selectAll()
                                                           .getByRecordTypeDeveloperName(new Set<String> {StaticConstants.TreatmentSiteRecordTypeDeveloperName}))
            												.getById();
        List<AccountShare> accShareList = new AccountSharesSelector().selectSObjectSharesBySObjectIds(treatmentSiteByIds.keySet());

        //THEN treatmentSite will be shared from AccountShare Object
        system.assert(!accShareList.isEmpty());
        Test.stopTest();
    }

}