objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification__c/fields/AssignedTo__c.field-meta.xml
<CustomField>
    <fullName>AssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User to whom the alert has been assigned</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Notification__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The detailed description of the Alert created for the user</description>
    <label>Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

objects/Notification__c/fields/ReadStatus__c.field-meta.xml
<CustomField>
    <fullName>ReadStatus__c</fullName>
    <description>Used to track whether the user has read the alert or not</description>
    <label>Read Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Unread</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>Salesforce Id of the record associated with the alert</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the alert to control number of alerts visible to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>The Subject of the alert</description>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/NotificationEngine__mdt.object-meta.xml
<CustomObject>
    <label>Notification Engine</label>
    <pluralLabel>Notification Engine</pluralLabel>
</CustomObject>

objects/NotificationEngine__mdt/fields/NotificationBody__c.field-meta.xml
<CustomField>
    <fullName>NotificationBody__c</fullName>
    <label>Notification Body</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/NotificationEngine__mdt/fields/NotificationSubject__c.field-meta.xml
<CustomField>
    <fullName>NotificationSubject__c</fullName>
    <label>Notifcation Subject</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ReasonforReschedule__c.field-meta.xml
<CustomField>
    <fullName>ReasonforReschedule__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Reason for Re-schedule of the apheresis pick-up date.</description>
    <label>Reason for Reschedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient Health</fullName>
            </value>
            <value>
                <fullName>Patient Scheduling Conflict</fullName>
            </value>
            <value>
                <fullName>Site Scheduling Conflict</fullName>
            </value>
            <value>
                <fullName>Weather/Travel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SpecifyTheOtherReasonForReschedule__c.field-meta.xml
<CustomField>
    <fullName>SpecifyTheOtherReasonForReschedule__c</fullName>
    <description>This field stores the reason of rescheduling order when user reschedules the order submission</description>
    <label>Specify The Other Reason For Reschedule</label>
    <type>TextArea</type>
</CustomField>

classes/NotificationsService.cls
public with sharing class NotificationsService
{
	private static final String activeStatus = 'Active';
	private static final String OTHERREASONFORRESCHEDULE = 'Other';
	private static final String readStatus = 'Unread';

	public void createNotificationRecords(List<Account> patientsList, List<NotificationEngine__mdt> notificationEngineList, List<User> cartCoordinatorRecords, List<Order__c> orderRecords)
	{
		List<Notification__c> notificationAlerts = new List<Notification__c>();
		for (Account patientInstance : patientsList)
		{
			Notification__c notificationsInstance = new Notification__c();
			notificationsInstance.AssignedTo__c = cartCoordinatorRecords[0].id;
			notificationsInstance.OwnerId = cartCoordinatorRecords[0].id;
			notificationsInstance.RelatedRecordId__c = patientInstance.Id;
			notificationsInstance.Subject__c = notificationEngineList[0].NotificationSubject__c.replace('<Patient Name>', (patientInstance.FirstName != null ? patientInstance.LastName + ', ' + patientInstance.FirstName : ''));
			notificationsInstance.Message__c = notificationEngineList[0].NotificationBody__c.replace('<Patient Name>', (patientInstance.FirstName != null ? patientInstance.LastName + ', ' + patientInstance.FirstName : ''));
			updateNotificationBodyForPickupDateAndReason(notificationsInstance, orderRecords);
			notificationsInstance.ReadStatus__c = readStatus;
			notificationsInstance.Status__c = activeStatus;
			notificationAlerts.add(notificationsInstance);
		}
		if (!notificationAlerts.isEmpty())
		{
			NotificationsService.createAlertNotifications(notificationAlerts);
		}
	}

	@TestVisible
	private void updateNotificationBodyForPickupDateAndReason(Notification__c notificationsInstance, List<Order__c> orderRecords)
	{
		if (notificationsInstance.Message__c.contains('<Apheresis Pick-Up Date>') && orderRecords[0].ApheresisPickUpDate__c != null)
		{
			String ApheresisPickUpDate = 'MMM dd, yyyy';
			Datetime formattedDate = Datetime.newInstance(orderRecords[0].ApheresisPickUpDate__c.year(), orderRecords[0].ApheresisPickUpDate__c.month(), orderRecords[0].ApheresisPickUpDate__c.day());
			notificationsInstance.Message__c = notificationsInstance.Message__c.replace('<Apheresis Pick-Up Date>', (orderRecords[0].ApheresisPickUpDate__c != null ? formattedDate.format(ApheresisPickUpDate) : ''));
			if (orderRecords[0].ReasonforReschedule__c == OTHERREASONFORRESCHEDULE && orderRecords[0].ReasonforReschedule__c != null)
			{
				notificationsInstance.Message__c = notificationsInstance.Message__c.replace('<Reason for Rescheduling>', (orderRecords[0].SpecifyTheOtherReasonForReschedule__c != null ? orderRecords[0].SpecifyTheOtherReasonForReschedule__c : ''));
			}
			else
			{
				notificationsInstance.Message__c = notificationsInstance.Message__c.replace('<Reason for Rescheduling>', (orderRecords[0].ReasonforReschedule__c != null ? orderRecords[0].ReasonforReschedule__c : ''));
			}
		}
	}

	public static void createAlertNotifications(List<Notification__c> notificationAlerts)
	{
		try
		{
			fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
			uow.registerNew(notificationAlerts);
			uow.commitWork();
		}
		catch (Exception excp)
		{
			Application.logEntry.error(excp);
		}
	}
}