objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the account.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Verification</fullName>
            </value>
            <value>
                <fullName>Additional Information Requested</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the contact.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <description>Custom alerts information for TCP users</description>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOT-{0000}</displayFormat>
        <label>Notification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Notification__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>Salesforce Id of the record associated with the alert</description>
    <label>Related Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the alert to control number of alerts visible to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

classes/PatientsListViewControllerTest.cls
@IsTest(SeeAllData=false)
private class PatientsListViewControllerTest
{
    private static final String CASEMANAGER = 'CaseManager';
    public static final String INTERNALBASEUSER = 'Internal Base User';
	public static final String PATIENT = 'Patient';
    public static final String PATIENTMANAGEMENT = 'PatientManagement';
	static List<User> userList;
    
	static void init()
	{
		userList = TestDataFactory.getUsersToInsert(INTERNALBASEUSER, 10);
		insert userList;

		Set<String> permissionSets = new Set<String>();
		permissionSets.add(PATIENTMANAGEMENT);
        permissionSets.add(CASEMANAGER);

		List<PermissionSetAssignment> permissionSetAssignments = TestDataFactory.assignPermissionSets(permissionSets, userList[0]);
		insert permissionSetAssignments;

	}

	@TestSetup
	static void testSetupMethod()
	{
		init();
		System.runAs(userList[0])
		{
			List<Account> accountsList = TestDataFactory.getPatientAccountsList();
			insert accountsList;

			List<Notification__c> notificationList = TestDataFactory.getNotificationList(5, null);
			Integer i = 0;
			for (Notification__c notification : notificationList)
			{
				notification.RelatedRecordId__c = accountsList[i].id;
				i++;
			}
			notificationList[i-1].RelatedRecordId__c = accountsList[0].id;
			insert notificationList;
		}
	}

	static testMethod void itShouldGetAllAccounts()
	{
		//GIVEN - The patients are enrolled in the system
		Test.startTest();
		//WHEN - Community user lands on the TCP landing page
		String strPatientDetails = PatientsListViewController.fetchPatientDetails();
		Test.stopTest();
		List<PatientsWrapper> lstPatients = (List<PatientsWrapper>) JSON.deserialize(strPatientDetails, List<PatientsWrapper>.Class);
		//THEN - Community user should be able to see the enrolled patients
		System.assertEquals(7, lstPatients.size());
	}

	static testMethod void itShouldGetPatientTreatmentMilestone()
	{
		//GIVEN - The patients are enrolled in the system
		Test.startTest();
		//WHEN - Community user lands on the TCP landing page
		Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
				.selectAll()
				.getByRecordTypeDeveloperName(new Set<String> {PATIENT}))
				.getById();
		for (Account objAccount : patientByIds.values())
		{
			objAccount.Status__c = 'Verified';
		}
		update patientByIds.values();

		Map<Id, Contact> contactsByAccountIds =
				((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
						.selectByAccountId(new Set<Id> {patientByIds.values()[0].Id}).getContactsByAccountId();

		List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
		carePlanList[0].Status = 'Manufacturing';
		insert carePlanList;

		List<Order__c> ordersList = ((OrdersSelector) Application.Selector
				.newInstance(Order__c.SObjectType))
				.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});
		ordersList[0].OrderStatus__c = 'Drug Product Delivery Date Scheduled';
		update ordersList;

		String strPatientDetails = PatientsListViewController.fetchPatientDetails();
		Test.stopTest();
		List<PatientsWrapper> lstPatients = (List<PatientsWrapper>) JSON.deserialize(strPatientDetails, List<PatientsWrapper>.Class);
		//THEN - Community user should be able to see the enrolled patients
		System.assertEquals(7, lstPatients.size(), 'Success');
	}

	static testMethod void itShouldFetchPatientDetailsForSiteCalendar()
	{
		//GIVEN - The patients are enrolled in the system
		Test.startTest();
		//WHEN - Community user lands on the TCP landing page
		Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
				.selectAll()
				.getByRecordTypeDeveloperName(new Set<String> {PATIENT}))
				.getById();
		Map<Id, Contact> contactsByAccountIds =
				((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
						.selectByAccountId(new Set<Id>{patientByIds.values()[0].Id}).getContactsByAccountId();
		List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
		carePlanList[0].Status = 'Apheresis Pickup Date Scheduled';
		insert carePlanList;
		List<Order__c> orders = TestDataFactory.getOrders(new List<Id>{carePlanList[0].Id},patientByIds.values()[0].Id);
		orders[0].ApheresisPickUpDate__c = Date.Today().addDays(5);
		insert orders;
		String strPatientDetails = PatientsListViewController.fetchPatientDetailsForSiteCalendar(null);
		Test.stopTest();
		List<PatientsWrapper> lstPatients = (List<PatientsWrapper>) JSON.deserialize(strPatientDetails, List<PatientsWrapper>.Class);
		//THEN - Community user should be able to see the enrolled patients
		System.assertEquals(1, lstPatients.size(), 'Success');
	}
}