objects/Account/recordTypes/ApheresisSite.recordType-meta.xml
<RecordType>
    <fullName>ApheresisSite</fullName>
    <active>true</active>
    <description>Represents an apheresis site</description>
    <label>Apheresis Site</label>
</RecordType>

objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/AtlasOrderId__c.field-meta.xml
<CustomField>
    <fullName>AtlasOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration, stores the Atlas Order ID value.</description>
    <externalId>true</externalId>
    <label>Atlas Order ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/QTCPOtoSDStatus__c.field-meta.xml
<CustomField>
    <fullName>QTCPOtoSDStatus__c</fullName>
    <description>This field is used to keep a track of shipping status of an Order PO to the Specialty Distributor</description>
    <label>QTC PO to SD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
                <isActive>false</isActive>
                <label>Success</label>
            </value>
            <value>
                <fullName>Failure</fullName>
                <isActive>false</isActive>
                <label>Failure</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Manually Created</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SitePO__c.field-meta.xml
<CustomField>
    <fullName>SitePO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Site PO# from TCP.</description>
    <label>Site PO#</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

classes/PurchaseOrderServiceTest.cls
@isTest(SeeAllData=false)
public with sharing class PurchaseOrderServiceTest
{
	public static final String APHERESISSITE = 'ApheresisSite';
	public static final String CARTCOORDINATOR = 'CAR-T Coordinator';
	public static final String CONTACTROLE = 'ContactRole';
	public static final String TREATMENTSITE = 'TreatmentSite';
	private static final String RETRY = 'Retry';

	@testSetup static void testDataSetup()
	{
		List<Account> accountToBeInserted = TestDataFactory.getPatientAccountsList();

		List<String> listOfSitesNames = new List<String>();
		listOfSitesNames.add(TREATMENTSITE);
		listOfSitesNames.add(APHERESISSITE);

		Id PatientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.PatientRecordtype).getRecordTypeId();
		for (String siteName : listOfSitesNames)
		{
			accountToBeInserted.add(TestDataFactory.getBusinessAccountToInsert(siteName));
		}
		insert accountToBeInserted;

		List<Contact> siteContactList = new List<Contact>();
		Set<Id> patientIds = new Set<Id>();
		List<Account> businessAccounts = new List<Account>();
		for (Account site : accountToBeInserted)
		{
			if (PatientRecordTypeId.equals(site.RecordTypeId))
			{
				patientIds.add(site.Id);
			}
			else
			{
				siteContactList.add(TestDataFactory.getBusinessAccRelatedContacts(site.Name, site.Id));
				businessAccounts.add(site);
			}
		}
		insert siteContactList;

		Map<Id, Contact> contactsByAccountMap =
				((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
						.selectByAccountId(patientIds).getContactsByAccountId();
		List<AccountContactRelation> accConRelationList = new List<AccountContactRelation>();
		accConRelationList.addAll(TestDataFactory.getAccountContactRelationsToInsert(businessAccounts, contactsByAccountMap.values(), 2));
		insert accConRelationList;

		List<HealthCloudGA__ReciprocalRole__c> roleList = new List<HealthCloudGA__ReciprocalRole__c>();
		HealthCloudGA__ReciprocalRole__c carTRole = TestDataFactory.getContactRole(CARTCOORDINATOR, CONTACTROLE);
		roleList.add(carTRole);
		insert roleList;

		List<Account> accountContactList = ((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
				.selectContactsByAccountId(patientIds);
		List<Contact> personaccContactList = new List<Contact>();

		for (Account accounts : accountContactList)
		{
			personaccContactList.add(accounts.Contacts);
		}

		List<HealthCloudGA__ContactContactRelation__c> conRelationList = new List<HealthCloudGA__ContactContactRelation__c>();
		HealthCloudGA__ContactContactRelation__c conConRelation = TestDataFactory.getContactRelationsToInsert(siteContactList[0].Id, personaccContactList[0].Id, carTRole.Id);
		conRelationList.add(conConRelation);
		insert conRelationList;

		List<Case> caseList = TestDataFactory.getCareplanCasesList(personaccContactList);
		insert caseList;

	}

	@isTest static void itShouldValidateQTCPOtoSDStatus()
	{
		Test.startTest();

		Test.setMock(HttpCalloutMock.class, new PurchaseOrderServiceMock(true));
		Test.enableChangeDataCapture();

		//GIVEN - An order has been selected.
		OrdersSelector orderSelect = new OrdersSelector();
		List<Order__c> orders = orderSelect.selectAll();
		List<Order__c> lstOrderToUpdate = new List<Order__c>();
		Set<Id> sOrderId = new Set<Id>();

		//WHEN QTCPOtoSDStatus__c of an Order is updated as 'Retry'
		for (Order__c order : orders)
		{
			sOrderId.add(order.Id);
			Order__c ord = new Order__c();
			ord.Id = order.Id;
			ord.SitePO__c = '12334';
			ord.AtlasOrderId__c = '32332';
			ord.QTCPOtoSDStatus__c = RETRY;
			lstOrderToUpdate.add(ord);
		}
		update lstOrderToUpdate;
		List<Order__c> listOrders = orderSelect.selectOrdersByOrderId(sOrderId);

		//THEN QTCPOtoSDStatus__c  is updated success
		System.assert(!listOrders.isEmpty());
		System.assertEquals(listOrders[0].QTCPOtoSDStatus__c, RETRY);
		Test.stopTest();
	}
}