objects/Account/recordTypes/ApheresisSite.recordType-meta.xml
<RecordType>
    <fullName>ApheresisSite</fullName>
    <active>true</active>
    <description>Represents an apheresis site</description>
    <label>Apheresis Site</label>
</RecordType>

objects/Account/recordTypes/CryoSite.recordType-meta.xml
<RecordType>
    <fullName>CryoSite</fullName>
    <active>true</active>
    <description>Represents a cryo site</description>
    <label>Cryo Site</label>
</RecordType>

objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/HealthCloudGA__AccountAccountRelation__c/HealthCloudGA__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as between a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ApheresisPO__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration, stores the Apheresis PO # value.</description>
    <externalId>true</externalId>
    <label>Apheresis PO #</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/CarePlanID__c.field-meta.xml
<CustomField>
    <fullName>CarePlanID__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Care Plan.</description>
    <label>Care Plan ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/CartOrderId__c.field-meta.xml
<CustomField>
    <fullName>CartOrderId__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>This field is used for Integration. Stores the Order ID value.</description>
    <externalId>true</externalId>
    <label>CAR-T Order ID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

objects/Order__c/fields/ConfirmedFPDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedFPDeliveryDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Confirmed FP Delivery Date of the order.</description>
    <label>Confirmed DP Delivery Date from Site</label>
    <type>Date</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/FinalDPDateinVineti__c.field-meta.xml
<CustomField>
    <fullName>FinalDPDateinVineti__c</fullName>
    <description>Final DP Date that is coming from Vineti</description>
    <label>Final DP Date Updated in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/OrderRescheduledinVineti__c.field-meta.xml
<CustomField>
    <fullName>OrderRescheduledinVineti__c</fullName>
    <description>Order Rescheduled Updated in Vineti System.</description>
    <label>Order Rescheduled in Vineti</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>PO Status of the order.</description>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Pending</fullName>
                <default>true</default>
                <label>PO Pending</label>
            </value>
            <value>
                <fullName>PO Received</fullName>
            </value>
            <value>
                <fullName>PO Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SDPO__c.field-meta.xml
<CustomField>
    <fullName>SDPO__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>SD PO# integrated with SD.</description>
    <label>SD PO#</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

objects/Order__c/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Slot status of the order.</description>
    <inlineHelpText>If the Slot Status is &apos;Slot Rejected&apos; then please select a new Apheresis Pickup Date.</inlineHelpText>
    <label>Slot Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slot Requested</fullName>
            </value>
            <value>
                <fullName>Slot Confirmed</fullName>
            </value>
            <value>
                <fullName>Slot Blocked</fullName>
                <isActive>false</isActive>
                <label>Slot Blocked</label>
            </value>
            <value>
                <fullName>Slot Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/VinetiCOI__c.field-meta.xml
<CustomField>
    <fullName>VinetiCOI__c</fullName>
    <description>Field to track courier shipment details in the Vineti portal.</description>
    <externalId>true</externalId>
    <label>Vineti COI #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

classes/OrdersTest.cls
@IsTest(SeeAllData=false)
public class OrdersTest
{
	//GIVEN - A care plan has been created for a patient, and order has been generated.
	@TestSetup static void testDataSetup()
	{
		List<String> listOfSitesNames = new List<String>();
		List<Account> accToBeInserted = TestDataFactory.getPatientAccountsList();
		Id PatientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Label.PatientRecordtype).getRecordTypeId();
		listOfSitesNames.add('TreatmentSite');
		listOfSitesNames.add('ApheresisSite');
		listOfSitesNames.add('CryoSite');

		for (String siteName : listOfSitesNames)
		{
			accToBeInserted.add(TestDataFactory.getBusinessAccountToInsert(siteName));
		}
		insert accToBeInserted;

		List<Contact> contactList = new List<Contact>();
		List<String> listOfSites = new List<String>();
		listOfSites.add('Treatment Site');
		listOfSites.add('Apheresis Site');
		listOfSites.add('Cryo Site');

		for (Account site : accToBeInserted)
		{
			if (!PatientRecordTypeId.equals(site.RecordTypeId))
			{
				contactList.add(TestDataFactory.getBusinessAccRelatedContacts(site.Name, site.Id));
			}
		}

		insert contactList;

		List<HealthCloudGA__ReciprocalRole__c> roleList = new List<HealthCloudGA__ReciprocalRole__c>();

		HealthCloudGA__ReciprocalRole__c carTRole = TestDataFactory.getContactRole('CAR-T Coordinator', 'ContactRole');
		HealthCloudGA__ReciprocalRole__c aphSiteRole1 = TestDataFactory.getContactRole('Aphresis Site', 'AccountRole');
		HealthCloudGA__ReciprocalRole__c cryoSiteRole1 = TestDataFactory.getContactRole('Cryo Site', 'AccountRole');

		roleList.add(carTRole);
		roleList.add(aphSiteRole1);
		roleList.add(cryoSiteRole1);
		insert roleList;

		List<Account> accList = [SELECT Id, (SELECT Id,AccountId FROM Contacts) FROM Account LIMIT 5];
		List<Contact> conList = new List<Contact>();

		for (Account acc : accList)
		{
			conList.add(acc.Contacts);
		}

		List<HealthCloudGA__ContactContactRelation__c> conRelationList = new List<HealthCloudGA__ContactContactRelation__c>();
		HealthCloudGA__ContactContactRelation__c conRel1 = TestDataFactory.getContactRelationsToInsert(contactList[0].Id, conList[0].Id, carTRole.Id);
		conRelationList.add(conRel1);
		HealthCloudGA__ContactContactRelation__c conRel2 = TestDataFactory.getContactRelationsToInsert(contactList[1].Id, conList[1].Id, carTRole.Id);
		conRelationList.add(conRel2);
		insert conRelationList;
		List<HealthCloudGA__AccountAccountRelation__c> accRelationList = new List<HealthCloudGA__AccountAccountRelation__c>();
		HealthCloudGA__AccountAccountRelation__c accRel1 = TestDataFactory.getAccountRelationsToInsert(accToBeInserted[0].Id, accToBeInserted[1].Id, aphSiteRole1.Id);
		accRelationList.add(accRel1);
		HealthCloudGA__AccountAccountRelation__c accRel2 = TestDataFactory.getAccountRelationsToInsert(accToBeInserted[1].Id, accToBeInserted[3].Id, cryoSiteRole1.Id);
		accRelationList.add(accRel2);

		insert accRelationList;
		List<Case> caseList = TestDataFactory.getCareplanCasesList(conList);
		insert caseList;
		testDataSetup2(caseList);
	}

	private static void testDataSetup2(List<Case> caseList)
	{
		List<Id> listOfCaseIds = new List<Id>();

		if (!caseList.isEmpty())
		{
			for (Case c : caseList)
			{
				listOfCaseIds.add(c.Id);
			}
		}

		List<HealthCloudGA__CarePlanGoal__c> listOfGoals = TestDataFactory.getGoals(listOfCaseIds, Label.OrderPlacementGoal);
		insert listOfGoals;

		List<Id> listOfGoalIds = new List<Id>();

		for (HealthCloudGA__CarePlanGoal__c goal : listOfGoals)
		{
			listOfGoalIds.add(goal.Id);
		}

		List<String> listOfTasksSubject = new List<String>();
		listOfTasksSubject.add(Label.SelectAnApheresisPickupDateTask);
		listOfTasksSubject.add(Label.SubmitTheRequestForSchedulingApheresisPickupTask);
		listOfTasksSubject.add('Test Task');

		List<Task> listOfTasks = new List<Task>();
		listOfTasks = TestDataFactory.getTasks(listOfGoalIds[0], listOfTasksSubject);
		listOfTasks[0].WhatId = caseList[0].Id;
		listOfTasks[1].WhatId = caseList[1].Id;
		insert listOfTasks;

		List<Order__c> orderList = [SELECT Id,SlotStatus__c,SDPO__c,OrderStatus__c,POStatus__c,CarePlanID__c FROM Order__c LIMIT 5];
		for (Order__c ord : orderList)
		{
			ord.SlotStatus__c = StaticConstants.softSlotConfirmed;
		}
		update orderList;

		List<Order__c> orderListWithSDPOAsNotNull = [SELECT Id,SlotStatus__c,SDPO__c,OrderStatus__c,POStatus__c,CarePlanID__c FROM Order__c LIMIT 5];
		for (Order__c ord : orderListWithSDPOAsNotNull)
		{
			ord.SDPO__c = '34567890';
		}
		update orderListWithSDPOAsNotNull;
	}


	@IsTest static void itShouldGetOrderDetails()
	{
		List<Order__c> returnListOfOrders = new List<Order__c>();
		List<Id> listOfOrderIds = new List<Id>();
		//WHEN - The order Id has been passed to the server-side method named getOrderDetails() of the Orders class.
		Test.startTest();
		List<Order__c> listOfOrders = [SELECT Id,Name,CarePlanID__c,ApheresisPickUpDate__c FROM Order__c LIMIT 5];

		for (Order__c order : listOfOrders)
		{
			listOfOrderIds.add(order.Id);
		}

		returnListOfOrders = OrderPlacementController.getOrderDetails(listOfOrderIds);
		Test.stopTest();
		//THEN - The order data has been returned for the order ids that were passed to the getOrderDetails() method of the Orders class.
		System.assertEquals(returnListOfOrders.size(), listOfOrders.size());

		try
		{
			returnListOfOrders = OrderPlacementController.getOrderDetails(null);
		}
		catch (Exception e)
		{
			System.assertEquals(e.getMessage(), e.getMessage());
		}
	}

	@IsTest static void itShouldUpdateOrdersSlotConfirmed()
	{
		//WHEN Slot Status of an Order is updated as 'Soft Slot Confirmed'
		Test.startTest();
		List<Order__c> updatedOrdersList = [SELECT Id,SlotStatus__c,SDPO__c,OrderStatus__c,POStatus__c,CarePlanID__c FROM Order__c WHERE SDPO__c = NULL AND SlotStatus__c = :StaticConstants.softSlotConfirmed LIMIT 5];

		Test.stopTest();
		//THEN Check if the Order Status & PO Status is updated accordingly
		for (Order__c order : updatedOrdersList)
		{
			System.assertEquals(StaticConstants.orderVerified, order.OrderStatus__c);
			System.assertEquals(StaticConstants.POPending, order.POStatus__c);
		}
	}

	@IsTest static void itShouldUpdateOrdersWithSDPOAsNotNull()
	{
		//WHEN SDPO of an Order is populated
		Test.startTest();
		List<Order__c> updatedOrdersList = [SELECT Id,SDPO__c,OrderStatus__c,POStatus__c,CarePlanID__c FROM Order__c WHERE SDPO__c != NULL LIMIT 5];

		Test.stopTest();
		//THEN Check if the PO Status is updated accordingly
		System.assertEquals(StaticConstants.POReceived, updatedOrdersList[2].POStatus__c);
	}

	@IsTest static void itShouldPopulateOrderNameAndCartOrderId()
	{
		//GIVEN A care plan has been created for a patient.
		Test.startTest();

		//WHEN Order is inserted
		List<Order__c> updatedOrdersList = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType)).selectAll();

		Test.stopTest();
		//THEN it should populate Name and CartOrderId__c with the same value
		System.assert(!updatedOrdersList.isEmpty());

		Order__c testOrder = updatedOrdersList[0];
		System.assertEquals(testOrder.Name, testOrder.CartOrderId__c);
	}

	@IsTest static void itShouldCloseTaskBySubject(){
		//GIVEN - A task has been created for a care plan.
		Case carePlan = ((CasesSelector) Application.Selector.newInstance(Case.SObjectType))
		.selectAll()[0];

		Order__c ord = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType))
		.selectOrdersByCarePlanId(new Set<Id>{
			carePlan.Id
		})[0];

		List<Task> taskToInsert = TestDataFactory.getCarePlanTasks(carePlan.Id, new List<String>{
			Label.OrderReschedule,
			Label.ConfirmDeliveryDate,
			Label.OrderPlacement
		});

		insert taskToInsert;

		//WHEN - VinetiCOI__c or FinalDPDateinVineti__c or OrderRescheduledinVineti__c in Order__c is updated
		Test.startTest();
		ord.VinetiCOI__c = 'Vineti COI Number updated';
		ord.FinalDPDateinVineti__c = 'Final DP Date updated';
		update ord;
		Test.stopTest();

		//THEN - it should mark its related task as closed
		system.assertEquals(2, [SELECT COUNT() FROM Task WHERE Status = 'completed']);
	}

	/*@IsTest
  private static void itShouldCreateAdhocTasksforVeinToVein()
   {
	   List<Order__c> listOfOrdersUpdated = new List<Order__c>();
	   Order__c orderToUpdate = new Order__c();

	   Test.startTest();
	   //GIVEN- An Order has been created with a Care Plan related
	   List<Order__c> listOfOrders = ((OrdersSelector) Application.Selector.newInstance(Order__c.SObjectType)).selectAll();
	   orderToUpdate = listOfOrders[0];

	   //WHEN - the ApheresisPO__c is populated, the ConfirmedFPDeliveryDate__c is populated
	   //and the OrderStatus__c is updated to Order Rescheduled in the order .
	   orderToUpdate.OrderStatus__c = 'Order Rescheduled';
	   update orderToUpdate;

	   orderToUpdate.ApheresisPO__c = '12312';
	   update orderToUpdate;

	   orderToUpdate.ConfirmedFPDeliveryDate__c = System.today();
	   update orderToUpdate;

	   List<Task> newTasks =  ((TasksSelector) Application.Selector.newInstance(Task.SObjectType)).selectAllTasks();

	   Map<String,Id> tasksCreated = new Map<String,Id>();

	   for(Task objTask : newTasks)
	   {
		   if(objTask.WhatId == orderToUpdate.CarePlanID__c)
		   {
			   tasksCreated.put(objTask.Subject,objTask.WhatId);
		   }
	   }
	   Test.stopTest();

	   //THEN - It should create a task with subject 'Setup a new order in Vineti on receipt of Aph PO for order placement',
	   //another task with subject 'Update/create the order in Vineti' and another with subject
	   //'Update the DP Delivery Date of the order on receiving the confirmed DP Delivery Date from the site'.
	   System.assertEquals(tasksCreated.containsKey(Label.OrderReschedule) , true);
	   System.assertEquals(tasksCreated.containsKey(Label.OrderPlacement) , true);
	   System.assertEquals(tasksCreated.containsKey(Label.ConfirmDeliveryDate) , true);
   }*/
}