objects/Account/recordTypes/TreatmentSite.recordType-meta.xml
<RecordType>
    <fullName>TreatmentSite</fullName>
    <active>true</active>
    <description>Represents a treatment site</description>
    <label>Treatment Site</label>
</RecordType>

objects/Case/fields/BeginPatientSupportEligibilityCheck__c.field-meta.xml
<CustomField>
    <fullName>BeginPatientSupportEligibilityCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to capture Patient’s confirmation for Service Program</description>
    <label>Begin Patient Support Eligibility Check</label>
    <type>Checkbox</type>
</CustomField>

objects/Contact/fields/SitePersona__c.field-meta.xml
<CustomField>
    <fullName>SitePersona__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>List of personas at the Treatment Center Portal.</description>
    <label>Site Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAR-T Coordinator</fullName>
            </value>
            <value>
                <fullName>Pharmacist</fullName>
            </value>
            <value>
                <fullName>Physician</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/HealthCloudGA__ContactContactRelation__c/HealthCloudGA__ContactContactRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between any two individuals.</description>
    <label>Contact-Contact Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Contact Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Contact Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Order information related to the Care Plan.</description>
	<historyRetentionPolicy>
        <archiveAfterMonths>18</archiveAfterMonths>
        <archiveRetentionYears>2</archiveRetentionYears>
        <description>HIPAA Audit Log Retention Order__c</description>
        <gracePeriodDays>0</gracePeriodDays>
    </historyRetentionPolicy>
    <label>Order</label>
    <nameField>
        <label>Order ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order__c/fields/ApheresisPickUpDate__c.field-meta.xml
<CustomField>
    <fullName>ApheresisPickUpDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Apheresis Pick-up date of the order.</description>
    <label>Apheresis Pick-up Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ConfirmedFPDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedFPDeliveryDate__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Confirmed FP Delivery Date of the order.</description>
    <label>Confirmed DP Delivery Date from Site</label>
    <type>Date</type>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
</CustomField>

objects/Order__c/fields/Coordinator__c.field-meta.xml
<CustomField>
    <fullName>Coordinator__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAR-T Coordinator associated to the related Care Plan.</description>
    <label>CAR-T Coordinator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Order__c/fields/InfusionDate__c.field-meta.xml
<CustomField>
    <fullName>InfusionDate__c</fullName>
    <description>Infusion Date of the drug.</description>
    <label>Infusion Date</label>
    <type>Date</type>
</CustomField>

objects/Order__c/fields/ManufacturingStatus__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Manufacturing Status related to the order.</description>
    <label>Manufacturing Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>True</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>QC/QA Complete</fullName>
            </value>
            <value>
                <fullName>Manufacturing Started</fullName>
            </value>
            <value>
                <fullName>Manufacturing Complete</fullName>
            </value>
            <value>
                <fullName>QR Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Status of the order.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Order Verified</fullName>
            </value>
            <value>
                <fullName>Order In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Order Rescheduled</fullName>
            </value>
            <value>
                <fullName>Order Cancellation Requested</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivery Date Scheduled</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
            <value>
                <fullName>Infusion Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>PO Status of the order.</description>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PO Pending</fullName>
                <default>true</default>
                <label>PO Pending</label>
            </value>
            <value>
                <fullName>PO Received</fullName>
            </value>
            <value>
                <fullName>PO Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/ReasonForOrderWithdrawal__c.field-meta.xml
<CustomField>
    <fullName>ReasonForOrderWithdrawal__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Reason for Order Withdrawal.</description>
    <label>Reason for Order Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Patient withdrew consent for treatment with Janssen CAR-T</fullName>
            </value>
            <value>
                <fullName>Patient health-related reason</fullName>
            </value>
            <value>
                <fullName>Other patient-related reason</fullName>
            </value>
            <value>
                <fullName>Other non-patient related reason</fullName>
            </value>
            <value>
                <fullName>Patient Health – Deceased</fullName>
                <isActive>false</isActive>
                <label>Patient Health – Deceased</label>
            </value>
            <value>
                <fullName>Patient Health – Disease Progression</fullName>
                <isActive>false</isActive>
                <label>Patient Health – Disease Progression</label>
            </value>
            <value>
                <fullName>Patient opted out of treatment</fullName>
                <isActive>false</isActive>
                <label>Patient opted out of treatment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Shipping status of the order.</description>
    <label>Shipping Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shipping Fresh Cells</fullName>
            </value>
            <value>
                <fullName>Fresh Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Cryo-ed Cells</fullName>
            </value>
            <value>
                <fullName>Cryo-ed Cells Delivered</fullName>
            </value>
            <value>
                <fullName>Shipping Drug Product</fullName>
            </value>
            <value>
                <fullName>Drug Product Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Order__c/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <complianceGroup>GxP</complianceGroup>
    <description>Slot status of the order.</description>
    <inlineHelpText>If the Slot Status is &apos;Slot Rejected&apos; then please select a new Apheresis Pickup Date.</inlineHelpText>
    <label>Slot Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Slot Requested</fullName>
            </value>
            <value>
                <fullName>Slot Confirmed</fullName>
            </value>
            <value>
                <fullName>Slot Blocked</fullName>
                <isActive>false</isActive>
                <label>Slot Blocked</label>
            </value>
            <value>
                <fullName>Slot Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/PatientServicesEnrollee__c/PatientServicesEnrollee__c.object-meta.xml
<CustomObject>
    <label>Patient Services Enrollee</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Patient Services Enrollee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Services Enrollees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TreatmentJourneySteps__mdt/TreatmentJourneySteps__mdt.object-meta.xml
<CustomObject>
    <label>Treatment Journey Steps</label>
    <pluralLabel>Treatment Journey Steps</pluralLabel>
</CustomObject>

objects/TreatmentJourneySteps__mdt/fields/ManufacturingStatus__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingStatus__c</fullName>
    <description>To store Manufacturing Status as per matrix.</description>
    <label>Manufacturing Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/OrderStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderStatus__c</fullName>
    <description>To store Order Status as per matrix for comparison with the Order Status of the Patient in Treatment Journey Screen</description>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/POStatus__c.field-meta.xml
<CustomField>
    <fullName>POStatus__c</fullName>
    <description>To store PO Status as per matrix for comparison with the PO Status of the Patients Order in Treatment Journey Screen</description>
    <label>PO Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/ShippingStatus__c.field-meta.xml
<CustomField>
    <fullName>ShippingStatus__c</fullName>
    <description>To populate the corresponding Shipping Section Status based on Order, Care Plan, PO and Slot statuses in Treatment Journey Screen</description>
    <label>Shipping Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/TreatmentJourneySteps__mdt/fields/SlotStatus__c.field-meta.xml
<CustomField>
    <fullName>SlotStatus__c</fullName>
    <description>To store Slot Status as per matrix for comparison with the Slot Status of the Patients Order in Treatment Journey Screen</description>
    <label>Slot Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

classes/PatientJourneyControllerTest.cls
@IsTest(SeeAllData=false)
public class PatientJourneyControllerTest
{
	public static final String CARTCOORDINATOR = 'CAR-T Coordinator';
	public static final String PATIENT = 'Patient';
	public static final String PATIENTSERVICEELIGIBILITY = 'true';
	public static final String PHYSICIAN = 'Physician';
	public static final string REASONFORCANCELLATION = 'Patient health-related reason';
	public static final string strPatientRecordType = 'Patient';
	public static final string strSuccess = 'SUCCESS';
	public static final String TreatmentSiteRecordTypeDeveloperName = 'TreatmentSite';
	public static final String SCRIPTTHROWNEXCEPTION = 'Script-thrown exception';


	@testSetup
	static void setup()
	{
		List<Account> patientsToBeInserted = TestDataFactory.getPatientAccountsList();
		insert patientsToBeInserted;
	}

	@IsTest
	public static void itShouldGetPatientDocuments()
	{
		Test.startTest();
		try
		{
			//GIVEN - The patients are enrolled in the system and required consent files are uploaded
			Map<Id, Account> patientIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id> {patientIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<PatientServicesEnrollee__c> lstpPatientServicesEnrolleesEnrollee = new List<PatientServicesEnrollee__c>();
			for (Account objAccount : patientIds.values())
			{
				lstpPatientServicesEnrolleesEnrollee.add(TestDataFactory.getPatientServicesEnrollee(carePlanList[0].Id, objAccount.Id));
			}

			insert lstpPatientServicesEnrolleesEnrollee;

			List<ContentDocument> contentVersionDocs = TestDataFactory.createAttachment(10);

			List<ContentDocumentLink> lstContentLink = new List<ContentDocumentLink>();

			for (PatientServicesEnrollee__c objEnrollee : lstpPatientServicesEnrolleesEnrollee)
			{
				lstContentLink.add(TestDataFactory.getVisibleContentDocumentLink(objEnrollee.Id, contentVersionDocs[0].Id));
			}

			insert lstContentLink;

			//WHEN - The CAR-T CO logs into TCP and navigates to Patient Journey page
			List<ContentVersion> docs = PatientJourneyController.getDocumentsByPatientId(patientIds.values()[0].Id);
			//THEN - CAR-T Coordinator should able to see documents uploaded for a given patient
			System.assertEquals(1, docs.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldFetchBussinessDayDueForReschedule()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system and apheresis pickup slot is booked
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id> {carePlanList[0].Id}, patientByIds.values()[0].Id);
			orders[0].ApheresisPickUpDate__c = Date.Today().addDays(5);
			insert orders;

			TestDataFactory.getSflibSettingsList();
			//WHEN - The apheresis due date is greater then one business day
			Boolean isBusinessDue = PatientJourneyController.isBussinessDayDueForReschedule(patientByIds.values()[0].Id);
			//THEN - Then patient is eligible for reschedule
			System.assertEquals(true, isBusinessDue, strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldFetchPatientServiceEligibilty()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			//WHEN - A CO navigates to Patient Journey screen for a Patient
			List<Case> casesList = PatientJourneyController.fetchPatientServiceEligibilty(patientByIds.values()[0].Id);
			//THEN - Eligibility Information for the patient should be retrieved
			System.assertEquals(1, casesList.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION , strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldFetchPatientServiceEnrollees()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient is enrolled in the system
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<PatientServicesEnrollee__c> lstpPatientServicesEnrolleesEnrollee = new List<PatientServicesEnrollee__c>();
			for (Account objAccount : patientByIds.values())
			{
				lstpPatientServicesEnrolleesEnrollee.add(TestDataFactory.getPatientServicesEnrollee(carePlanList[0].Id, objAccount.Id));
			}

			insert lstpPatientServicesEnrolleesEnrollee;

			//WHEN - A CO navigates to Patient Journey screen for a Patient
			List<PatientServicesEnrollee__c> lstEnrollees = PatientJourneyController.fetchPatientServiceEnrollees(patientByIds.values()[0].Id);
			//THEN - Patient Services Enrollees Information for the patient should be retrieved
			System.assertEquals(1, lstEnrollees.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateCarePlan()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and the Service Program Eligibiity was unchecked during Enrollment
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			//WHEN - A CO navigates to Patient Journey screen for a Patient and Submits Request for Service Program Eligibiity
			PatientJourneyController.updateCarePlan(patientByIds.values()[0].Id, PATIENTSERVICEELIGIBILITY);

			Map<Id, Case> casesByAccountId =
					((CasesSelector) Application.Selector.newInstance(Case.SObjectType))
							.selectByPatientAccountId(new Set<Id> {patientByIds.values()[0].Id}).getCasesByAccountId();
			if (casesByAccountId.isEmpty()) return;
			//THEN - The Patient should be made eligible for the Service Program
			System.assertEquals(true, casesByAccountId.values()[0].BeginPatientSupportEligibilityCheck__c, strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION , strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldgetDetailsByPatientId()
	{
		Test.startTest();
		try
		{
			//GIVEN -  A patient has corresponding  treating physician  and cart CO
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();
			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<HealthCloudGA__ReciprocalRole__c> roleList = new List<HealthCloudGA__ReciprocalRole__c>();
			HealthCloudGA__ReciprocalRole__c carTRole =
					TestDataFactory.getContactRole(CARTCOORDINATOR, 'ContactRole');
			HealthCloudGA__ReciprocalRole__c physicianRole =
					TestDataFactory.getContactRole(PHYSICIAN, 'ContactRole');
			roleList.add(carTRole);
			roleList.add(physicianRole);
			insert roleList;

			List<Account> treatmentSiteAccountsList =
					TestDataFactory.getBusinessAccountsList(TREATMENTSITERECORDTYPEDEVELOPERNAME, 10);
			insert treatmentSiteAccountsList;

			List<Contact> contacts = new List<Contact>();
			Contact objContact1 =
					TestDataFactory.getBusinessAccRelatedContacts('test1', treatmentSiteAccountsList[0].Id);
			objContact1.SitePersona__c = CARTCOORDINATOR;
			Contact objContact2 =
					TestDataFactory.getBusinessAccRelatedContacts('test2', treatmentSiteAccountsList[1].Id);
			objContact2.SitePersona__c = CARTCOORDINATOR;
			Contact objContact3 =
					TestDataFactory.getBusinessAccRelatedContacts('test3', treatmentSiteAccountsList[2].Id);
			objContact3.SitePersona__c = CARTCOORDINATOR;
			Contact objContact4 =
					TestDataFactory.getBusinessAccRelatedContacts('test4', treatmentSiteAccountsList[3].Id);
			objContact4.SitePersona__c = CARTCOORDINATOR;
			Contact objContact5 =
					TestDataFactory.getBusinessAccRelatedContacts('test5', treatmentSiteAccountsList[4].Id);
			objContact5.SitePersona__c = CARTCOORDINATOR;
			contacts.add(objContact1);
			contacts.add(objContact2);
			contacts.add(objContact3);
			contacts.add(objContact4);
			contacts.add(objContact5);
			insert contacts;
			List<HealthCloudGA__ContactContactRelation__c> conRelationList =
					new List<HealthCloudGA__ContactContactRelation__c>();
			HealthCloudGA__ContactContactRelation__c conRel1 =
					TestDataFactory.getContactRelationsToInsert(contacts[0].Id, contactsByAccountIds.values()[0].Id, carTRole.Id);
			conRelationList.add(conRel1);
			HealthCloudGA__ContactContactRelation__c conRel2 =
					TestDataFactory.getContactRelationsToInsert(contacts[1].Id, contactsByAccountIds.values()[1].Id, physicianRole.Id);
			conRelationList.add(conRel2);
			insert conRelationList;
			//WHEN - A CO navigates to Patient Journey screen for a Patient
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);
			//THEN - treating physician and car-t co-ordinator Information for the patient should be retrieved
			System.assertEquals(2, conRelationList.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION , strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldGetApheresisStatus()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id>{patientByIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			carePlanList[0].Status = 'Apheresis Pickup Date Scheduled';
			insert carePlanList;
			Account trtSite = TestDataFactory.getBusinessAccountToInsert(StaticConstants.TreatmentSiteRecordTypeDeveloperName);
			insert trtSite;
			Contact orderContact = TestDataFactory.getBusinessAccRelatedContacts('test', trtSite.id);
			insert orderContact;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id>{carePlanList[0].Id},patientByIds.values()[0].Id);
			orders[0].OrderStatus__c = 'Order Verified';
			orders[0].POStatus__c = 'PO Received';
			orders[0].SlotStatus__c = 'Slot Confirmed';
			orders[0].Coordinator__c = orderContact.Id;
			insert orders;
			//WHEN - A CO navigates to Patient Journey screen for the Patient whose Apheresis is either inprogress or Completed
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);
			//THEN - The CO should be able to view corresponding Patient's Apheresis Section details.
			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newInstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectApheresisStepsByStatuses(carePlanList[0].Status, orders[0].OrderStatus__c, orders[0].SlotStatus__c, orders[0].POStatus__c);

			System.assertEquals(1, treatmentJourneySteps.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldGetManufacturingDetails()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id> {patientByIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id> {carePlanList[0].Id}, patientByIds.values()[0].Id);
			orders[0].ManufacturingStatus__c = 'QR Complete';
			insert orders;
			//WHEN - A CO navigates to Patient Journey screen for the Patient whose Manufacturing is either inprogress or Completed
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);
			//THEN - The CO should be able to view corresponding Patient's Manufacturing Section details.
			System.assertEquals(1, orders.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldGetManufacturingStatus()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id> {patientByIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			carePlanList[0].Status = 'Manufacturing';
			insert carePlanList;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id> {carePlanList[0].Id}, patientByIds.values()[0].Id);
			orders[0].OrderStatus__c = 'Order In Progress';
			orders[0].POStatus__c = 'PO Received';
			orders[0].SlotStatus__c = 'Slot Confirmed';
			orders[0].ManufacturingStatus__c = 'Not Started';
			insert orders;

			//WHEN - A CO navigates to Patient Journey screen for the Patient whose Manufacturing is Not Started
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);

			//THEN - The CO should be able to view corresponding Patient's Manufacturing Section details.
			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newInstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectManufacturingStepsByStatuses(carePlanList[0].Status, orders[0].OrderStatus__c, orders[0].SlotStatus__c, orders[0].POStatus__c, orders[0].ManufacturingStatus__c);

			System.assertEquals(1, treatmentJourneySteps.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldGetShippingStatus()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id> {patientByIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			carePlanList[0].Status = 'Shipping Cells to Manufacturing Site';
			insert carePlanList;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id> {carePlanList[0].Id}, patientByIds.values()[0].Id);
			orders[0].OrderStatus__c = 'Order In Progress';
			orders[0].POStatus__c = 'PO Received';
			orders[0].SlotStatus__c = 'Slot Confirmed';
			orders[0].ShippingStatus__c = 'Shipping Cryo-ed Cells';
			insert orders;

			//WHEN - A CO navigates to Patient Journey screen for the Patient whose Shipping status is Shipping Cryo-ed Cells
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);

			//THEN - The CO should be able to view corresponding Patient's Shipping Section details.
			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newInstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectShippingStepsByStatuses(carePlanList[0].Status, orders[0].OrderStatus__c, orders[0].SlotStatus__c, orders[0].POStatus__c, orders[0].ShippingStatus__c);

			System.assertEquals(1, treatmentJourneySteps.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldGetDeliveryStatus()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(new Set<Id> {patientByIds.values()[0].Id}).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			carePlanList[0].Status = 'Drug Product Shipped';
			insert carePlanList;

			List<Order__c> orders = TestDataFactory.getOrders(new List<Id> {carePlanList[0].Id}, patientByIds.values()[0].Id);
			orders[0].OrderStatus__c = 'Drug Product Delivery Date Scheduled';
			orders[0].ManufacturingStatus__c = 'QR Complete';
			orders[0].POStatus__c = 'PO Received';
			orders[0].SlotStatus__c = 'Slot Confirmed';
			orders[0].ShippingStatus__c = 'Shipping Drug Product';
			insert orders;

			//WHEN - A CO navigates to Patient Journey screen for the Patient whose Shipping status/Delivery Status is Shipping Drug Product
			PatientJourneyController.getDetailsByPatientId(patientByIds.values()[0].Id);

			//THEN - The CO should be able to view corresponding Patient's Delivery Section details.
			List<TreatmentJourneySteps__mdt> treatmentJourneySteps = ((TreatmentJourneyStepsSelector)
					Application.Selector.newInstance(TreatmentJourneySteps__mdt.SObjectType))
					.selectDeliveryStepsByStatuses(carePlanList[0].Status, orders[0].OrderStatus__c, orders[0].SlotStatus__c, orders[0].POStatus__c, orders[0].ShippingStatus__c, orders[0].ManufacturingStatus__c, orders[0].ShippingStatus__c);

			System.assertEquals(1, treatmentJourneySteps.size(), strSuccess);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateOrder()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});
			ordersList[0].OrderStatus__c = 'Order Cancellation Requested';
			update ordersList;

			//WHEN - A CO navigates to Patient Journey screen for a Patient and Submits Request for Order Cancellation
			PatientJourneyController.updateOrder(patientByIds.values()[0].Id, REASONFORCANCELLATION);

			//THEN - The Patient should be able to raise request for order cancellation
			List<Order__c> updatedOrdersList = new OrdersSelector().selectOrdersByOrderId(
					sflib_ArrayUtils.pluckIdField(ordersList, Order__c.Id));
			System.assert(!updatedOrdersList.isEmpty());
			System.assertEquals(REASONFORCANCELLATION, updatedOrdersList[0].ReasonForOrderWithdrawal__c);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateDeliveryDateOnOrder()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});

			//WHEN - A CO navigates to Patient Journey screen for a Patient and updates the Confirmed FP Delivery Date
			PatientJourneyController.updateDeliveryDateOnOrder(patientByIds.values()[0].Id, String.valueOf(System.today()));

			//THEN - The Patient should be able to see the updated Confirmed FP Delivery Date on the Patient Journey Screen
			List<Order__c> updatedOrdersList = new OrdersSelector().selectOrdersByOrderId(
					sflib_ArrayUtils.pluckIdField(ordersList, Order__c.Id));
			System.assert(!updatedOrdersList.isEmpty());
			System.assertEquals(System.today(), updatedOrdersList[0].ConfirmedFPDeliveryDate__c);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

	@IsTest
	public static void itShouldUpdateInfusedDateOnOrder()
	{
		Test.startTest();
		try
		{
			//GIVEN - A patient is enrolled and Order is placed successfully
			Map<Id, Account> patientByIds = new Accounts(((AccountsSelector) Application.Selector.newInstance(Account.SObjectType))
					.selectAll()
					.getByRecordTypeDeveloperName(new Set<String> {strPatientRecordType}))
					.getById();

			Map<Id, Contact> contactsByAccountIds =
					((ContactsSelector) Application.Selector.newInstance(Contact.SObjectType))
							.selectByAccountId(patientByIds.keySet()).getContactsByAccountId();

			List<Case> carePlanList = TestDataFactory.getCareplanCasesList(contactsByAccountIds.values());
			insert carePlanList;

			List<Order__c> ordersList = ((OrdersSelector) Application.Selector
					.newInstance(Order__c.SObjectType))
					.selectOrdersByCarePlanId(new Set<Id> {carePlanList[0].Id});

			//WHEN - A CO navigates to Patient Journey screen for a Patient and updates the infusion date
			PatientJourneyController.updateInfusedDateOnOrder(patientByIds.values()[0].Id, String.valueOf(System.today()));

			//THEN - The Patient should be able to see the updated Infusion Date on the Patient Journey Screen
			List<Order__c> updatedOrdersList = new OrdersSelector().selectOrdersByOrderId(
					sflib_ArrayUtils.pluckIdField(ordersList, Order__c.Id));
			System.assert(!updatedOrdersList.isEmpty());
			System.assertEquals(System.today(), updatedOrdersList[0].InfusionDate__c);
		}
		catch (AuraHandledException ex)
		{
			//THEN - check for Exception being thrown
			System.assertEquals(ex.getMessage(), SCRIPTTHROWNEXCEPTION, strSuccess);
		}
		Test.stopTest();
	}

}